# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BeaconConceptCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category': 'str',
        'local_category': 'str',
        'description': 'str',
        'frequency': 'int'
    }

    attribute_map = {
        'category': 'category',
        'local_category': 'local_category',
        'description': 'description',
        'frequency': 'frequency'
    }

    def __init__(self, category=None, local_category=None, description=None, frequency=None):  # noqa: E501
        """BeaconConceptCategory - a model defined in Swagger"""  # noqa: E501

        self._category = None
        self._local_category = None
        self._description = None
        self._frequency = None
        self.discriminator = None

        if category is not None:
            self.category = category
        if local_category is not None:
            self.local_category = local_category
        if description is not None:
            self.description = description
        if frequency is not None:
            self.frequency = frequency

    @property
    def category(self):
        """Gets the category of this BeaconConceptCategory.  # noqa: E501

        human readable name (\"rdfs:label\")  # noqa: E501

        :return: The category of this BeaconConceptCategory.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this BeaconConceptCategory.

        human readable name (\"rdfs:label\")  # noqa: E501

        :param category: The category of this BeaconConceptCategory.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def local_category(self):
        """Gets the local_category of this BeaconConceptCategory.  # noqa: E501

        the locally designated CURIE of the concept category  # noqa: E501

        :return: The local_category of this BeaconConceptCategory.  # noqa: E501
        :rtype: str
        """
        return self._local_category

    @local_category.setter
    def local_category(self, local_category):
        """Sets the local_category of this BeaconConceptCategory.

        the locally designated CURIE of the concept category  # noqa: E501

        :param local_category: The local_category of this BeaconConceptCategory.  # noqa: E501
        :type: str
        """

        self._local_category = local_category

    @property
    def description(self):
        """Gets the description of this BeaconConceptCategory.  # noqa: E501

        human readable name definition of the category  # noqa: E501

        :return: The description of this BeaconConceptCategory.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this BeaconConceptCategory.

        human readable name definition of the category  # noqa: E501

        :param description: The description of this BeaconConceptCategory.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def frequency(self):
        """Gets the frequency of this BeaconConceptCategory.  # noqa: E501

        the number of concept entries of the specified type in the beacon knowledge base  # noqa: E501

        :return: The frequency of this BeaconConceptCategory.  # noqa: E501
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this BeaconConceptCategory.

        the number of concept entries of the specified type in the beacon knowledge base  # noqa: E501

        :param frequency: The frequency of this BeaconConceptCategory.  # noqa: E501
        :type: int
        """

        self._frequency = frequency

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BeaconConceptCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
