language: python
cache: pip
env:
  matrix:
    - TOXENV=check
matrix:
  include:
    - python: '2.7'
      env:
       - TOXENV=py27,report,coveralls,codecov
    - python: '3.5'
      env:
       - TOXENV=py35,report,coveralls,codecov
    - python: '3.6'
      env:
       - TOXENV=py36,report,coveralls,codecov
    - python: '3.7'
      sudo: required
      dist: xenial
      env:
       - TOXENV=py37,report,coveralls,codecov
install:
  - pip install tox
script:
  - tox -v
