
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-02T16:03:57+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "f094f34f31ee0d6e738f71ecb564d74ad2df2c9d",
 "version": "0.1.7+27.gf094f34.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
