language: python
python:
  - "2.7"
  - "3.6"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - name: "Python: 3.7"
      python: "3.7"
      dist: xenial
      sudo: true

sudo: false

cache: pip

install:
  - pip install -U pip setuptools wheel
  - pip install -r dev.txt -r requirements.txt

script:
  - py.test --cov=. hpfeeds
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8 hpfeeds; fi

after_success:
  - codecov
