
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-07T13:27:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c420dda42bcb9b5fdfb919cc150925537b2c6bb",
 "version": "0.1.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
