---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - name: rest-api-server
        image: {{WORKFLOW_CONTROLLER_IMAGE}}
        {% if DEPLOYMENT != 'prod' %}
        command: ["/bin/sh","-c"]
        args: ["flask run --host=0.0.0.0"]
        {% endif %}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        {%- if DEPLOYMENT != 'prod' %}
        tty: true
        stdin: true
        {% endif %}
        volumeMounts:
        - mountPath: "/reana"
          name: reana-shared-volume
        {% set mountpoints=RWFC_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        ports:
        - containerPort: 5000
          name: http
        env:
        {% set environment=RWFC_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
      - name: job-status-consumer
        image: {{WORKFLOW_CONTROLLER_IMAGE}}
        command: ["flask", "consume-job-queue"]
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        volumeMounts:
        - mountPath: "/reana"
          name: reana-shared-volume
        env:
        {% set environment=RWFC_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
      volumes:
      - name: reana-shared-volume
        {% if DEPLOYMENT == 'prod' %}
        persistentVolumeClaim:
          claimName: manila-cephfs-pvc
          readOnly: false
        {% else %}
        hostPath:
          path: {{ROOT_PATH}}
        {% endif %}
      {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
