
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "27a85ad177b70222a184c2b84a6c0b1abdefc01c",
 "version": "1.0.0.post.dev786"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
