
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-06T11:38:26-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe250ccb8b49cc23d1da47f8a3493450a5ea923f",
 "version": "v1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
