[tool.poetry]
name = "pyberny"
version = "0.4.2"
description = "Molecular/crystal structure optimizer"
readme = "README.md"
authors = ["Jan Hermann <dev@janhermann.cz>"]
repository = "https://github.com/azag0/pyberny"
documentation = "https://azag0.github.io/pyberny"
license = "MPL-2.0"
packages = [
    { include = "berny" },
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
]

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
numpy = "^1.15"
pytest = { version = "^3.6", optional = true }
sphinx = { version = "^1.7", optional = true }
coverage = { version = "^4.5", optional = true }
toml = { version = "^0.10.0", optional = true }

[tool.poetry.extras]
test = ["pytest"]
cov = ["coverage"]
doc = ["sphinx", "toml"]

[tool.poetry.dev-dependencies]
flake8 = "^3.5"
flake8-bugbear = { version = "^18.8", python = "^3.5" }
flake8-comprehensions = "^1.4"
flake8-quotes = "^1.0"

[tool.poetry.scripts]
berny = "berny.cli:main"
