
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d48994b2bb99dbd0cfe245c8cb57247e84b0c56c",
 "version": "0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
