
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-13T17:41:53-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd4ab8503c41e9753465e77dfd77c91597c85fee",
 "version": "0.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
