
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-12T20:43:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "76dea7306ebe294ec6f0ea4b60ccb29732709564",
 "version": "1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
