BUFFER_SIZE = 2048

BEGIN_MSG = 'BEGIN:MSG:'
END_MSG = ':END:MSG'
BEGIN_FILE = 'BEGIN:FILE:'
END_FILE = ':END:FILE'

TYPE_MSG = 'MSG'
TYPE_FILE = 'FILE'

ERROR = 'ERROR'
INTERRUPT = 'INTERRUPT'

NAME_CHANGE = 'NAMECHANGE:'
INIT_CLIENT = 'INITCLIENT:'

DEFAULT_DIR = 'tmp/'
DEFAULT_CLIENT_NAME = 'Pymmel'