KEYS = {"on_off": "Power",
        "2": "2",
        "1": "1",
        "3": "3",
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "delete": "Delete / Subtitle",
        "0": "0",
        "text": "Text",
        "prev": "Previous",
        "play_pause": "Play / Pause",
        "next": "Next",
        "guide": "Guide",
        "rec": "Record",
        "back": "Back",
        "menu": "Menu",
        "info": "Info",
        "green": "Green",
        "yellow": "Yellow",
        "blue": "Blue",
        "red": "Red",
        "ok": "OK",
        "vol_up": "Vol+",
        "vol_down": "Vol-",
        "left": "Left",
        "down": "Down",
        "up": "Up",
        "right": "Right",
        "channel_down": "Channel -",
        "channel_up": "Channel +",
        "mute": "Mute"
        }
