language: python
sudo: false # Use container-based infrastructure

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: pypy3
    - python: 2.7
    - python: pypy

install:
 - pip install coverage tox-travis

script: tox

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
