# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/projects/python/pylatus/Pylatus/gui/ui/ui_scan_groupbox.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_groupBoxScan(object):
    def setupUi(self, groupBoxScan):
        groupBoxScan.setObjectName("groupBoxScan")
        groupBoxScan.resize(531, 652)
        groupBoxScan.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(groupBoxScan)
        self.gridLayout.setObjectName("gridLayout")
        self.spinTo = QtWidgets.QDoubleSpinBox(groupBoxScan)
        self.spinTo.setDecimals(5)
        self.spinTo.setMinimum(-100000.0)
        self.spinTo.setMaximum(100000.0)
        self.spinTo.setObjectName("spinTo")
        self.gridLayout.addWidget(self.spinTo, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(groupBoxScan)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(groupBoxScan)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(groupBoxScan)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 4, 0, 1, 1)
        self.comboMotor = QtWidgets.QComboBox(groupBoxScan)
        self.comboMotor.setEditable(True)
        self.comboMotor.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboMotor.setObjectName("comboMotor")
        self.comboMotor.addItem("")
        self.gridLayout.addWidget(self.comboMotor, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(groupBoxScan)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 3, 0, 1, 1)
        self.spinExposure = QtWidgets.QDoubleSpinBox(groupBoxScan)
        self.spinExposure.setDecimals(5)
        self.spinExposure.setMinimum(-100000.0)
        self.spinExposure.setMaximum(100000.0)
        self.spinExposure.setObjectName("spinExposure")
        self.gridLayout.addWidget(self.spinExposure, 4, 1, 1, 1)
        self.labelYPos = QtWidgets.QLabel(groupBoxScan)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.labelYPos.setFont(font)
        self.labelYPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelYPos.setObjectName("labelYPos")
        self.gridLayout.addWidget(self.labelYPos, 8, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(groupBoxScan)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 0, 1, 1)
        self.spinFilter = QtWidgets.QDoubleSpinBox(groupBoxScan)
        self.spinFilter.setDecimals(5)
        self.spinFilter.setObjectName("spinFilter")
        self.gridLayout.addWidget(self.spinFilter, 5, 1, 1, 1)
        self.labelCurrentMotor = QtWidgets.QLabel(groupBoxScan)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.labelCurrentMotor.setFont(font)
        self.labelCurrentMotor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCurrentMotor.setObjectName("labelCurrentMotor")
        self.gridLayout.addWidget(self.labelCurrentMotor, 6, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(groupBoxScan)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)
        self.spinFrom = QtWidgets.QDoubleSpinBox(groupBoxScan)
        self.spinFrom.setDecimals(5)
        self.spinFrom.setMinimum(-100000.0)
        self.spinFrom.setMaximum(100000.0)
        self.spinFrom.setObjectName("spinFrom")
        self.gridLayout.addWidget(self.spinFrom, 1, 1, 1, 1)
        self.currentPositionLabel_6 = QtWidgets.QLabel(groupBoxScan)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.currentPositionLabel_6.setFont(font)
        self.currentPositionLabel_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currentPositionLabel_6.setObjectName("currentPositionLabel_6")
        self.gridLayout.addWidget(self.currentPositionLabel_6, 7, 0, 1, 1)
        self.labelCurrentPosition = QtWidgets.QLabel(groupBoxScan)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.labelCurrentPosition.setFont(font)
        self.labelCurrentPosition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCurrentPosition.setObjectName("labelCurrentPosition")
        self.gridLayout.addWidget(self.labelCurrentPosition, 6, 1, 1, 1)
        self.labelXPos = QtWidgets.QLabel(groupBoxScan)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.labelXPos.setFont(font)
        self.labelXPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelXPos.setObjectName("labelXPos")
        self.gridLayout.addWidget(self.labelXPos, 7, 1, 1, 1)
        self.currentPositionLabel_5 = QtWidgets.QLabel(groupBoxScan)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        font.setItalic(False)
        self.currentPositionLabel_5.setFont(font)
        self.currentPositionLabel_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currentPositionLabel_5.setObjectName("currentPositionLabel_5")
        self.gridLayout.addWidget(self.currentPositionLabel_5, 8, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonRoot = QtWidgets.QPushButton(groupBoxScan)
        self.buttonRoot.setObjectName("buttonRoot")
        self.horizontalLayout_3.addWidget(self.buttonRoot)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonShot = QtWidgets.QPushButton(groupBoxScan)
        self.buttonShot.setObjectName("buttonShot")
        self.horizontalLayout_3.addWidget(self.buttonShot)
        self.buttonStart = QtWidgets.QPushButton(groupBoxScan)
        self.buttonStart.setObjectName("buttonStart")
        self.horizontalLayout_3.addWidget(self.buttonStart)
        self.buttonStop = QtWidgets.QPushButton(groupBoxScan)
        self.buttonStop.setObjectName("buttonStop")
        self.horizontalLayout_3.addWidget(self.buttonStop)
        self.gridLayout.addLayout(self.horizontalLayout_3, 10, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 1)
        self.spinPoints = QtWidgets.QSpinBox(groupBoxScan)
        self.spinPoints.setObjectName("spinPoints")
        self.gridLayout.addWidget(self.spinPoints, 3, 1, 1, 1)
        self.label_20.setBuddy(self.comboMotor)
        self.label_17.setBuddy(self.spinFrom)
        self.label_22.setBuddy(self.spinExposure)
        self.label_19.setBuddy(self.spinPoints)
        self.label_18.setBuddy(self.spinFilter)
        self.labelCurrentMotor.setBuddy(self.labelCurrentPosition)
        self.currentPositionLabel_6.setBuddy(self.labelXPos)
        self.currentPositionLabel_5.setBuddy(self.labelYPos)

        self.retranslateUi(groupBoxScan)
        self.comboMotor.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(groupBoxScan)
        groupBoxScan.setTabOrder(self.comboMotor, self.spinFrom)
        groupBoxScan.setTabOrder(self.spinFrom, self.spinTo)
        groupBoxScan.setTabOrder(self.spinTo, self.spinPoints)
        groupBoxScan.setTabOrder(self.spinPoints, self.spinExposure)
        groupBoxScan.setTabOrder(self.spinExposure, self.spinFilter)
        groupBoxScan.setTabOrder(self.spinFilter, self.buttonStart)
        groupBoxScan.setTabOrder(self.buttonStart, self.buttonStop)
        groupBoxScan.setTabOrder(self.buttonStop, self.buttonShot)
        groupBoxScan.setTabOrder(self.buttonShot, self.buttonRoot)

    def retranslateUi(self, groupBoxScan):
        _translate = QtCore.QCoreApplication.translate
        groupBoxScan.setWindowTitle(_translate("groupBoxScan", "GroupBox"))
        groupBoxScan.setTitle(_translate("groupBoxScan", "Scan control"))
        self.label_20.setText(_translate("groupBoxScan", "Mo&tor"))
        self.label_17.setText(_translate("groupBoxScan", "From"))
        self.label_22.setText(_translate("groupBoxScan", "Expos&ure"))
        self.comboMotor.setItemText(0, _translate("groupBoxScan", "pldistd"))
        self.label_19.setText(_translate("groupBoxScan", "Points"))
        self.labelYPos.setText(_translate("groupBoxScan", "000000"))
        self.label_18.setText(_translate("groupBoxScan", "Fi&lter"))
        self.labelCurrentMotor.setText(_translate("groupBoxScan", "A:"))
        self.label_21.setText(_translate("groupBoxScan", "To"))
        self.currentPositionLabel_6.setText(_translate("groupBoxScan", "&X:"))
        self.labelCurrentPosition.setText(_translate("groupBoxScan", "000000"))
        self.labelXPos.setText(_translate("groupBoxScan", "000000"))
        self.currentPositionLabel_5.setText(_translate("groupBoxScan", "&Y:"))
        self.buttonRoot.setText(_translate("groupBoxScan", "Root"))
        self.buttonShot.setText(_translate("groupBoxScan", "Shot"))
        self.buttonStart.setText(_translate("groupBoxScan", "Start"))
        self.buttonStop.setText(_translate("groupBoxScan", "Stop"))

from . import resources_rc
