# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/projects/python/pylatus/Pylatus/gui/ui/ui_wstatus.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WStatus(object):
    def setupUi(self, WStatus):
        WStatus.setObjectName("WStatus")
        WStatus.resize(640, 669)
        WStatus.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(WStatus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(WStatus)
        self.groupBox_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.pilj2SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pilj2SpinBox.setDecimals(4)
        self.pilj2SpinBox.setMinimum(-10000.0)
        self.pilj2SpinBox.setMaximum(10000.0)
        self.pilj2SpinBox.setObjectName("pilj2SpinBox")
        self.verticalLayout_9.addWidget(self.pilj2SpinBox)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.pilx2SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pilx2SpinBox.setDecimals(4)
        self.pilx2SpinBox.setMinimum(-10000.0)
        self.pilx2SpinBox.setMaximum(10000.0)
        self.pilx2SpinBox.setObjectName("pilx2SpinBox")
        self.verticalLayout_12.addWidget(self.pilx2SpinBox)
        self.gridLayout_3.addLayout(self.verticalLayout_12, 1, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.pilj3SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pilj3SpinBox.setDecimals(4)
        self.pilj3SpinBox.setMinimum(-10000.0)
        self.pilj3SpinBox.setMaximum(10000.0)
        self.pilj3SpinBox.setObjectName("pilj3SpinBox")
        self.verticalLayout_10.addWidget(self.pilj3SpinBox)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 2, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.pilj1SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pilj1SpinBox.setDecimals(4)
        self.pilj1SpinBox.setMinimum(-10000.0)
        self.pilj1SpinBox.setMaximum(10000.0)
        self.pilj1SpinBox.setObjectName("pilj1SpinBox")
        self.verticalLayout_8.addWidget(self.pilj1SpinBox)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.pilx1SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pilx1SpinBox.setDecimals(4)
        self.pilx1SpinBox.setMinimum(-10000.0)
        self.pilx1SpinBox.setMaximum(10000.0)
        self.pilx1SpinBox.setObjectName("pilx1SpinBox")
        self.verticalLayout_11.addWidget(self.pilx1SpinBox)
        self.gridLayout_3.addLayout(self.verticalLayout_11, 0, 1, 1, 1)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_22.addWidget(self.label_22)
        self.bstopSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.bstopSpinBox.setDecimals(4)
        self.bstopSpinBox.setMinimum(-10000.0)
        self.bstopSpinBox.setMaximum(10000.0)
        self.bstopSpinBox.setObjectName("bstopSpinBox")
        self.verticalLayout_22.addWidget(self.bstopSpinBox)
        self.gridLayout_3.addLayout(self.verticalLayout_22, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(WStatus)
        self.groupBox_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.pilsl1bSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.pilsl1bSpinBox.setDecimals(4)
        self.pilsl1bSpinBox.setMinimum(-10000.0)
        self.pilsl1bSpinBox.setMaximum(10000.0)
        self.pilsl1bSpinBox.setObjectName("pilsl1bSpinBox")
        self.verticalLayout_14.addWidget(self.pilsl1bSpinBox)
        self.gridLayout_4.addLayout(self.verticalLayout_14, 4, 2, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_4)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 2, 3, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_15.addWidget(self.label_15)
        self.pilsl1lSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.pilsl1lSpinBox.setDecimals(4)
        self.pilsl1lSpinBox.setMinimum(-10000.0)
        self.pilsl1lSpinBox.setMaximum(10000.0)
        self.pilsl1lSpinBox.setObjectName("pilsl1lSpinBox")
        self.verticalLayout_15.addWidget(self.pilsl1lSpinBox)
        self.gridLayout_4.addLayout(self.verticalLayout_15, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 2, 1, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_16.addWidget(self.label_16)
        self.pilsl1rSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.pilsl1rSpinBox.setDecimals(4)
        self.pilsl1rSpinBox.setMinimum(-10000.0)
        self.pilsl1rSpinBox.setMaximum(10000.0)
        self.pilsl1rSpinBox.setObjectName("pilsl1rSpinBox")
        self.verticalLayout_16.addWidget(self.pilsl1rSpinBox)
        self.gridLayout_4.addLayout(self.verticalLayout_16, 2, 4, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.pilsl1tSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.pilsl1tSpinBox.setDecimals(4)
        self.pilsl1tSpinBox.setMinimum(-10000.0)
        self.pilsl1tSpinBox.setMaximum(10000.0)
        self.pilsl1tSpinBox.setObjectName("pilsl1tSpinBox")
        self.verticalLayout_13.addWidget(self.pilsl1tSpinBox)
        self.gridLayout_4.addLayout(self.verticalLayout_13, 0, 1, 1, 3)
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 4, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.buttonClose = QtWidgets.QPushButton(WStatus)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout_5.addWidget(self.buttonClose)
        self.buttonOpen = QtWidgets.QPushButton(WStatus)
        self.buttonOpen.setObjectName("buttonOpen")
        self.horizontalLayout_5.addWidget(self.buttonOpen)
        self.updateButton = QtWidgets.QPushButton(WStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateButton.sizePolicy().hasHeightForWidth())
        self.updateButton.setSizePolicy(sizePolicy)
        self.updateButton.setMinimumSize(QtCore.QSize(100, 0))
        self.updateButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_5.addWidget(self.updateButton)
        self.sendButton = QtWidgets.QPushButton(WStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        self.sendButton.setMinimumSize(QtCore.QSize(100, 0))
        self.sendButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_5.addWidget(self.sendButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(WStatus)
        QtCore.QMetaObject.connectSlotsByName(WStatus)

    def retranslateUi(self, WStatus):
        _translate = QtCore.QCoreApplication.translate
        WStatus.setWindowTitle(_translate("WStatus", "Pylatus status"))
        self.groupBox_3.setTitle(_translate("WStatus", "Marble table"))
        self.label_9.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 2)</p></body></html>"))
        self.label_9.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 2)</p></body></html>"))
        self.label_9.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 2)</p></body></html>"))
        self.label_9.setText(_translate("WStatus", "pilj2 (mm)"))
        self.pilj2SpinBox.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 2)</p></body></html>"))
        self.pilj2SpinBox.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 2)</p></body></html>"))
        self.pilj2SpinBox.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 2)</p></body></html>"))
        self.label_12.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.label_12.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.label_12.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.label_12.setText(_translate("WStatus", "pilx2 (mm)"))
        self.pilx2SpinBox.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.pilx2SpinBox.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.pilx2SpinBox.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.label_10.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 3)</p></body></html>"))
        self.label_10.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 3)</p></body></html>"))
        self.label_10.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 3)</p></body></html>"))
        self.label_10.setText(_translate("WStatus", "pilj3 (mm)"))
        self.pilj3SpinBox.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 3)</p></body></html>"))
        self.pilj3SpinBox.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 3)</p></body></html>"))
        self.pilj3SpinBox.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 3)</p></body></html>"))
        self.label_8.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 1)</p></body></html>"))
        self.label_8.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 1)</p></body></html>"))
        self.label_8.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 1)</p></body></html>"))
        self.label_8.setText(_translate("WStatus", "pilj1 (mm)"))
        self.pilj1SpinBox.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 1)</p></body></html>"))
        self.pilj1SpinBox.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 1)</p></body></html>"))
        self.pilj1SpinBox.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table vertical movement (jack 1)</p></body></html>"))
        self.label_11.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 1)</p></body></html>"))
        self.label_11.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 1)</p></body></html>"))
        self.label_11.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 1)</p></body></html>"))
        self.label_11.setText(_translate("WStatus", "pilx1 (mm)"))
        self.pilx1SpinBox.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 1)</p></body></html>"))
        self.pilx1SpinBox.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 1)</p></body></html>"))
        self.pilx1SpinBox.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 1)</p></body></html>"))
        self.label_22.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.label_22.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.label_22.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.label_22.setText(_translate("WStatus", "bstop (mm)"))
        self.bstopSpinBox.setToolTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.bstopSpinBox.setStatusTip(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.bstopSpinBox.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Marble table horizontal movement (jack 2)</p></body></html>"))
        self.groupBox_4.setTitle(_translate("WStatus", "Slits"))
        self.label_14.setToolTip(_translate("WStatus", "<html><head/><body><p>Bottom detector slit</p></body></html>"))
        self.label_14.setStatusTip(_translate("WStatus", "<html><head/><body><p>Bottom detector slit</p></body></html>"))
        self.label_14.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Bottom detector slit</p></body></html>"))
        self.label_14.setText(_translate("WStatus", "pilsl1b (mm)"))
        self.pilsl1bSpinBox.setToolTip(_translate("WStatus", "<html><head/><body><p>Bottom detector slit</p></body></html>"))
        self.pilsl1bSpinBox.setStatusTip(_translate("WStatus", "<html><head/><body><p>Bottom detector slit</p></body></html>"))
        self.pilsl1bSpinBox.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Bottom detector slit</p></body></html>"))
        self.label_15.setToolTip(_translate("WStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_15.setStatusTip(_translate("WStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_15.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_15.setText(_translate("WStatus", "pilsl1l (mm)"))
        self.pilsl1lSpinBox.setToolTip(_translate("WStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.pilsl1lSpinBox.setStatusTip(_translate("WStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.pilsl1lSpinBox.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_16.setToolTip(_translate("WStatus", "<html><head/><body><p>Right detector slit</p></body></html>"))
        self.label_16.setStatusTip(_translate("WStatus", "<html><head/><body><p>Right detector slit</p></body></html>"))
        self.label_16.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Right detector slit</p></body></html>"))
        self.label_16.setText(_translate("WStatus", "pilsl1r (mm)"))
        self.pilsl1rSpinBox.setToolTip(_translate("WStatus", "<html><head/><body><p>Right detector slit</p></body></html>"))
        self.pilsl1rSpinBox.setStatusTip(_translate("WStatus", "<html><head/><body><p>Right detector slit</p></body></html>"))
        self.pilsl1rSpinBox.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Right detector slit</p></body></html>"))
        self.label_13.setToolTip(_translate("WStatus", "<html><head/><body><p>Top detector slit</p></body></html>"))
        self.label_13.setStatusTip(_translate("WStatus", "<html><head/><body><p>Top detector slit</p></body></html>"))
        self.label_13.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Top detector slit</p></body></html>"))
        self.label_13.setText(_translate("WStatus", "pilsl1t (mm)"))
        self.pilsl1tSpinBox.setToolTip(_translate("WStatus", "<html><head/><body><p>Top detector slit</p></body></html>"))
        self.pilsl1tSpinBox.setStatusTip(_translate("WStatus", "<html><head/><body><p>Top detector slit</p></body></html>"))
        self.pilsl1tSpinBox.setWhatsThis(_translate("WStatus", "<html><head/><body><p>Top detector slit</p></body></html>"))
        self.buttonClose.setText(_translate("WStatus", "Close shutter"))
        self.buttonOpen.setText(_translate("WStatus", "Open shutter"))
        self.updateButton.setText(_translate("WStatus", "Update (F5)"))
        self.sendButton.setText(_translate("WStatus", "Send"))

