# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/projects/python/pylatus/Pylatus/gui/ui/ui_wuserstatus.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WUserStatus(object):
    def setupUi(self, WUserStatus):
        WUserStatus.setObjectName("WUserStatus")
        WUserStatus.resize(734, 1005)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WUserStatus.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(WUserStatus)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(WUserStatus)
        self.groupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.omegaSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.omegaSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.omegaSpinBox.setDecimals(4)
        self.omegaSpinBox.setMinimum(-10000.0)
        self.omegaSpinBox.setMaximum(10000.0)
        self.omegaSpinBox.setObjectName("omegaSpinBox")
        self.horizontalLayout_20.addWidget(self.omegaSpinBox)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_20.addWidget(self.label_21)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.phiSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.phiSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.phiSpinBox.setDecimals(4)
        self.phiSpinBox.setMinimum(-10000.0)
        self.phiSpinBox.setMaximum(10000.0)
        self.phiSpinBox.setObjectName("phiSpinBox")
        self.horizontalLayout_19.addWidget(self.phiSpinBox)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_19.addWidget(self.label_20)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.kappaSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.kappaSpinBox.setStatusTip("")
        self.kappaSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.kappaSpinBox.setDecimals(4)
        self.kappaSpinBox.setMinimum(-10000.0)
        self.kappaSpinBox.setMaximum(10000.0)
        self.kappaSpinBox.setObjectName("kappaSpinBox")
        self.horizontalLayout_14.addWidget(self.kappaSpinBox)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prphiSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.prphiSpinBox.setEnabled(False)
        self.prphiSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.prphiSpinBox.setDecimals(4)
        self.prphiSpinBox.setMinimum(-10000.0)
        self.prphiSpinBox.setMaximum(10000.0)
        self.prphiSpinBox.setObjectName("prphiSpinBox")
        self.horizontalLayout.addWidget(self.prphiSpinBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prhorSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.prhorSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.prhorSpinBox.setDecimals(4)
        self.prhorSpinBox.setMinimum(-10000.0)
        self.prhorSpinBox.setMaximum(10000.0)
        self.prhorSpinBox.setObjectName("prhorSpinBox")
        self.horizontalLayout_3.addWidget(self.prhorSpinBox)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prverSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.prverSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.prverSpinBox.setDecimals(4)
        self.prverSpinBox.setMinimum(-10000.0)
        self.prverSpinBox.setMaximum(10000.0)
        self.prverSpinBox.setObjectName("prverSpinBox")
        self.horizontalLayout_2.addWidget(self.prverSpinBox)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(WUserStatus)
        self.groupBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pldistdSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.pldistdSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pldistdSpinBox.setDecimals(4)
        self.pldistdSpinBox.setMinimum(-10000.0)
        self.pldistdSpinBox.setMaximum(10000.0)
        self.pldistdSpinBox.setObjectName("pldistdSpinBox")
        self.horizontalLayout_4.addWidget(self.pldistdSpinBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pldistfSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.pldistfSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pldistfSpinBox.setDecimals(4)
        self.pldistfSpinBox.setMinimum(-10000.0)
        self.pldistfSpinBox.setMaximum(10000.0)
        self.pldistfSpinBox.setObjectName("pldistfSpinBox")
        self.horizontalLayout_5.addWidget(self.pldistfSpinBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem7 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.plvertSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.plvertSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.plvertSpinBox.setDecimals(4)
        self.plvertSpinBox.setMinimum(-10000.0)
        self.plvertSpinBox.setMaximum(10000.0)
        self.plvertSpinBox.setObjectName("plvertSpinBox")
        self.horizontalLayout_6.addWidget(self.plvertSpinBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem8 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.plrotSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plrotSpinBox.sizePolicy().hasHeightForWidth())
        self.plrotSpinBox.setSizePolicy(sizePolicy)
        self.plrotSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.plrotSpinBox.setDecimals(4)
        self.plrotSpinBox.setMinimum(-10000.0)
        self.plrotSpinBox.setMaximum(10000.0)
        self.plrotSpinBox.setObjectName("plrotSpinBox")
        self.horizontalLayout_7.addWidget(self.plrotSpinBox)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        spacerItem9 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.filterSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterSpinBox.sizePolicy().hasHeightForWidth())
        self.filterSpinBox.setSizePolicy(sizePolicy)
        self.filterSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.filterSpinBox.setDecimals(4)
        self.filterSpinBox.setMinimum(-10000.0)
        self.filterSpinBox.setMaximum(10000.0)
        self.filterSpinBox.setObjectName("filterSpinBox")
        self.horizontalLayout_10.addWidget(self.filterSpinBox)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        spacerItem10 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(WUserStatus)
        self.groupBox_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_21.addWidget(self.label_23)
        self.energyLabel = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        self.energyLabel.setFont(font)
        self.energyLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.energyLabel.setTextFormat(QtCore.Qt.AutoText)
        self.energyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.energyLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.energyLabel.setObjectName("energyLabel")
        self.verticalLayout_21.addWidget(self.energyLabel)
        self.horizontalLayout_8.addLayout(self.verticalLayout_21)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_17.addWidget(self.label_17)
        self.waveLengthLabel = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        self.waveLengthLabel.setFont(font)
        self.waveLengthLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.waveLengthLabel.setTextFormat(QtCore.Qt.AutoText)
        self.waveLengthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.waveLengthLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.waveLengthLabel.setObjectName("waveLengthLabel")
        self.verticalLayout_17.addWidget(self.waveLengthLabel)
        self.horizontalLayout_8.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_18.addWidget(self.label_18)
        self.monitorLabel = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        self.monitorLabel.setFont(font)
        self.monitorLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.monitorLabel.setTextFormat(QtCore.Qt.AutoText)
        self.monitorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.monitorLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.monitorLabel.setObjectName("monitorLabel")
        self.verticalLayout_18.addWidget(self.monitorLabel)
        self.horizontalLayout_8.addLayout(self.verticalLayout_18)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.stopButton = QtWidgets.QPushButton(WUserStatus)
        self.stopButton.setIconSize(QtCore.QSize(16, 16))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_9.addWidget(self.stopButton)
        self.relativeButton = QtWidgets.QPushButton(WUserStatus)
        self.relativeButton.setObjectName("relativeButton")
        self.horizontalLayout_9.addWidget(self.relativeButton)
        self.updateButton = QtWidgets.QPushButton(WUserStatus)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_9.addWidget(self.updateButton)
        self.sendButton = QtWidgets.QPushButton(WUserStatus)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_9.addWidget(self.sendButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)

        self.retranslateUi(WUserStatus)
        QtCore.QMetaObject.connectSlotsByName(WUserStatus)

    def retranslateUi(self, WUserStatus):
        _translate = QtCore.QCoreApplication.translate
        WUserStatus.setWindowTitle(_translate("WUserStatus", "Pylatus user status"))
        self.groupBox.setTitle(_translate("WUserStatus", "Sample"))
        self.omegaSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>&omega; rotation of the sample (deg)</p></body></html>"))
        self.omegaSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>&omega; rotation of the sample (deg)</p></body></html>"))
        self.label_21.setToolTip(_translate("WUserStatus", "<html><head/><body><p>&omega; rotation of the sample (deg)</p></body></html>"))
        self.label_21.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>&omega; rotation of the sample (deg)</p></body></html>"))
        self.label_21.setText(_translate("WUserStatus", "<html><head/><body><p>&omega; rotation of the sample (deg)</p></body></html>"))
        self.phiSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Phi rotation of the sample</p></body></html>"))
        self.phiSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Phi rotation of the sample</p></body></html>"))
        self.label_20.setToolTip(_translate("WUserStatus", "<html><head/><body><p>&phi; rotation of the sample (deg)</p></body></html>"))
        self.label_20.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>&phi; rotation of the sample (deg)</p></body></html>"))
        self.label_20.setText(_translate("WUserStatus", "<html><head/><body><p>&phi; rotation of the sample (deg)</p></body></html>"))
        self.kappaSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>&kappa; rotation of the sample (deg)</p></body></html>"))
        self.kappaSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>&kappa; rotation of the sample (deg)</p></body></html>"))
        self.label_13.setToolTip(_translate("WUserStatus", "<html><head/><body><p>&kappa; rotation of the sample (deg)</p></body></html>"))
        self.label_13.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>&kappa; rotation of the sample (deg)</p></body></html>"))
        self.label_13.setText(_translate("WUserStatus", "<html><head/><body><p>&kappa; rotation of the sample (deg)</p></body></html>"))
        self.prphiSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>&phi;\' (rotary table) rotation of the sample (deg)</p></body></html>"))
        self.prphiSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>&phi;\' (rotary table) rotation of the sample (deg)</p></body></html>"))
        self.label_5.setToolTip(_translate("WUserStatus", "<html><head/><body><p>&phi;\' (rotary table) rotation of the sample (deg)</p></body></html>"))
        self.label_5.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>&phi;\' (rotary table) rotation of the sample (deg)</p></body></html>"))
        self.label_5.setText(_translate("WUserStatus", "<html><head/><body><p>&omega;\' rotation of the sample (deg)</p></body></html>"))
        self.prhorSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the sample (mm)</p></body></html>"))
        self.prhorSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the sample (mm)</p></body></html>"))
        self.label_7.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the sample (mm)</p></body></html>"))
        self.label_7.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the sample (mm)</p></body></html>"))
        self.label_7.setText(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the sample (mm)</p></body></html>"))
        self.prverSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Vertical position of the sample (mm)</p></body></html>"))
        self.prverSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Vertical phi movement</p></body></html>"))
        self.label_6.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Vertical position of the sample (mm)</p></body></html>"))
        self.label_6.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Vertical position of the sample (mm)</p></body></html>"))
        self.label_6.setText(_translate("WUserStatus", "<html><head/><body><p>Vertical position of the sample (mm)</p></body></html>"))
        self.groupBox_2.setTitle(_translate("WUserStatus", "Detector"))
        self.pldistdSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the detector</p></body></html>"))
        self.pldistdSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the detector</p></body></html>"))
        self.label_3.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the detector</p></body></html>"))
        self.label_3.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the detector</p></body></html>"))
        self.label_3.setText(_translate("WUserStatus", "<html><head/><body><p>Detector horizontal position (mm)</p></body></html>"))
        self.pldistfSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the frame (mm)</p></body></html>"))
        self.pldistfSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the frame (mm)</p></body></html>"))
        self.label_2.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the frame (mm)</p></body></html>"))
        self.label_2.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Horizontal position of the frame (mm)</p></body></html>"))
        self.label_2.setText(_translate("WUserStatus", "<html><head/><body><p>Frame horizontal position (mm)</p></body></html>"))
        self.plvertSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Vertical position of the detector</p></body></html>"))
        self.plvertSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Vertical position of the detector</p></body></html>"))
        self.label_4.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Vertical position of the detector</p></body></html>"))
        self.label_4.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Vertical position of the detector</p></body></html>"))
        self.label_4.setText(_translate("WUserStatus", "<html><head/><body><p>Detector vertical position (mm)</p></body></html>"))
        self.plrotSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Tilt of the detector</p></body></html>"))
        self.plrotSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Tilt of the detector</p></body></html>"))
        self.label_8.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Tilt of the detector</p></body></html>"))
        self.label_8.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Tilt of the detector</p></body></html>"))
        self.label_8.setText(_translate("WUserStatus", "<html><head/><body><p>Tilt of the detector (deg)</p></body></html>"))
        self.filterSpinBox.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Tilt of the detector</p></body></html>"))
        self.filterSpinBox.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Tilt of the detector</p></body></html>"))
        self.label_9.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Tilt of the detector</p></body></html>"))
        self.label_9.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Tilt of the detector</p></body></html>"))
        self.label_9.setText(_translate("WUserStatus", "Filter"))
        self.groupBox_3.setTitle(_translate("WUserStatus", "Beam"))
        self.label_23.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_23.setStatusTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_23.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_23.setText(_translate("WUserStatus", "Energy (keV)"))
        self.energyLabel.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.energyLabel.setStatusTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.energyLabel.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.energyLabel.setText(_translate("WUserStatus", "1.00000"))
        self.label_17.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_17.setStatusTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_17.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_17.setText(_translate("WUserStatus", "<html><head/><body><p>Wavelength (&#8491;)</p></body></html>"))
        self.waveLengthLabel.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.waveLengthLabel.setStatusTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.waveLengthLabel.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.waveLengthLabel.setText(_translate("WUserStatus", "1.00000"))
        self.label_18.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_18.setStatusTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_18.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.label_18.setText(_translate("WUserStatus", "Monitor"))
        self.monitorLabel.setToolTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.monitorLabel.setStatusTip(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.monitorLabel.setWhatsThis(_translate("WUserStatus", "<html><head/><body><p>Left detector slit</p></body></html>"))
        self.monitorLabel.setText(_translate("WUserStatus", "0"))
        self.stopButton.setText(_translate("WUserStatus", "Stop!"))
        self.relativeButton.setText(_translate("WUserStatus", "Relative"))
        self.updateButton.setText(_translate("WUserStatus", "Update"))
        self.sendButton.setText(_translate("WUserStatus", "Send"))

from . import resources_rc
