# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/projects/python/pylatus/Pylatus/gui/ui/ui_walign.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WBeamAlign(object):
    def setupUi(self, WBeamAlign):
        WBeamAlign.setObjectName("WBeamAlign")
        WBeamAlign.resize(584, 379)
        WBeamAlign.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(WBeamAlign)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(WBeamAlign)
        self.groupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 4, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 3, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.sl01tSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl01tSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl01tSpinBox.setDecimals(5)
        self.sl01tSpinBox.setMinimum(-10000.0)
        self.sl01tSpinBox.setMaximum(10000.0)
        self.sl01tSpinBox.setObjectName("sl01tSpinBox")
        self.gridLayout_2.addWidget(self.sl01tSpinBox, 1, 1, 1, 1)
        self.sl02tSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl02tSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl02tSpinBox.setDecimals(5)
        self.sl02tSpinBox.setMinimum(-10000.0)
        self.sl02tSpinBox.setMaximum(10000.0)
        self.sl02tSpinBox.setObjectName("sl02tSpinBox")
        self.gridLayout_2.addWidget(self.sl02tSpinBox, 2, 1, 1, 1)
        self.sl03tSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl03tSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl03tSpinBox.setDecimals(5)
        self.sl03tSpinBox.setMinimum(-10000.0)
        self.sl03tSpinBox.setMaximum(10000.0)
        self.sl03tSpinBox.setObjectName("sl03tSpinBox")
        self.gridLayout_2.addWidget(self.sl03tSpinBox, 3, 1, 1, 1)
        self.sl01bSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl01bSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl01bSpinBox.setDecimals(5)
        self.sl01bSpinBox.setMinimum(-10000.0)
        self.sl01bSpinBox.setMaximum(10000.0)
        self.sl01bSpinBox.setObjectName("sl01bSpinBox")
        self.gridLayout_2.addWidget(self.sl01bSpinBox, 1, 2, 1, 1)
        self.sl02bSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl02bSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl02bSpinBox.setDecimals(5)
        self.sl02bSpinBox.setMinimum(-10000.0)
        self.sl02bSpinBox.setMaximum(10000.0)
        self.sl02bSpinBox.setObjectName("sl02bSpinBox")
        self.gridLayout_2.addWidget(self.sl02bSpinBox, 2, 2, 1, 1)
        self.sl03bSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl03bSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl03bSpinBox.setDecimals(5)
        self.sl03bSpinBox.setMinimum(-10000.0)
        self.sl03bSpinBox.setMaximum(10000.0)
        self.sl03bSpinBox.setObjectName("sl03bSpinBox")
        self.gridLayout_2.addWidget(self.sl03bSpinBox, 3, 2, 1, 1)
        self.sl01lSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl01lSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl01lSpinBox.setDecimals(5)
        self.sl01lSpinBox.setMinimum(-10000.0)
        self.sl01lSpinBox.setMaximum(10000.0)
        self.sl01lSpinBox.setObjectName("sl01lSpinBox")
        self.gridLayout_2.addWidget(self.sl01lSpinBox, 1, 3, 1, 1)
        self.sl02lSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl02lSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl02lSpinBox.setDecimals(5)
        self.sl02lSpinBox.setMinimum(-10000.0)
        self.sl02lSpinBox.setMaximum(10000.0)
        self.sl02lSpinBox.setObjectName("sl02lSpinBox")
        self.gridLayout_2.addWidget(self.sl02lSpinBox, 2, 3, 1, 1)
        self.sl03lSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl03lSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl03lSpinBox.setDecimals(5)
        self.sl03lSpinBox.setMinimum(-10000.0)
        self.sl03lSpinBox.setMaximum(10000.0)
        self.sl03lSpinBox.setObjectName("sl03lSpinBox")
        self.gridLayout_2.addWidget(self.sl03lSpinBox, 3, 3, 1, 1)
        self.sl01rSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl01rSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl01rSpinBox.setDecimals(5)
        self.sl01rSpinBox.setMinimum(-10000.0)
        self.sl01rSpinBox.setMaximum(10000.0)
        self.sl01rSpinBox.setObjectName("sl01rSpinBox")
        self.gridLayout_2.addWidget(self.sl01rSpinBox, 1, 4, 1, 1)
        self.sl02rSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl02rSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl02rSpinBox.setDecimals(5)
        self.sl02rSpinBox.setMinimum(-10000.0)
        self.sl02rSpinBox.setMaximum(10000.0)
        self.sl02rSpinBox.setObjectName("sl02rSpinBox")
        self.gridLayout_2.addWidget(self.sl02rSpinBox, 2, 4, 1, 1)
        self.sl03rSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sl03rSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sl03rSpinBox.setDecimals(5)
        self.sl03rSpinBox.setMinimum(-10000.0)
        self.sl03rSpinBox.setMaximum(10000.0)
        self.sl03rSpinBox.setObjectName("sl03rSpinBox")
        self.gridLayout_2.addWidget(self.sl03rSpinBox, 3, 4, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(WBeamAlign)
        self.groupBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.mirror1SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.mirror1SpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.mirror1SpinBox.setDecimals(5)
        self.mirror1SpinBox.setMinimum(-10000.0)
        self.mirror1SpinBox.setMaximum(10000.0)
        self.mirror1SpinBox.setObjectName("mirror1SpinBox")
        self.gridLayout_3.addWidget(self.mirror1SpinBox, 0, 1, 1, 1)
        self.mirror2SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.mirror2SpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.mirror2SpinBox.setDecimals(5)
        self.mirror2SpinBox.setMinimum(-10000.0)
        self.mirror2SpinBox.setMaximum(10000.0)
        self.mirror2SpinBox.setObjectName("mirror2SpinBox")
        self.gridLayout_3.addWidget(self.mirror2SpinBox, 1, 1, 1, 1)
        self.mirror3SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.mirror3SpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.mirror3SpinBox.setDecimals(5)
        self.mirror3SpinBox.setMinimum(-10000.0)
        self.mirror3SpinBox.setMaximum(10000.0)
        self.mirror3SpinBox.setObjectName("mirror3SpinBox")
        self.gridLayout_3.addWidget(self.mirror3SpinBox, 2, 1, 1, 1)
        self.mirror4SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.mirror4SpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.mirror4SpinBox.setDecimals(5)
        self.mirror4SpinBox.setMinimum(-10000.0)
        self.mirror4SpinBox.setMaximum(10000.0)
        self.mirror4SpinBox.setObjectName("mirror4SpinBox")
        self.gridLayout_3.addWidget(self.mirror4SpinBox, 3, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 1, 1, 1)
        self.monoSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.monoSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.monoSpinBox.setDecimals(5)
        self.monoSpinBox.setMinimum(-10000.0)
        self.monoSpinBox.setMaximum(10000.0)
        self.monoSpinBox.setObjectName("monoSpinBox")
        self.gridLayout_4.addWidget(self.monoSpinBox, 1, 0, 1, 1)
        self._monoSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self._monoSpinBox.setDecimals(5)
        self._monoSpinBox.setMinimum(0.5)
        self._monoSpinBox.setMaximum(1.5)
        self._monoSpinBox.setSingleStep(0.1)
        self._monoSpinBox.setObjectName("_monoSpinBox")
        self.gridLayout_4.addWidget(self._monoSpinBox, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 1, 1, 1)
        self.benderoSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.benderoSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.benderoSpinBox.setDecimals(5)
        self.benderoSpinBox.setMinimum(-10000.0)
        self.benderoSpinBox.setMaximum(10000.0)
        self.benderoSpinBox.setObjectName("benderoSpinBox")
        self.gridLayout_5.addWidget(self.benderoSpinBox, 1, 0, 1, 1)
        self.bendergSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.bendergSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.bendergSpinBox.setDecimals(5)
        self.bendergSpinBox.setMinimum(-10000.0)
        self.bendergSpinBox.setMaximum(10000.0)
        self.bendergSpinBox.setObjectName("bendergSpinBox")
        self.gridLayout_5.addWidget(self.bendergSpinBox, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.getButton = QtWidgets.QPushButton(WBeamAlign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getButton.sizePolicy().hasHeightForWidth())
        self.getButton.setSizePolicy(sizePolicy)
        self.getButton.setMinimumSize(QtCore.QSize(100, 0))
        self.getButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.getButton.setObjectName("getButton")
        self.horizontalLayout_3.addWidget(self.getButton)
        self.sendButton = QtWidgets.QPushButton(WBeamAlign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        self.sendButton.setMinimumSize(QtCore.QSize(100, 0))
        self.sendButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_3.addWidget(self.sendButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)

        self.retranslateUi(WBeamAlign)
        QtCore.QMetaObject.connectSlotsByName(WBeamAlign)

    def retranslateUi(self, WBeamAlign):
        _translate = QtCore.QCoreApplication.translate
        WBeamAlign.setWindowTitle(_translate("WBeamAlign", "Pylatus beam alignment"))
        self.groupBox.setTitle(_translate("WBeamAlign", "Slits (mm)"))
        self.label_8.setText(_translate("WBeamAlign", "b"))
        self.label_7.setText(_translate("WBeamAlign", "l"))
        self.label_5.setText(_translate("WBeamAlign", "r"))
        self.label.setText(_translate("WBeamAlign", "sl01"))
        self.label_2.setText(_translate("WBeamAlign", "sl02"))
        self.label_3.setText(_translate("WBeamAlign", "sl03"))
        self.label_6.setText(_translate("WBeamAlign", "t"))
        self.groupBox_2.setTitle(_translate("WBeamAlign", "Mirrors && Mono"))
        self.label_4.setText(_translate("WBeamAlign", "mirror1 (mm)"))
        self.label_9.setText(_translate("WBeamAlign", "mirror2 (mm)"))
        self.label_10.setText(_translate("WBeamAlign", "mirror3 (mm)"))
        self.label_11.setText(_translate("WBeamAlign", "mirror4 (mm)"))
        self.label_12.setText(_translate("WBeamAlign", "mono (deg)"))
        self.label_13.setText(_translate("WBeamAlign", "<html><head/><body><p>mono (&#8491;)</p></body></html>"))
        self.label_16.setText(_translate("WBeamAlign", "bendero"))
        self.label_17.setText(_translate("WBeamAlign", "benderg"))
        self.getButton.setText(_translate("WBeamAlign", "Update (F5)"))
        self.sendButton.setText(_translate("WBeamAlign", "Send"))

