# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/projects/python/pylatus/Pylatus/gui/ui/ui_wmain.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WPylatus(object):
    def setupUi(self, WPylatus):
        WPylatus.setObjectName("WPylatus")
        WPylatus.resize(928, 1205)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WPylatus.setWindowIcon(icon)
        WPylatus.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(WPylatus)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.userTab = QtWidgets.QWidget()
        self.userTab.setObjectName("userTab")
        self.verticalLayout_54 = QtWidgets.QVBoxLayout(self.userTab)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.label_15 = QtWidgets.QLabel(self.userTab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_54.addWidget(self.label_15)
        self.line = QtWidgets.QFrame(self.userTab)
        self.line.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_54.addWidget(self.line)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.userTab)
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_14.addWidget(self.label_4)
        self.filenameLineEdit = QtWidgets.QLineEdit(self.userTab)
        self.filenameLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.filenameLineEdit.setMaxLength(48)
        self.filenameLineEdit.setObjectName("filenameLineEdit")
        self.verticalLayout_14.addWidget(self.filenameLineEdit)
        self.horizontalLayout_30.addLayout(self.verticalLayout_14)
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.label_13 = QtWidgets.QLabel(self.userTab)
        self.label_13.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_53.addWidget(self.label_13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.folderLineEdit = QtWidgets.QLineEdit(self.userTab)
        self.folderLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.folderLineEdit.setObjectName("folderLineEdit")
        self.horizontalLayout_7.addWidget(self.folderLineEdit)
        self.selectFolderButton = QtWidgets.QPushButton(self.userTab)
        self.selectFolderButton.setText("")
        self.selectFolderButton.setObjectName("selectFolderButton")
        self.horizontalLayout_7.addWidget(self.selectFolderButton)
        self.verticalLayout_53.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_30.addLayout(self.verticalLayout_53)
        self.verticalLayout_5.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exposureSpinBox = QtWidgets.QDoubleSpinBox(self.userTab)
        self.exposureSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.exposureSpinBox.setDecimals(4)
        self.exposureSpinBox.setMinimum(0.034)
        self.exposureSpinBox.setMaximum(65535.0)
        self.exposureSpinBox.setProperty("value", 1.0)
        self.exposureSpinBox.setObjectName("exposureSpinBox")
        self.horizontalLayout_3.addWidget(self.exposureSpinBox)
        self.label_5 = QtWidgets.QLabel(self.userTab)
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nframesSpinBox = QtWidgets.QSpinBox(self.userTab)
        self.nframesSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.nframesSpinBox.setMinimum(1)
        self.nframesSpinBox.setMaximum(65535)
        self.nframesSpinBox.setObjectName("nframesSpinBox")
        self.horizontalLayout_4.addWidget(self.nframesSpinBox)
        self.label_6 = QtWidgets.QLabel(self.userTab)
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.nperiodsSpinBox = QtWidgets.QSpinBox(self.userTab)
        self.nperiodsSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.nperiodsSpinBox.setMinimum(1)
        self.nperiodsSpinBox.setMaximum(10000)
        self.nperiodsSpinBox.setObjectName("nperiodsSpinBox")
        self.horizontalLayout_8.addWidget(self.nperiodsSpinBox)
        self.label_17 = QtWidgets.QLabel(self.userTab)
        self.label_17.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dOmegaSpinBox = QtWidgets.QDoubleSpinBox(self.userTab)
        self.dOmegaSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dOmegaSpinBox.setDecimals(4)
        self.dOmegaSpinBox.setMaximum(360.0)
        self.dOmegaSpinBox.setObjectName("dOmegaSpinBox")
        self.horizontalLayout_5.addWidget(self.dOmegaSpinBox)
        self.dAngleLabel = QtWidgets.QLabel(self.userTab)
        self.dAngleLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dAngleLabel.setObjectName("dAngleLabel")
        self.horizontalLayout_5.addWidget(self.dAngleLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.omegaSpinBox = QtWidgets.QDoubleSpinBox(self.userTab)
        self.omegaSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.omegaSpinBox.setDecimals(4)
        self.omegaSpinBox.setMinimum(-360.0)
        self.omegaSpinBox.setMaximum(360.0)
        self.omegaSpinBox.setObjectName("omegaSpinBox")
        self.horizontalLayout_6.addWidget(self.omegaSpinBox)
        self.startingAngleLabel = QtWidgets.QLabel(self.userTab)
        self.startingAngleLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.startingAngleLabel.setObjectName("startingAngleLabel")
        self.horizontalLayout_6.addWidget(self.startingAngleLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.phiLayout = QtWidgets.QHBoxLayout()
        self.phiLayout.setObjectName("phiLayout")
        self.phiSpinBox = QtWidgets.QDoubleSpinBox(self.userTab)
        self.phiSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.phiSpinBox.setDecimals(4)
        self.phiSpinBox.setMinimum(-360.0)
        self.phiSpinBox.setMaximum(360.0)
        self.phiSpinBox.setObjectName("phiSpinBox")
        self.phiLayout.addWidget(self.phiSpinBox)
        self.phiLabel = QtWidgets.QLabel(self.userTab)
        self.phiLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.phiLabel.setObjectName("phiLabel")
        self.phiLayout.addWidget(self.phiLabel)
        self.verticalLayout_5.addLayout(self.phiLayout)
        self.kappaLayout = QtWidgets.QHBoxLayout()
        self.kappaLayout.setObjectName("kappaLayout")
        self.kappaSpinBox = QtWidgets.QDoubleSpinBox(self.userTab)
        self.kappaSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.kappaSpinBox.setDecimals(4)
        self.kappaSpinBox.setMinimum(-360.0)
        self.kappaSpinBox.setMaximum(360.0)
        self.kappaSpinBox.setObjectName("kappaSpinBox")
        self.kappaLayout.addWidget(self.kappaSpinBox)
        self.kappaLabel = QtWidgets.QLabel(self.userTab)
        self.kappaLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.kappaLabel.setObjectName("kappaLabel")
        self.kappaLayout.addWidget(self.kappaLabel)
        self.verticalLayout_5.addLayout(self.kappaLayout)
        self.verticalLayout_54.addLayout(self.verticalLayout_5)
        self.line_2 = QtWidgets.QFrame(self.userTab)
        self.line_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_54.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.userTab)
        self.label_9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.pldistdSpinBox = QtWidgets.QDoubleSpinBox(self.userTab)
        self.pldistdSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pldistdSpinBox.setDecimals(4)
        self.pldistdSpinBox.setMinimum(-20.0)
        self.pldistdSpinBox.setMaximum(200.0)
        self.pldistdSpinBox.setObjectName("pldistdSpinBox")
        self.verticalLayout_7.addWidget(self.pldistdSpinBox)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.userTab)
        self.label_12.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.plrotSpinBox = QtWidgets.QDoubleSpinBox(self.userTab)
        self.plrotSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.plrotSpinBox.setDecimals(4)
        self.plrotSpinBox.setMinimum(-180.0)
        self.plrotSpinBox.setMaximum(180.0)
        self.plrotSpinBox.setObjectName("plrotSpinBox")
        self.verticalLayout_11.addWidget(self.plrotSpinBox)
        self.gridLayout.addLayout(self.verticalLayout_11, 0, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.userTab)
        self.label_10.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.pldistfSpinBox = QtWidgets.QDoubleSpinBox(self.userTab)
        self.pldistfSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pldistfSpinBox.setDecimals(4)
        self.pldistfSpinBox.setMinimum(-20.0)
        self.pldistfSpinBox.setMaximum(600.0)
        self.pldistfSpinBox.setObjectName("pldistfSpinBox")
        self.verticalLayout_8.addWidget(self.pldistfSpinBox)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.userTab)
        self.label_11.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.plvertSpinBox = QtWidgets.QDoubleSpinBox(self.userTab)
        self.plvertSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.plvertSpinBox.setDecimals(4)
        self.plvertSpinBox.setMinimum(-50.0)
        self.plvertSpinBox.setMaximum(500.0)
        self.plvertSpinBox.setObjectName("plvertSpinBox")
        self.verticalLayout_9.addWidget(self.plvertSpinBox)
        self.gridLayout.addLayout(self.verticalLayout_9, 1, 1, 1, 1)
        self.verticalLayout_54.addLayout(self.gridLayout)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.userTab)
        self.label_16.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_13.addWidget(self.label_16)
        self.timeLabel = QtWidgets.QLabel(self.userTab)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        self.timeLabel.setFont(font)
        self.timeLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout_13.addWidget(self.timeLabel)
        self.horizontalLayout_20.addLayout(self.verticalLayout_13)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_14 = QtWidgets.QLabel(self.userTab)
        self.label_14.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_20.addWidget(self.label_14)
        self.max2ThetaLabel = QtWidgets.QLabel(self.userTab)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        self.max2ThetaLabel.setFont(font)
        self.max2ThetaLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.max2ThetaLabel.setTextFormat(QtCore.Qt.RichText)
        self.max2ThetaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.max2ThetaLabel.setObjectName("max2ThetaLabel")
        self.verticalLayout_20.addWidget(self.max2ThetaLabel)
        self.horizontalLayout_20.addLayout(self.verticalLayout_20)
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.measureButton = QtWidgets.QPushButton(self.userTab)
        self.measureButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.measureButton.setObjectName("measureButton")
        self.horizontalLayout_21.addWidget(self.measureButton)
        self.addSeqButton = QtWidgets.QPushButton(self.userTab)
        self.addSeqButton.setObjectName("addSeqButton")
        self.horizontalLayout_21.addWidget(self.addSeqButton)
        self.abortButton = QtWidgets.QPushButton(self.userTab)
        self.abortButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.abortButton.setObjectName("abortButton")
        self.horizontalLayout_21.addWidget(self.abortButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_21)
        self.verticalLayout_54.addLayout(self.verticalLayout_12)
        self.line_5 = QtWidgets.QFrame(self.userTab)
        self.line_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_54.addWidget(self.line_5)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_19 = QtWidgets.QLabel(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMaximumSize(QtCore.QSize(160, 52))
        self.label_19.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/snbl"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_31.addWidget(self.label_19)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem)
        self.lampLabel = QtWidgets.QLabel(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lampLabel.sizePolicy().hasHeightForWidth())
        self.lampLabel.setSizePolicy(sizePolicy)
        self.lampLabel.setMaximumSize(QtCore.QSize(51, 51))
        self.lampLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lampLabel.setText("")
        self.lampLabel.setPixmap(QtGui.QPixmap(":/lamp"))
        self.lampLabel.setScaledContents(True)
        self.lampLabel.setObjectName("lampLabel")
        self.horizontalLayout_31.addWidget(self.lampLabel)
        self.lampTextLabel = QtWidgets.QLabel(self.userTab)
        self.lampTextLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lampTextLabel.setObjectName("lampTextLabel")
        self.horizontalLayout_31.addWidget(self.lampTextLabel)
        self.verticalLayout_54.addLayout(self.horizontalLayout_31)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/user"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.userTab, icon1, "")
        self.staffTab = QtWidgets.QWidget()
        self.staffTab.setObjectName("staffTab")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.staffTab)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.kappaGroupBox = QtWidgets.QGroupBox(self.staffTab)
        self.kappaGroupBox.setEnabled(True)
        self.kappaGroupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.kappaGroupBox.setObjectName("kappaGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.kappaGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.kappaCheckBox = QtWidgets.QCheckBox(self.kappaGroupBox)
        self.kappaCheckBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.kappaCheckBox.setChecked(True)
        self.kappaCheckBox.setObjectName("kappaCheckBox")
        self.verticalLayout_6.addWidget(self.kappaCheckBox)
        self.phiScanCheckBox = QtWidgets.QCheckBox(self.kappaGroupBox)
        self.phiScanCheckBox.setObjectName("phiScanCheckBox")
        self.verticalLayout_6.addWidget(self.phiScanCheckBox)
        self.verticalLayout_15.addWidget(self.kappaGroupBox)
        self.musstGroupBox = QtWidgets.QGroupBox(self.staffTab)
        self.musstGroupBox.setEnabled(True)
        self.musstGroupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.musstGroupBox.setObjectName("musstGroupBox")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.musstGroupBox)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.modSpinBox = QtWidgets.QSpinBox(self.musstGroupBox)
        self.modSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.modSpinBox.setMinimum(1)
        self.modSpinBox.setMaximum(65536)
        self.modSpinBox.setObjectName("modSpinBox")
        self.horizontalLayout_9.addWidget(self.modSpinBox)
        self.label_20 = QtWidgets.QLabel(self.musstGroupBox)
        self.label_20.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_22.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.mod2SpinBox = QtWidgets.QSpinBox(self.musstGroupBox)
        self.mod2SpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.mod2SpinBox.setMinimum(1)
        self.mod2SpinBox.setMaximum(65536)
        self.mod2SpinBox.setProperty("value", 10)
        self.mod2SpinBox.setObjectName("mod2SpinBox")
        self.horizontalLayout_10.addWidget(self.mod2SpinBox)
        self.label_21 = QtWidgets.QLabel(self.musstGroupBox)
        self.label_21.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_10.addWidget(self.label_21)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_22.addLayout(self.horizontalLayout_10)
        self.verticalLayout_15.addWidget(self.musstGroupBox)
        self.beamGroupBox = QtWidgets.QGroupBox(self.staffTab)
        self.beamGroupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.beamGroupBox.setObjectName("beamGroupBox")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.beamGroupBox)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pauseBeamOffCheckBox = QtWidgets.QCheckBox(self.beamGroupBox)
        self.pauseBeamOffCheckBox.setObjectName("pauseBeamOffCheckBox")
        self.verticalLayout_16.addWidget(self.pauseBeamOffCheckBox)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.zeroSpinBox = QtWidgets.QDoubleSpinBox(self.beamGroupBox)
        self.zeroSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.zeroSpinBox.setDecimals(3)
        self.zeroSpinBox.setMaximum(10000.0)
        self.zeroSpinBox.setProperty("value", 156.88)
        self.zeroSpinBox.setObjectName("zeroSpinBox")
        self.horizontalLayout_11.addWidget(self.zeroSpinBox)
        self.label_22 = QtWidgets.QLabel(self.beamGroupBox)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.beamxSpinBox = QtWidgets.QDoubleSpinBox(self.beamGroupBox)
        self.beamxSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.beamxSpinBox.setDecimals(3)
        self.beamxSpinBox.setMaximum(10000.0)
        self.beamxSpinBox.setProperty("value", 542.414)
        self.beamxSpinBox.setObjectName("beamxSpinBox")
        self.horizontalLayout_12.addWidget(self.beamxSpinBox)
        self.label_23 = QtWidgets.QLabel(self.beamGroupBox)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.beamySpinBox = QtWidgets.QDoubleSpinBox(self.beamGroupBox)
        self.beamySpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.beamySpinBox.setDecimals(3)
        self.beamySpinBox.setMaximum(10000.0)
        self.beamySpinBox.setProperty("value", 732.4)
        self.beamySpinBox.setObjectName("beamySpinBox")
        self.horizontalLayout_13.addWidget(self.beamySpinBox)
        self.label_24 = QtWidgets.QLabel(self.beamGroupBox)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_13.addWidget(self.label_24)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout_16.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.wlSpinBox = QtWidgets.QDoubleSpinBox(self.beamGroupBox)
        self.wlSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.wlSpinBox.setDecimals(7)
        self.wlSpinBox.setMaximum(2.0)
        self.wlSpinBox.setProperty("value", 2.0)
        self.wlSpinBox.setObjectName("wlSpinBox")
        self.horizontalLayout_27.addWidget(self.wlSpinBox)
        self.label_34 = QtWidgets.QLabel(self.beamGroupBox)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_27.addWidget(self.label_34)
        self.updateButton = QtWidgets.QPushButton(self.beamGroupBox)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_27.addWidget(self.updateButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem6)
        self.verticalLayout_16.addLayout(self.horizontalLayout_27)
        self.verticalLayout_15.addWidget(self.beamGroupBox)
        self.detectorGroupBox = QtWidgets.QGroupBox(self.staffTab)
        self.detectorGroupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.detectorGroupBox.setObjectName("detectorGroupBox")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.detectorGroupBox)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_25 = QtWidgets.QLabel(self.detectorGroupBox)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_18.addWidget(self.label_25)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_26 = QtWidgets.QLabel(self.detectorGroupBox)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        self.detectorxSpinBox = QtWidgets.QSpinBox(self.detectorGroupBox)
        self.detectorxSpinBox.setMinimum(1)
        self.detectorxSpinBox.setMaximum(10000)
        self.detectorxSpinBox.setProperty("value", 1679)
        self.detectorxSpinBox.setObjectName("detectorxSpinBox")
        self.horizontalLayout_15.addWidget(self.detectorxSpinBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_27 = QtWidgets.QLabel(self.detectorGroupBox)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_16.addWidget(self.label_27)
        self.detectorySpinBox = QtWidgets.QSpinBox(self.detectorGroupBox)
        self.detectorySpinBox.setMinimum(1)
        self.detectorySpinBox.setMaximum(10000)
        self.detectorySpinBox.setSingleStep(1)
        self.detectorySpinBox.setProperty("value", 1475)
        self.detectorySpinBox.setObjectName("detectorySpinBox")
        self.horizontalLayout_16.addWidget(self.detectorySpinBox)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_16)
        self.verticalLayout_18.addLayout(self.horizontalLayout_14)
        self.verticalLayout_17.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_28 = QtWidgets.QLabel(self.detectorGroupBox)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_19.addWidget(self.label_28)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_29 = QtWidgets.QLabel(self.detectorGroupBox)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.pixelxSpinBox = QtWidgets.QDoubleSpinBox(self.detectorGroupBox)
        self.pixelxSpinBox.setMaximum(1000.0)
        self.pixelxSpinBox.setProperty("value", 172.0)
        self.pixelxSpinBox.setObjectName("pixelxSpinBox")
        self.horizontalLayout_18.addWidget(self.pixelxSpinBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem9)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_30 = QtWidgets.QLabel(self.detectorGroupBox)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_19.addWidget(self.label_30)
        self.pixelySpinBox = QtWidgets.QDoubleSpinBox(self.detectorGroupBox)
        self.pixelySpinBox.setMaximum(1000.0)
        self.pixelySpinBox.setProperty("value", 172.0)
        self.pixelySpinBox.setObjectName("pixelySpinBox")
        self.horizontalLayout_19.addWidget(self.pixelySpinBox)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem10)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_19)
        self.verticalLayout_19.addLayout(self.horizontalLayout_17)
        self.verticalLayout_17.addLayout(self.verticalLayout_19)
        self.verticalLayout_15.addWidget(self.detectorGroupBox)
        spacerItem11 = QtWidgets.QSpacerItem(20, 434, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem11)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/hammer"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.staffTab, icon2, "")
        self.guruTab = QtWidgets.QWidget()
        self.guruTab.setObjectName("guruTab")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.guruTab)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.devicesGroupBox = QtWidgets.QGroupBox(self.guruTab)
        self.devicesGroupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.devicesGroupBox.setObjectName("devicesGroupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.devicesGroupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.devicesGroupBox)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.specServerLineEdit = QtWidgets.QLineEdit(self.devicesGroupBox)
        self.specServerLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.specServerLineEdit.setObjectName("specServerLineEdit")
        self.verticalLayout.addWidget(self.specServerLineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.devicesGroupBox)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.specSessionLineEdit = QtWidgets.QLineEdit(self.devicesGroupBox)
        self.specSessionLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.specSessionLineEdit.setText("")
        self.specSessionLineEdit.setObjectName("specSessionLineEdit")
        self.verticalLayout_2.addWidget(self.specSessionLineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.devicesGroupBox)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.specMotorLineEdit = QtWidgets.QLineEdit(self.devicesGroupBox)
        self.specMotorLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.specMotorLineEdit.setText("")
        self.specMotorLineEdit.setObjectName("specMotorLineEdit")
        self.verticalLayout_3.addWidget(self.specMotorLineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.addDeviceButton = QtWidgets.QToolButton(self.devicesGroupBox)
        self.addDeviceButton.setText("")
        self.addDeviceButton.setIconSize(QtCore.QSize(32, 32))
        self.addDeviceButton.setObjectName("addDeviceButton")
        self.horizontalLayout_2.addWidget(self.addDeviceButton)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.motorsList = QtWidgets.QListWidget(self.devicesGroupBox)
        self.motorsList.setObjectName("motorsList")
        self.verticalLayout_10.addWidget(self.motorsList)
        self.verticalLayout_21.addWidget(self.devicesGroupBox)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.prphiMaxLabel = QtWidgets.QLabel(self.guruTab)
        self.prphiMaxLabel.setObjectName("prphiMaxLabel")
        self.horizontalLayout_22.addWidget(self.prphiMaxLabel)
        self.prphiMaxSpinBox = QtWidgets.QDoubleSpinBox(self.guruTab)
        self.prphiMaxSpinBox.setMaximum(50.0)
        self.prphiMaxSpinBox.setProperty("value", 10.0)
        self.prphiMaxSpinBox.setObjectName("prphiMaxSpinBox")
        self.horizontalLayout_22.addWidget(self.prphiMaxSpinBox)
        self.line_3 = QtWidgets.QFrame(self.guruTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_22.addWidget(self.line_3)
        self.omegaMaxLabel = QtWidgets.QLabel(self.guruTab)
        self.omegaMaxLabel.setObjectName("omegaMaxLabel")
        self.horizontalLayout_22.addWidget(self.omegaMaxLabel)
        self.omegaMaxSpinBox = QtWidgets.QDoubleSpinBox(self.guruTab)
        self.omegaMaxSpinBox.setMaximum(50.0)
        self.omegaMaxSpinBox.setProperty("value", 10.0)
        self.omegaMaxSpinBox.setObjectName("omegaMaxSpinBox")
        self.horizontalLayout_22.addWidget(self.omegaMaxSpinBox)
        self.line_4 = QtWidgets.QFrame(self.guruTab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_22.addWidget(self.line_4)
        self.phiMaxLabel = QtWidgets.QLabel(self.guruTab)
        self.phiMaxLabel.setObjectName("phiMaxLabel")
        self.horizontalLayout_22.addWidget(self.phiMaxLabel)
        self.phiMaxSpinBox = QtWidgets.QDoubleSpinBox(self.guruTab)
        self.phiMaxSpinBox.setMaximum(50.0)
        self.phiMaxSpinBox.setProperty("value", 10.0)
        self.phiMaxSpinBox.setObjectName("phiMaxSpinBox")
        self.horizontalLayout_22.addWidget(self.phiMaxSpinBox)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem12)
        self.verticalLayout_21.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_7 = QtWidgets.QLabel(self.guruTab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_23.addWidget(self.label_7)
        self.minPlvertSpinBox = QtWidgets.QDoubleSpinBox(self.guruTab)
        self.minPlvertSpinBox.setMinimum(-1000.0)
        self.minPlvertSpinBox.setMaximum(1000.0)
        self.minPlvertSpinBox.setProperty("value", -20.0)
        self.minPlvertSpinBox.setObjectName("minPlvertSpinBox")
        self.horizontalLayout_23.addWidget(self.minPlvertSpinBox)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem13)
        self.verticalLayout_21.addLayout(self.horizontalLayout_23)
        spacerItem14 = QtWidgets.QSpacerItem(20, 231, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem14)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem15)
        self.settingsButton = QtWidgets.QPushButton(self.guruTab)
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout_24.addWidget(self.settingsButton)
        self.verticalLayout_21.addLayout(self.horizontalLayout_24)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/guru"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.guruTab, icon3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        WPylatus.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WPylatus)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 49))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        WPylatus.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WPylatus)
        self.statusbar.setObjectName("statusbar")
        WPylatus.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(WPylatus)
        self.toolBar.setIconSize(QtCore.QSize(36, 36))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        WPylatus.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionStatus = QtWidgets.QAction(WPylatus)
        self.actionStatus.setCheckable(True)
        self.actionStatus.setChecked(False)
        self.actionStatus.setObjectName("actionStatus")
        self.actionAlignment = QtWidgets.QAction(WPylatus)
        self.actionAlignment.setCheckable(True)
        self.actionAlignment.setObjectName("actionAlignment")
        self.actionLogging = QtWidgets.QAction(WPylatus)
        self.actionLogging.setCheckable(True)
        self.actionLogging.setChecked(True)
        self.actionLogging.setObjectName("actionLogging")
        self.actionRelMove = QtWidgets.QAction(WPylatus)
        self.actionRelMove.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/relative"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRelMove.setIcon(icon4)
        self.actionRelMove.setObjectName("actionRelMove")
        self.actionStopMotors = QtWidgets.QAction(WPylatus)
        self.actionStopMotors.setObjectName("actionStopMotors")
        self.actionConnectToPilatus = QtWidgets.QAction(WPylatus)
        self.actionConnectToPilatus.setCheckable(False)
        self.actionConnectToPilatus.setIcon(icon)
        self.actionConnectToPilatus.setObjectName("actionConnectToPilatus")
        self.actionConnectToMotors = QtWidgets.QAction(WPylatus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/motor"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnectToMotors.setIcon(icon5)
        self.actionConnectToMotors.setObjectName("actionConnectToMotors")
        self.actionAboutPylatus = QtWidgets.QAction(WPylatus)
        self.actionAboutPylatus.setObjectName("actionAboutPylatus")
        self.actionAboutQt = QtWidgets.QAction(WPylatus)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionUserStatus = QtWidgets.QAction(WPylatus)
        self.actionUserStatus.setCheckable(True)
        self.actionUserStatus.setChecked(True)
        self.actionUserStatus.setObjectName("actionUserStatus")
        self.actionQuit = QtWidgets.QAction(WPylatus)
        self.actionQuit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCryostream = QtWidgets.QAction(WPylatus)
        self.actionCryostream.setCheckable(True)
        self.actionCryostream.setObjectName("actionCryostream")
        self.actionSequence = QtWidgets.QAction(WPylatus)
        self.actionSequence.setCheckable(True)
        self.actionSequence.setObjectName("actionSequence")
        self.actionScriptEditor = QtWidgets.QAction(WPylatus)
        self.actionScriptEditor.setCheckable(True)
        self.actionScriptEditor.setObjectName("actionScriptEditor")
        self.actionGeneralScan = QtWidgets.QAction(WPylatus)
        self.actionGeneralScan.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/scan"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGeneralScan.setIcon(icon6)
        self.actionGeneralScan.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionGeneralScan.setObjectName("actionGeneralScan")
        self.actionBlower = QtWidgets.QAction(WPylatus)
        self.actionBlower.setCheckable(True)
        self.actionBlower.setObjectName("actionBlower")
        self.actionHideMainWindow = QtWidgets.QAction(WPylatus)
        self.actionHideMainWindow.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/eye"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHideMainWindow.setIcon(icon7)
        self.actionHideMainWindow.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionHideMainWindow.setObjectName("actionHideMainWindow")
        self.actionLakeshore = QtWidgets.QAction(WPylatus)
        self.actionLakeshore.setCheckable(True)
        self.actionLakeshore.setObjectName("actionLakeshore")
        self.actionOpen_poni = QtWidgets.QAction(WPylatus)
        self.actionOpen_poni.setObjectName("actionOpen_poni")
        self.actionIsegHV = QtWidgets.QAction(WPylatus)
        self.actionIsegHV.setCheckable(True)
        self.actionIsegHV.setObjectName("actionIsegHV")
        self.menuView.addAction(self.actionLogging)
        self.menuView.addAction(self.actionUserStatus)
        self.menuView.addAction(self.actionRelMove)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStatus)
        self.menuView.addAction(self.actionAlignment)
        self.menuView.addAction(self.actionGeneralScan)
        self.menuControl.addAction(self.actionStopMotors)
        self.menuControl.addAction(self.actionConnectToPilatus)
        self.menuControl.addAction(self.actionConnectToMotors)
        self.menuHelp.addAction(self.actionAboutPylatus)
        self.menuHelp.addAction(self.actionAboutQt)
        self.menuTools.addAction(self.actionCryostream)
        self.menuTools.addAction(self.actionSequence)
        self.menuTools.addAction(self.actionScriptEditor)
        self.menuTools.addAction(self.actionBlower)
        self.menuTools.addAction(self.actionLakeshore)
        self.menuTools.addAction(self.actionIsegHV)
        self.menuFile.addAction(self.actionOpen_poni)
        self.menuFile.addAction(self.actionHideMainWindow)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionHideMainWindow)
        self.toolBar.addAction(self.actionStopMotors)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnectToPilatus)
        self.toolBar.addAction(self.actionConnectToMotors)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLakeshore)
        self.toolBar.addAction(self.actionCryostream)
        self.toolBar.addAction(self.actionBlower)
        self.toolBar.addAction(self.actionIsegHV)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSequence)
        self.toolBar.addAction(self.actionScriptEditor)
        self.label_4.setBuddy(self.filenameLineEdit)
        self.label_13.setBuddy(self.folderLineEdit)
        self.label_5.setBuddy(self.exposureSpinBox)
        self.label_6.setBuddy(self.nframesSpinBox)
        self.label_17.setBuddy(self.nperiodsSpinBox)
        self.dAngleLabel.setBuddy(self.dOmegaSpinBox)
        self.startingAngleLabel.setBuddy(self.omegaSpinBox)
        self.phiLabel.setBuddy(self.phiSpinBox)
        self.kappaLabel.setBuddy(self.kappaSpinBox)
        self.label_9.setBuddy(self.pldistdSpinBox)
        self.label_12.setBuddy(self.plrotSpinBox)
        self.label_10.setBuddy(self.pldistfSpinBox)
        self.label_11.setBuddy(self.plvertSpinBox)

        self.retranslateUi(WPylatus)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WPylatus)

    def retranslateUi(self, WPylatus):
        _translate = QtCore.QCoreApplication.translate
        WPylatus.setWindowTitle(_translate("WPylatus", "Pylatus"))
        self.label_15.setText(_translate("WPylatus", "Set diffraction experiment"))
        self.label_4.setText(_translate("WPylatus", "File &base name"))
        self.filenameLineEdit.setToolTip(_translate("WPylatus", "<html><head/><body><p>Less than 48 characters</p></body></html>"))
        self.filenameLineEdit.setStatusTip(_translate("WPylatus", "Less than 48 characters"))
        self.filenameLineEdit.setWhatsThis(_translate("WPylatus", "<html><head/><body><p>Less than 48 characters</p></body></html>"))
        self.label_13.setText(_translate("WPylatus", "Fo&lder name"))
        self.label_5.setText(_translate("WPylatus", "E&xposure time per image (sec)"))
        self.label_6.setText(_translate("WPylatus", "&Number of images per period"))
        self.label_17.setText(_translate("WPylatus", "Number &of periods"))
        self.dAngleLabel.setText(_translate("WPylatus", "<html><head/><body><p>&Delta;&omega; per image (deg)</p></body></html>"))
        self.startingAngleLabel.setText(_translate("WPylatus", "<html><head/><body><p>Starting &omega;<span style=\" vertical-align:sub;\">0 </span>(deg)</p></body></html>"))
        self.phiLabel.setText(_translate("WPylatus", "<html><head/><body><p>Position of &phi; (deg)</p></body></html>"))
        self.kappaLabel.setText(_translate("WPylatus", "<html><head/><body><p>Position of &kappa; (deg)</p></body></html>"))
        self.label_9.setText(_translate("WPylatus", "<html><head/><body><p>Detector horizontal position (mm)</p></body></html>"))
        self.label_12.setText(_translate("WPylatus", "<html><head/><body><p>Detector tilt (deg)</p></body></html>"))
        self.label_10.setText(_translate("WPylatus", "<html><head/><body><p>Frame horizontal position (mm)</p></body></html>"))
        self.label_11.setText(_translate("WPylatus", "<html><head/><body><p>Detector vertical position (mm)</p></body></html>"))
        self.label_16.setText(_translate("WPylatus", "<html><head/><body><p>Time for the data collection</p></body></html>"))
        self.timeLabel.setText(_translate("WPylatus", "000000"))
        self.label_14.setText(_translate("WPylatus", "<html><head/><body><p>Resolution at the detector top</p></body></html>"))
        self.max2ThetaLabel.setText(_translate("WPylatus", "000000"))
        self.measureButton.setToolTip(_translate("WPylatus", "Start data collection"))
        self.measureButton.setStatusTip(_translate("WPylatus", "Start data collection"))
        self.measureButton.setWhatsThis(_translate("WPylatus", "Start data collection"))
        self.measureButton.setText(_translate("WPylatus", "Start DC"))
        self.addSeqButton.setToolTip(_translate("WPylatus", "Append to the sequence list"))
        self.addSeqButton.setStatusTip(_translate("WPylatus", "Append to the sequence list"))
        self.addSeqButton.setWhatsThis(_translate("WPylatus", "Append to the sequence list"))
        self.addSeqButton.setText(_translate("WPylatus", "To Sequence"))
        self.abortButton.setToolTip(_translate("WPylatus", "Abort current data collection"))
        self.abortButton.setStatusTip(_translate("WPylatus", "Abort current data collection"))
        self.abortButton.setWhatsThis(_translate("WPylatus", "Abort current data collection"))
        self.abortButton.setText(_translate("WPylatus", "Abort DC"))
        self.lampTextLabel.setText(_translate("WPylatus", "Experiment is running"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.userTab), _translate("WPylatus", "User"))
        self.kappaGroupBox.setTitle(_translate("WPylatus", "Kappa parameters"))
        self.kappaCheckBox.setText(_translate("WPylatus", "Do we have the kappa option?"))
        self.phiScanCheckBox.setText(_translate("WPylatus", "Do we perform the phi scan?"))
        self.musstGroupBox.setTitle(_translate("WPylatus", "MUSST parameters"))
        self.label_20.setText(_translate("WPylatus", "Number of frames for the delay"))
        self.label_21.setText(_translate("WPylatus", "Number of images where the pulse high after the delay"))
        self.beamGroupBox.setTitle(_translate("WPylatus", "Beam parameters"))
        self.pauseBeamOffCheckBox.setText(_translate("WPylatus", "Pause experiment when the beam is off?"))
        self.label_22.setText(_translate("WPylatus", "Zero detector distance (mm)"))
        self.label_23.setText(_translate("WPylatus", "Beam X at [0, 0, 0] (pixels)"))
        self.label_24.setText(_translate("WPylatus", "Beam Y at [0, 0, 0] (pixels)"))
        self.label_34.setText(_translate("WPylatus", "<html><head/><body><p>Wavelength (&Aring;)</p></body></html>"))
        self.updateButton.setText(_translate("WPylatus", "Update"))
        self.detectorGroupBox.setTitle(_translate("WPylatus", "Detector parameters"))
        self.label_25.setText(_translate("WPylatus", "Detector size (pixels)"))
        self.label_26.setText(_translate("WPylatus", "x"))
        self.label_27.setText(_translate("WPylatus", "y"))
        self.label_28.setText(_translate("WPylatus", "<html><head/><body><p>Pixel size (μm)</p></body></html>"))
        self.label_29.setText(_translate("WPylatus", "x"))
        self.label_30.setText(_translate("WPylatus", "y"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.staffTab), _translate("WPylatus", "Staff"))
        self.devicesGroupBox.setTitle(_translate("WPylatus", "Devices"))
        self.label.setText(_translate("WPylatus", "Spec server"))
        self.specServerLineEdit.setText(_translate("WPylatus", "snbla1.esrf.fr"))
        self.label_2.setText(_translate("WPylatus", "Spec Session"))
        self.label_3.setText(_translate("WPylatus", "Motor"))
        self.prphiMaxLabel.setText(_translate("WPylatus", "prphi"))
        self.omegaMaxLabel.setText(_translate("WPylatus", "omega"))
        self.phiMaxLabel.setText(_translate("WPylatus", "phi"))
        self.label_7.setText(_translate("WPylatus", "Min plvert"))
        self.settingsButton.setText(_translate("WPylatus", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.guruTab), _translate("WPylatus", "Guru"))
        self.menuView.setTitle(_translate("WPylatus", "&Controls"))
        self.menuControl.setTitle(_translate("WPylatus", "Actio&ns"))
        self.menuHelp.setTitle(_translate("WPylatus", "&Help"))
        self.menuTools.setTitle(_translate("WPylatus", "&Tools"))
        self.menuFile.setTitle(_translate("WPylatus", "&File"))
        self.toolBar.setWindowTitle(_translate("WPylatus", "toolBar"))
        self.actionStatus.setText(_translate("WPylatus", "&Status"))
        self.actionAlignment.setText(_translate("WPylatus", "&Alignment"))
        self.actionLogging.setText(_translate("WPylatus", "&Log window"))
        self.actionRelMove.setText(_translate("WPylatus", "&Relative movements"))
        self.actionStopMotors.setText(_translate("WPylatus", "&Stop all motors"))
        self.actionStopMotors.setToolTip(_translate("WPylatus", "Stop all motors"))
        self.actionConnectToPilatus.setText(_translate("WPylatus", "&Connect to Pilatus"))
        self.actionConnectToMotors.setText(_translate("WPylatus", "Connect to &motors"))
        self.actionAboutPylatus.setText(_translate("WPylatus", "About &Pylatus"))
        self.actionAboutQt.setText(_translate("WPylatus", "&About Qt"))
        self.actionUserStatus.setText(_translate("WPylatus", "&User status"))
        self.actionQuit.setText(_translate("WPylatus", "&Quit"))
        self.actionQuit.setShortcut(_translate("WPylatus", "Ctrl+Q"))
        self.actionCryostream.setText(_translate("WPylatus", "&Cryostream"))
        self.actionSequence.setText(_translate("WPylatus", "&Sequences"))
        self.actionScriptEditor.setText(_translate("WPylatus", "Script &Editor"))
        self.actionGeneralScan.setText(_translate("WPylatus", "General S&can"))
        self.actionGeneralScan.setShortcut(_translate("WPylatus", "Ctrl+Shift+S"))
        self.actionBlower.setText(_translate("WPylatus", "&Blower"))
        self.actionHideMainWindow.setText(_translate("WPylatus", "&Hide main window"))
        self.actionHideMainWindow.setShortcut(_translate("WPylatus", "Ctrl+H"))
        self.actionLakeshore.setText(_translate("WPylatus", "&Lakeshore"))
        self.actionOpen_poni.setText(_translate("WPylatus", "&Open poni..."))
        self.actionOpen_poni.setShortcut(_translate("WPylatus", "Ctrl+O"))
        self.actionIsegHV.setText(_translate("WPylatus", "Iseg HV"))

from . import resources_rc
