
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-15T16:28:51+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a323b08e25e7c2f5c37b68fd75c78a457d9b3f3b",
 "version": "0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
