
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-08T18:37:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "037b8200e0ba9c944b7f0157c4ad4de2feda7ff5",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
