
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-04T15:56:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8236356e17df4e3e55f995c5311141e39e9ecd5f",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
