language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.5
install:
  - ./travisci/install.sh
script:
  - ./travisci/run.sh
after_success:
  - coveralls
cache: pip
addons:
  apt:
    packages:
    - rpm
    - librpm-dev
