
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-07T13:03:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8bbc6e5b4aa167c0593d81c718949624ba7bba16",
 "version": "0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
