# This file automatically generated by
#    c:\jenkins\workspace\pycbc-win\label\all-pythons\pyarch\x64\pyversion\33\couchbase_version.py
# at
#    2018-11-06 14:48:24.411848
__version__ = '2.5.1'