
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8abaabc8a448605243244ba8edc582ba918d997f",
 "version": "0.4.0.b3098"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
