
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d76561f9dbf28ab040b9c91bb992948cb14c2b91",
 "version": "0.1.1a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
