# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tkbeacon
from tkbeacon.models.exact_match_response import ExactMatchResponse  # noqa: E501
from tkbeacon.rest import ApiException


class TestExactMatchResponse(unittest.TestCase):
    """ExactMatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExactMatchResponse(self):
        """Test ExactMatchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tkbeacon.models.exact_match_response.ExactMatchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
