# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tkbeacon
from tkbeacon import build, KnowledgeSource
from tkbeacon.rest import ApiException


class TestBeaconApi(unittest.TestCase):
    """BeaconApi unit test stubs"""

    def setUp(self):
        self.api = build(KnowledgeSource.SMPDB)

    def tearDown(self):
        pass

    def test_get_concept_categories(self):
        """Test case for get_concept_categories

        """
        categories = self.api.get_concept_categories()
        if len(categories) < 1:
            self.fail('Categories must not be empty')

    def test_get_concept_details(self):
        """Test case for get_concept_details

        """
        pass

    def test_get_concepts(self):
        """Test case for get_concepts

        """
        concepts = self.api.get_concepts(keywords='H2')

        if len(concepts) < 1:
            self.fail('Concepts should not be empty')

        for concept in concepts:
            if 'H2' not in concept.name:
                self.fail('get_concepts filter keywords=["H2"] failed for {}'.format(concept.id))

    def test_get_exact_matches_to_concept_list(self):
        """Test case for get_exact_matches_to_concept_list

        """
        pass

    def test_get_knowledge_map(self):
        """Test case for get_knowledge_map

        """
        pass

    def test_get_predicates(self):
        """Test case for get_predicates

        """
        pass

    def test_get_statement_details(self):
        """Test case for get_statement_details

        """
        pass

    def test_get_statements(self):
        """Test case for get_statements

        """
        pass


if __name__ == '__main__':
    unittest.main()
