
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-03T17:32:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a765d5b0dddb48b5ef410b556f82231d3612b3a",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
