language: python
python:
- '3.6'
- 3.7-dev
stages:
- name: after_script
  if: branch = master
install:
- pip install tox-travis codecov flit
script:
- tox
after_script:
- echo [distutils]                                  > ~/.pypirc
- echo index-servers = pypi                        >> ~/.pypirc
- echo [pypi]                                      >> ~/.pypirc
- echo username=$FLIT_USERNAME                     >> ~/.pypirc
- echo password=$FLIT_PASSWORD                     >> ~/.pypirc
- flit build
- flit publish
env:
  global:
  - secure: F7TX3RzQabtFVuom1z412Q6EzQNhr+oGlOr4obzx1O+5qsKn6236AAV0GZP1gjTy/8wR+uxLqtJTvfXNxbdxFfkhuLesJAU5DZVPQe6vpYvvc9Hr/WJhCrd5Rl6jiW6oVw6dNkMDZrire8QQoFnC9ElxrZ9ablU0rAAxhgRdQYiGS97Rw4LqtU/Xi0+i/CvoulKVR3xnWamQ6Z+pggauBcWDio6v8PCjGL5wHVJFJOyeYkzG2TAOyz4rqFA42NGvV+eysIXpLaprnfLV4a4Fnx4P22jaWVndpBi84cQ1YI3h7Sg+eH2Wi790YHJyZPLO1NdzOvf9HhRuRWzdLv6p8vi561wiyYeFVG0MCjtGeFuXfol6sHKFAm6i740rZieFw5Hoi6bYAW46iKJIY2EMWHUbLzsfrQ5vqJgYw8IZGHbZG04FEQy3v3DqUHJsqJnFOkQcHHBisAAa6Ld5cMybF86lpks9rJkcaOh2z0PNXMofPwcioTqLKWzo3CywlTtJifqwquhJGU4rxJvPhLHnQkyoJ/ZVqnk3vQVy5YYoEE7/oajFoXJx13gjDmYt0r5pouCPGL1eHuLUDHhyKdNz4robBInfcKDjE6RIZog3m7wcoB1+FRAhTBI8XrZ9osvkWPYAyS2/Q/NZcsARRVmrt7ZEBa7Ip2a7G04zPyGN7rI=
  - secure: craytCM6RY+PQfQEVKFqPO/dSD2GxztahiyCXs2s5Q6K1/biwHf+GfO+umedoVD6P8xpwVGKHvTCL1hva+3qZtFsjN7z+IDYoTbLqcigHEhaLz+kLIkyaOL4P84EAcyWOrBAu0dLnLUVuGAF2VwAk0kfbF7p9rYdAgaxa6VPsJQsM+JvDsqAmKsKWKpZpV9Nii7qWL9QnbvfWlEdUlfjRsEqiMaIuDCyXVv1b/u0m/MaVLjdHiW47CI23VkYJ1UaRSZcFC19I1iZV9f9edPZiHQMSsFAAQLbkHikf4KqAqRXenhdtZD7vS2vABf3h31TEIE2BuNsi40DJyeoMacxO6Cpck0AfPZiU93iXrg3MfbPu52zBmGoK8uLNgm7h7J0hnudxKLk3jDAgPsL7YxFG+LnH7+EbiE7WC01MW0U2ia6W7Db6E8BXBlY6IlrypNqO9UvEcNPmarBO2O5tLya2C979XtbGMHqeo9LPs5U2tvfGvzD6qKRMJULDobO4eLHTiTtF1VGS7ulfE9Gis+lMF5ifLeYBQSUa0gNqxOmWKCC2V4SL47Q38CHKfRTofQKBwASdIvcq1ulajnuNaxl2/mfJdvwJg+kpMzk+rwzG94DCZu+YMXXRF9J8iYsattCWFKEw/XC1hQGGP++o4tLxHlpve+H+vFnhM58BE6qpNs=
