
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-08T19:01:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3be2be9a6fbb5ee7fde53a10476dac64a82f6ba",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
