# -*- coding: utf-8 -*-

"""
    songkiss

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import songkiss.models.identifier_1

class Artist1(object):

    """Implementation of the 'Artist1' model.

    TODO: type model description here.

    Attributes:
        id (int): TODO: type description here.
        display_name (string): TODO: type description here.
        uri (string): TODO: type description here.
        identifier (list of Identifier1): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id":'id',
        "display_name":'displayName',
        "uri":'uri',
        "identifier":'identifier'
    }

    def __init__(self,
                 id=None,
                 display_name=None,
                 uri=None,
                 identifier=None):
        """Constructor for the Artist1 class"""

        # Initialize members of the class
        self.id = id
        self.display_name = display_name
        self.uri = uri
        self.identifier = identifier


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        display_name = dictionary.get('displayName')
        uri = dictionary.get('uri')
        identifier = None
        if dictionary.get('identifier') != None:
            identifier = list()
            for structure in dictionary.get('identifier'):
                identifier.append(songkiss.models.identifier_1.Identifier1.from_dictionary(structure))

        # Return an object of this model
        return cls(id,
                   display_name,
                   uri,
                   identifier)


