# -*- coding: utf-8 -*-

"""
    songkiss

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class Country(object):

    """Implementation of the 'Country' model.

    TODO: type model description here.

    Attributes:
        display_name (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "display_name":'displayName'
    }

    def __init__(self,
                 display_name=None):
        """Constructor for the Country class"""

        # Initialize members of the class
        self.display_name = display_name


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        display_name = dictionary.get('displayName')

        # Return an object of this model
        return cls(display_name)


