# -*- coding: utf-8 -*-

"""
    songkiss

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import songkiss.models.results_page

class GETSimilarArtistsResponse(object):

    """Implementation of the 'GET_similar_artistsResponse' model.

    TODO: type model description here.

    Attributes:
        results_page (ResultsPage): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "results_page":'resultsPage'
    }

    def __init__(self,
                 results_page=None):
        """Constructor for the GETSimilarArtistsResponse class"""

        # Initialize members of the class
        self.results_page = results_page


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        results_page = songkiss.models.results_page.ResultsPage.from_dictionary(dictionary.get('resultsPage')) if dictionary.get('resultsPage') else None

        # Return an object of this model
        return cls(results_page)


