# -*- coding: utf-8 -*-

"""
    songkiss

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class Identifier1(object):

    """Implementation of the 'Identifier1' model.

    TODO: type model description here.

    Attributes:
        mbid (string): TODO: type description here.
        href (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mbid":'mbid',
        "href":'href'
    }

    def __init__(self,
                 mbid=None,
                 href=None):
        """Constructor for the Identifier1 class"""

        # Initialize members of the class
        self.mbid = mbid
        self.href = href


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        mbid = dictionary.get('mbid')
        href = dictionary.get('href')

        # Return an object of this model
        return cls(mbid,
                   href)


