# -*- coding: utf-8 -*-

"""
    songkiss

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class Location(object):

    """Implementation of the 'Location' model.

    TODO: type model description here.

    Attributes:
        city (string): TODO: type description here.
        lat (float): TODO: type description here.
        lng (float): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "city":'city',
        "lat":'lat',
        "lng":'lng'
    }

    def __init__(self,
                 city=None,
                 lat=None,
                 lng=None):
        """Constructor for the Location class"""

        # Initialize members of the class
        self.city = city
        self.lat = lat
        self.lng = lng


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        city = dictionary.get('city')
        lat = dictionary.get('lat')
        lng = dictionary.get('lng')

        # Return an object of this model
        return cls(city,
                   lat,
                   lng)


