# -*- coding: utf-8 -*-

"""
    songkiss

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import songkiss.models.metro_area

class Venue(object):

    """Implementation of the 'Venue' model.

    TODO: type model description here.

    Attributes:
        id (int): TODO: type description here.
        display_name (string): TODO: type description here.
        uri (string): TODO: type description here.
        metro_area (MetroArea): TODO: type description here.
        lat (float): TODO: type description here.
        lng (float): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id":'id',
        "display_name":'displayName',
        "uri":'uri',
        "metro_area":'metroArea',
        "lat":'lat',
        "lng":'lng'
    }

    def __init__(self,
                 id=None,
                 display_name=None,
                 uri=None,
                 metro_area=None,
                 lat=None,
                 lng=None):
        """Constructor for the Venue class"""

        # Initialize members of the class
        self.id = id
        self.display_name = display_name
        self.uri = uri
        self.metro_area = metro_area
        self.lat = lat
        self.lng = lng


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        display_name = dictionary.get('displayName')
        uri = dictionary.get('uri')
        metro_area = songkiss.models.metro_area.MetroArea.from_dictionary(dictionary.get('metroArea')) if dictionary.get('metroArea') else None
        lat = dictionary.get('lat')
        lng = dictionary.get('lng')

        # Return an object of this model
        return cls(id,
                   display_name,
                   uri,
                   metro_area,
                   lat,
                   lng)


