
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4b00fc0546af7883995ebc92df34982f1acb4122",
 "version": "2021"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
