
'''
This file is automatically generated; Do not edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '1.18.6.post1',
    'branch_nick': '(HEAD',
    'revision_id': 'c7cbb54cd42c5bac4dbef0372cdd3f267f05dad8',
    'revno': 7327
}
