# coding: utf-8

# flake8: noqa
"""
    Vectra API

    Swagger spec for Vectra API v1  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@vectra.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from detect_v1.models.detection import Detection
from detect_v1.models.detections import Detections
from detect_v1.models.error import Error
