# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-13 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge_freshdesk_plugin', '0002_configuration_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
