---
#
# Playbook to install the ELK stack for browbeat
#

- hosts: elk
  remote_user: root
  roles:
    - { role: epel }
    - { role: elasticsearch }
    - { role: fluentd, when: (logging_backend == 'fluentd') }
    - { role: logstash, when: ((logging_backend is none) or (logging_backend == 'logstash')) }
    - { role: nginx }
    - { role: curator, when: install_curator_tool }
    - { role: kibana }
  environment: "{{proxy_env}}"

- hosts: localhost
  connection: local
  roles:
    - { role: es-template }
  environment: "{{proxy_env}}"
