---
#
# Installs a StatsD server on the StatsD host with the default port, does not secure it

- hosts: statsd
  remote_user: root
  roles:
    - epel
    - statsd-install
  environment: "{{proxy_env}}"
