
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-11T22:46:23-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf84ebd3c9b8284e2a031b851bcb2392668f70e7",
 "version": "0.1.1-alpha"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
