
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-15T10:34:18-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b968fdb7d2a1b0c1dcf8ca61ebe10fe7b3d00191",
 "version": "v0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
