
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-18T18:25:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1cbda0a6b9813573baacbecdfd02155dc21ce5f2",
 "version": "2.3.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
