
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-14T18:38:25-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e32bc98e77e7caf5359bad7dd0dcbbdfee39036",
 "version": "0.7.1.post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
