[build-system]
# Minimum requirements for the build system to execute.
# PEP 508 specifications for PEP 518.
requires = [
    "setuptools > 20.2 ",
    "wheel",
]

[tool.black]
line-length = 120
safe = true
