# coding: utf-8

"""
    Vectra API

    Swagger spec for Vectra API v2  # noqa: E501

    OpenAPI spec version: v2
    Contact: support@vectra.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from detect_v2.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def detections_get(self, **kwargs):  # noqa: E501
        """Detection objects contain all the information related to security events detected on the network.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.detections_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str category: The category of the vname attack detected.
        :param int page:
        :param str min_id: >= the id provided
        :param int max_id: <= the id provided
        :param str state: filter by state: active, inactive, ignored, ignored4all
        :param str description: filter by the detection description
        :param str detection_type: filter by the detection type (verbose name)
        :param str detection: filter by the detection type (verbose name)
        :param str detection_category: filter by the detection category
        :param str src_ip: filter by source (ip address)
        :param int threat: filter by threat score
        :param int threat_gte: filter by threat score >= the score provided
        :param int certainty: filter by certainty score
        :param int certainty_gte: filter by certainty score >= the score provided
        :param str last_timestamp: filter by last_timestamp
        :param str host_id: filter by id of the host object a detection is attributed to
        :param list[str] tags: User defined tags added to the detection.
        :param bool is_targeting_key_asset: filter by detections that are targeting a key asset: True, False
        :param str note_modified_timestamp_gte: filter by note_modified_timestamp >= the timestamp provided: 2017-12-31T16:55:50Z
        :return: Detections
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.detections_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.detections_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def detections_get_with_http_info(self, **kwargs):  # noqa: E501
        """Detection objects contain all the information related to security events detected on the network.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.detections_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str category: The category of the vname attack detected.
        :param int page:
        :param str min_id: >= the id provided
        :param int max_id: <= the id provided
        :param str state: filter by state: active, inactive, ignored, ignored4all
        :param str description: filter by the detection description
        :param str detection_type: filter by the detection type (verbose name)
        :param str detection: filter by the detection type (verbose name)
        :param str detection_category: filter by the detection category
        :param str src_ip: filter by source (ip address)
        :param int threat: filter by threat score
        :param int threat_gte: filter by threat score >= the score provided
        :param int certainty: filter by certainty score
        :param int certainty_gte: filter by certainty score >= the score provided
        :param str last_timestamp: filter by last_timestamp
        :param str host_id: filter by id of the host object a detection is attributed to
        :param list[str] tags: User defined tags added to the detection.
        :param bool is_targeting_key_asset: filter by detections that are targeting a key asset: True, False
        :param str note_modified_timestamp_gte: filter by note_modified_timestamp >= the timestamp provided: 2017-12-31T16:55:50Z
        :return: Detections
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['category', 'page', 'min_id', 'max_id', 'state', 'description', 'detection_type', 'detection', 'detection_category', 'src_ip', 'threat', 'threat_gte', 'certainty', 'certainty_gte', 'last_timestamp', 'host_id', 'tags', 'is_targeting_key_asset', 'note_modified_timestamp_gte']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method detections_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'category' in local_var_params:
            query_params.append(('category', local_var_params['category']))  # noqa: E501
        if 'page' in local_var_params:
            query_params.append(('page', local_var_params['page']))  # noqa: E501
        if 'min_id' in local_var_params:
            query_params.append(('min_id', local_var_params['min_id']))  # noqa: E501
        if 'max_id' in local_var_params:
            query_params.append(('max_id', local_var_params['max_id']))  # noqa: E501
        if 'state' in local_var_params:
            query_params.append(('state', local_var_params['state']))  # noqa: E501
        if 'description' in local_var_params:
            query_params.append(('description', local_var_params['description']))  # noqa: E501
        if 'detection_type' in local_var_params:
            query_params.append(('detection_type', local_var_params['detection_type']))  # noqa: E501
        if 'detection' in local_var_params:
            query_params.append(('detection', local_var_params['detection']))  # noqa: E501
        if 'detection_category' in local_var_params:
            query_params.append(('detection_category', local_var_params['detection_category']))  # noqa: E501
        if 'src_ip' in local_var_params:
            query_params.append(('src_ip', local_var_params['src_ip']))  # noqa: E501
        if 'threat' in local_var_params:
            query_params.append(('threat', local_var_params['threat']))  # noqa: E501
        if 'threat_gte' in local_var_params:
            query_params.append(('threat_gte', local_var_params['threat_gte']))  # noqa: E501
        if 'certainty' in local_var_params:
            query_params.append(('certainty', local_var_params['certainty']))  # noqa: E501
        if 'certainty_gte' in local_var_params:
            query_params.append(('certainty_gte', local_var_params['certainty_gte']))  # noqa: E501
        if 'last_timestamp' in local_var_params:
            query_params.append(('last_timestamp', local_var_params['last_timestamp']))  # noqa: E501
        if 'host_id' in local_var_params:
            query_params.append(('host_id', local_var_params['host_id']))  # noqa: E501
        if 'tags' in local_var_params:
            query_params.append(('tags', local_var_params['tags']))  # noqa: E501
            collection_formats['tags'] = 'multi'  # noqa: E501
        if 'is_targeting_key_asset' in local_var_params:
            query_params.append(('is_targeting_key_asset', local_var_params['is_targeting_key_asset']))  # noqa: E501
        if 'note_modified_timestamp_gte' in local_var_params:
            query_params.append(('note_modified_timestamp_gte', local_var_params['note_modified_timestamp_gte']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['TokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/detections', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Detections',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def proxies_get(self, **kwargs):  # noqa: E501
        """proxies_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.proxies_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: Proxies
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.proxies_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.proxies_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def proxies_get_with_http_info(self, **kwargs):  # noqa: E501
        """proxies_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.proxies_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: Proxies
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method proxies_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['TokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/proxies', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Proxies',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def proxies_id_get(self, id, **kwargs):  # noqa: E501
        """proxies_id_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.proxies_id_get(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :return: Proxy
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.proxies_id_get_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.proxies_id_get_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def proxies_id_get_with_http_info(self, id, **kwargs):  # noqa: E501
        """proxies_id_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.proxies_id_get_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :return: Proxy
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method proxies_id_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in local_var_params or
                local_var_params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `proxies_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in local_var_params:
            path_params['id'] = local_var_params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['TokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/proxies/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Proxy',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def proxies_id_patch(self, id, proxies_body, **kwargs):  # noqa: E501
        """proxies_id_patch  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.proxies_id_patch(id, proxies_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :param ProxiesBody proxies_body: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.proxies_id_patch_with_http_info(id, proxies_body, **kwargs)  # noqa: E501
        else:
            (data) = self.proxies_id_patch_with_http_info(id, proxies_body, **kwargs)  # noqa: E501
            return data

    def proxies_id_patch_with_http_info(self, id, proxies_body, **kwargs):  # noqa: E501
        """proxies_id_patch  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.proxies_id_patch_with_http_info(id, proxies_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :param ProxiesBody proxies_body: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['id', 'proxies_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method proxies_id_patch" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in local_var_params or
                local_var_params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `proxies_id_patch`")  # noqa: E501
        # verify the required parameter 'proxies_body' is set
        if ('proxies_body' not in local_var_params or
                local_var_params['proxies_body'] is None):
            raise ValueError("Missing the required parameter `proxies_body` when calling `proxies_id_patch`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in local_var_params:
            path_params['id'] = local_var_params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'proxies_body' in local_var_params:
            body_params = local_var_params['proxies_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['TokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/proxies/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def proxies_post(self, proxies_body, **kwargs):  # noqa: E501
        """proxies_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.proxies_post(proxies_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProxiesBody proxies_body: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.proxies_post_with_http_info(proxies_body, **kwargs)  # noqa: E501
        else:
            (data) = self.proxies_post_with_http_info(proxies_body, **kwargs)  # noqa: E501
            return data

    def proxies_post_with_http_info(self, proxies_body, **kwargs):  # noqa: E501
        """proxies_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.proxies_post_with_http_info(proxies_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProxiesBody proxies_body: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['proxies_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method proxies_post" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'proxies_body' is set
        if ('proxies_body' not in local_var_params or
                local_var_params['proxies_body'] is None):
            raise ValueError("Missing the required parameter `proxies_body` when calling `proxies_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'proxies_body' in local_var_params:
            body_params = local_var_params['proxies_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['TokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/proxies', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def search_detections_get(self, **kwargs):  # noqa: E501
        """search_detections_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_detections_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_size:
        :param str query_string:
        :return: Detections
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_detections_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.search_detections_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def search_detections_get_with_http_info(self, **kwargs):  # noqa: E501
        """search_detections_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_detections_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_size:
        :param str query_string:
        :return: Detections
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['page_size', 'query_string']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_detections_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page_size' in local_var_params:
            query_params.append(('page_size', local_var_params['page_size']))  # noqa: E501
        if 'query_string' in local_var_params:
            query_params.append(('query_string', local_var_params['query_string']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['TokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/search/detections', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Detections',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def search_hosts_get(self, **kwargs):  # noqa: E501
        """search_hosts_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_hosts_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_size:
        :param str query_string:
        :return: Hosts
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_hosts_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.search_hosts_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def search_hosts_get_with_http_info(self, **kwargs):  # noqa: E501
        """search_hosts_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_hosts_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_size:
        :param str query_string:
        :return: Hosts
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['page_size', 'query_string']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_hosts_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page_size' in local_var_params:
            query_params.append(('page_size', local_var_params['page_size']))  # noqa: E501
        if 'query_string' in local_var_params:
            query_params.append(('query_string', local_var_params['query_string']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['TokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/search/hosts', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Hosts',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def threat_feeds_get(self, **kwargs):  # noqa: E501
        """threat_feeds_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.threat_feeds_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: ThreatFeeds
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.threat_feeds_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.threat_feeds_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def threat_feeds_get_with_http_info(self, **kwargs):  # noqa: E501
        """threat_feeds_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.threat_feeds_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: ThreatFeeds
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method threat_feeds_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['TokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/threatFeeds', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ThreatFeeds',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def threat_feeds_id_get(self, id, **kwargs):  # noqa: E501
        """threat_feeds_id_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.threat_feeds_id_get(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :return: ThreatFeed
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.threat_feeds_id_get_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.threat_feeds_id_get_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def threat_feeds_id_get_with_http_info(self, id, **kwargs):  # noqa: E501
        """threat_feeds_id_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.threat_feeds_id_get_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :return: ThreatFeed
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method threat_feeds_id_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in local_var_params or
                local_var_params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `threat_feeds_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in local_var_params:
            path_params['id'] = local_var_params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['appliction/json', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['TokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/threatFeeds/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ThreatFeed',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def threat_feeds_post(self, threat_feeds_body, **kwargs):  # noqa: E501
        """threat_feeds_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.threat_feeds_post(threat_feeds_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ThreatFeedsBody threat_feeds_body: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.threat_feeds_post_with_http_info(threat_feeds_body, **kwargs)  # noqa: E501
        else:
            (data) = self.threat_feeds_post_with_http_info(threat_feeds_body, **kwargs)  # noqa: E501
            return data

    def threat_feeds_post_with_http_info(self, threat_feeds_body, **kwargs):  # noqa: E501
        """threat_feeds_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.threat_feeds_post_with_http_info(threat_feeds_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ThreatFeedsBody threat_feeds_body: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['threat_feeds_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method threat_feeds_post" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'threat_feeds_body' is set
        if ('threat_feeds_body' not in local_var_params or
                local_var_params['threat_feeds_body'] is None):
            raise ValueError("Missing the required parameter `threat_feeds_body` when calling `threat_feeds_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'threat_feeds_body' in local_var_params:
            body_params = local_var_params['threat_feeds_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['TokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/threatFeeds', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
