
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0e057be388e60d51f45078a21b20e01f951d6255",
 "version": "0.4.2.a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
