[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "simple-smartsheet"
version = "0.1.0"
description = "Python library to interact with smartsheets"
authors = ["Dmitry Figol <git@dmfigol.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6.1"
marshmallow = "^3.0.0b19"
requests = "^2.20"
attrs = "^18.2"
cattrs = "^0.9.0"
pendulum = "^2.0"
python-decouple = "^3.1"

[tool.poetry.dev-dependencies]
ipython = "^7.0"
flake8 = "^3.5"
mypy = "^0.641.0"
ipdb = "^0.11.0"
black = "^18.3-alpha.0"
isort = "^4.3"
