language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
install:
    - pip install zope.testrunner coverage coveralls zope.testing mock
    - pip install -e .
script:
    - coverage run --source=irclog2html -m zope.testrunner --test-path=src
after_script:
    - coveralls
    - coverage report -m
notifications:
    email: false
