
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-26T13:40:48-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "25f9c6c1596ca85aa8ab530dd10e6465a3574ef3",
 "version": "0.1.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
