
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-07T05:19:15-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "920ef67a8bfaea725b251cbd61554f1492626590",
 "version": "0.0.1rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
