
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-20T20:54:30-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c6254074f64a22ddabe0e8f45c1b94836bd1189",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
