
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-02T14:57:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "84264c412ae433ba3956b47c06b5f49f27ad21e4",
 "version": "2.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
