image: python:3.6.6
pipelines:
  default:
    - step:
       script:
         - pip install -r requirements.txt
         - python manage.py test
       services:
         - postgres
         - redis
definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: 'yogasoft'
    redis:
      image: redis
