#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='publication',
      version='0.0.2',
      description='C{publication} helps you maintain public-api-friendly modules by preventing',
      author='Glyph',
      author_email='glyph@twistedmatrix.com',
      url='https://github.com/glyph/publication',
      py_modules=['publication'],
     )
