
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bb6cee7a20a2a94f400425ae27b995faa09d322e",
 "version": "0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
