[tool.poetry]
name = "migra"
version = "1.0.1541154795"
authors = [ "Robert Lechte <robertlechte@gmail.com>",]
license = "Unlicense"
readme = "README.md"
description = "Like `diff` but for PostgreSQL schemas"
repository = "https://github.com/djrobstep/migra"
homepage = "https://migra.djrobstep.com/"

[tool.poetry.dependencies]
python = "*"
sqlbag = "*"
six = "*"
schemainspect = "*"
psycopg2-binary = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
sqlbag = "*"
pytest = "*"
pytest-cov = "*"
pytest-sugar = "*"
psycopg2-binary = "*"
flake8 = "*"
isort = "*"
black = { version = "*", python = ">=3.6" }

[tool.poetry.scripts]
migra = "migra:do_command"

[tool.poetry.extras]
pg = [ "psycopg2-binary",]
