batch_size: 24
data_augmentation_options:
  - random_horizontal_flip: {}
  - ssd_random_crop: {}
optimizer:
  rms_prop_optimizer:
    learning_rate:
      exponential_decay_learning_rate:
        initial_learning_rate: 0.004
        decay_steps: 800720
        decay_factor: 0.95
    momentum_optimizer_value: 0.9
    decay: 0.9
    epsilon: 1.0
fine_tune_checkpoint_type: detection
fine_tune_checkpoint: checkpoint/model.ckpt
load_all_detection_checkpoint_vars: true
