
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-13T10:26:29-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a04e798615010ed443503540797c8cb93f4acea4",
 "version": "0.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
