
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.9'
version_full = '70fa6180102045a8669f1773de37ed50904a4e35'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

