
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-10T22:19:40-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c739155a4aefa1690dab890e12cb56c6c2e2fc05",
 "version": "0.0.1rc13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
