
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1a66f27174e1701b351a06f8b9f10b73fbeebdca",
 "version": "2022"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
