
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-26T13:33:57-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "877bc1113d35deca150fe0814cfdb66c6b1ae234",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
