# coding: utf-8
# Generated by setup.py for PyCBC on 2018-11-07 13:31:02 +0000.

version = '1.13.0'
date = '2018-11-07 12:52:41 +0000'
release = True
last_release = '1.13.0'

git_hash = '8be203575c720bfc7f1b7a936c90251dede05679'
git_branch = 'None'
git_tag = 'v1.13.0'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Travis CI User <travis@example.org>'
git_build_date = '2018-11-07 13:31:02 +0000'
git_verbose_msg = """Version: 1.13.0
Branch: None
Tag: v1.13.0
Id: 8be203575c720bfc7f1b7a936c90251dede05679
Builder: Travis CI User <travis@example.org>
Build date: 2018-11-07 13:31:02 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
