version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true

environment:
  BROKER_URL: redis://127.0.0.1:6379/0
  BACKEND_URL: redis://127.0.0.1:6379/0
  matrix:
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python36-x64

install:
  - ps: >
      & "$env:PYTHON\python.exe" -m virtualenv C:\pacifica;
      C:\pacifica\Scripts\activate.ps1;
      python -m pip install --upgrade pip setuptools wheel;
      nuget install redis-64 -excludeversion;
      redis-64\tools\redis-server.exe --service-install;
      redis-64\tools\redis-server.exe --service-start;
      python -m pip install -r requirements-dev.txt;
      python -m pip install 'redis<3.0';

build: off

test_script:
  - ps: >
      $env:CARTD_CPCONFIG = "$PWD/travis/cartd/server.conf";
      $env:ARCHIVEINTERFACE_CPCONFIG = "$PWD/travis/archive/server.conf";
      $env:ARCHIVEINTERFACE_CONFIG = "$PWD/travis/archive/config.cfg";
      mkdir C:\tmp; C:\pacifica\Scripts\activate.ps1;
      pre-commit run -a;
      $ai_proc = Start-Process C:\pacifica\Scripts\pacifica-archiveinterface.exe -PassThru -RedirectStandardError archive-error.log -RedirectStandardOutput archive-output.log;
      $env:ARCHIVE_INTERFACE_URL = 'http://127.0.0.1:8080/';
      C:\pacifica\Scripts\pacifica-cartd-cmd.exe dbsync;
      $back_proc = Start-Process C:\pacifica\Scripts\celery.exe -ArgumentList "-A pacifica.cartd.tasks worker -l info -P solo -c 1" -PassThru -RedirectStandardError celery-error.log -RedirectStandardOutput celery-output.log;
      $front_proc = Start-Process C:\pacifica\Scripts\pacifica-cartd.exe -PassThru -RedirectStandardError server-error.log -RedirectStandardOutput server-output.log;
      sleep 4;
      python test_files\archiveinterfacepreload.py;
      pip install .;
      cd tests;
      coverage run --include='*/site-packages/pacifica/downloader/*' -m pytest -v;
      celery -A pacifica.cartd.tasks control shutdown;
      $back_proc | Stop-Process;
      $front_proc | Stop-Process;
      $ai_proc | Stop-Process;
      coverage report -m --fail-under=100;
