
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-27T11:06:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa93600253291421fa27e99416ebeb0af5e54b31",
 "version": "v1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
