# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import coordinator_pb2 as coordinator__pb2


class CoordinatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubmitMessage = channel.stream_unary(
        '/Coordinator/SubmitMessage',
        request_serializer=coordinator__pb2.UpMessage.SerializeToString,
        response_deserializer=coordinator__pb2.Nothing.FromString,
        )
    self.ReceiveMessage = channel.unary_stream(
        '/Coordinator/ReceiveMessage',
        request_serializer=coordinator__pb2.RecvConf.SerializeToString,
        response_deserializer=coordinator__pb2.DownMessage.FromString,
        )


class CoordinatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SubmitMessage(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReceiveMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubmitMessage': grpc.stream_unary_rpc_method_handler(
          servicer.SubmitMessage,
          request_deserializer=coordinator__pb2.UpMessage.FromString,
          response_serializer=coordinator__pb2.Nothing.SerializeToString,
      ),
      'ReceiveMessage': grpc.unary_stream_rpc_method_handler(
          servicer.ReceiveMessage,
          request_deserializer=coordinator__pb2.RecvConf.FromString,
          response_serializer=coordinator__pb2.DownMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Coordinator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
