# Generated by Django 2.0.8 on 2018-11-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(db_index=True, max_length=255, verbose_name='display')),
                ('url', models.TextField(max_length=2000, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', max_length=2000, verbose_name='description')),
                ('tags', models.TextField(blank=True, default='', max_length=2000, verbose_name='tags')),
                ('removed', models.BooleanField(db_index=True, default=False, verbose_name='removed')),
                ('rank', models.IntegerField(db_index=True, default=10, verbose_name='rank')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
        ),
    ]
