
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-04T22:31:41-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3dc0b3fa8c9b9bd81540ffe20c8b7e7a72465274",
 "version": "0.25.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
