
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-14T14:18:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd4e866cf6eaa2dc4af87ea22790a2ade7444c58",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
