
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-06T14:45:54+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "291856b8faccb182804eff0ad57cd74e979e6f89",
 "version": "V0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
