
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-26T00:06:50-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "805c1cf950179d8d177fa08939d11d7763df9e55",
 "version": "0.0.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
