- project:
    templates:
      - check-requirements
      - periodic-stable-jobs-neutron
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - release-notes-jobs
      - publish-openstack-sphinx-docs
    check:
      jobs:
        - legacy-neutron-fwaas-v2-dsvm-tempest
        - legacy-neutron-fwaas-v1-dsvm-tempest
        - legacy-neutron-fwaas-dsvm-functional
        - legacy-grenade-dsvm-neutron-fwaas-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-neutron-fwaas-v1-dsvm-tempest-multinode:
            voting: false
        - legacy-neutron-fwaas-v2-dsvm-tempest-multinode:
            voting: false
    gate:
      jobs:
        - legacy-neutron-fwaas-v2-dsvm-tempest
        - legacy-neutron-fwaas-v1-dsvm-tempest
        - legacy-neutron-fwaas-dsvm-functional
    experimental:
      jobs:
        - legacy-neutron-fwaas-dsvm-fullstack
    post:
      jobs:
        - openstack-tox-cover
