#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='dontforget',
      version='0.0.2',
      description='Cache the results of expensive functions',
      author='James Elford',
      author_email='james.p.elford@gmail.com',
      url='https://github.com/jelford/dontforget',
      py_modules=['dontforget'],
      python_requires='>=3.6',
     )
