[tool.poetry]
name = "pgnotify"
version = "0.1.1541160085"
authors = [ "Robert Lechte <robertlechte@gmail.com>",]
license = "Unlicense"
readme = "README.md"
description = "Easily LISTEN to PostgreSQL NOTIFY notifications"
repository = "https://github.com/djrobstep/pgnotify"
homepage = "https://github.com/djrobstep/pgnotify"

[tool.poetry.dependencies]
python = "*"
psycopg2-binary = "*"
logx = "*"

[tool.poetry.dev-dependencies]
sqlbag = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
pytest-sugar = "*"
tox = "*"
flake8 = "*"
twine = "*"
wheel = "*"
isort = "*"

[tool.poetry.dev-dependencies.black]
version = "*"
python = ">=3.6"
