
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-16T08:58:40-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "121cb6070e93c1addfe141cb891d9913b5e76d74",
 "version": "0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
