sudo: required

services:
  - docker

language: python

env:
  - BASE_OS='fedora:rawhide' INSTALLER='dnf'
  - BASE_OS='fedora:29' INSTALLER='dnf'
  - BASE_OS='fedora:28' INSTALLER='dnf'

branches:
  except:
    - /^experimental/

before_script:
  - sed "s|@BASE_OS@|${BASE_OS}|" Dockerfile.in >Dockerfile
  - docker build -t "rpmrh/$(basename $BASE_OS)" --build-arg installer="$INSTALLER" .

script: docker run --rm -t "rpmrh/$(basename $BASE_OS)"
