[tool.poetry]
name = "twod"
version = "0.1.1"
description = "Two Dimensional Geomtric Objects"
authors = ["jnyjny <erik.oshaughnessy@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/JnyJny/twod"
homepage = "https://github.com/JnyJny/twod"
keywords = [ 'geometry', 'two-dimensional' ]
[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
