[tool.poetry]
name = 'keydope'
version = '0.1.0a2'
description = ''
authors = ['infokiller']
license = 'MIT'
readme = 'README.md'
repository = 'https://github.com/infokiller/keydope'
homepage = 'https://github.com/infokiller/keydope'
include = ['keydope']
classifiers = [
  'Development Status :: 3 - Alpha',
  'Intended Audience :: Developers',
  'Operating System :: POSIX :: Linux',
  'License :: OSI Approved :: MIT License',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.6',
  'Programming Language :: Python :: 3.7'
]
keywords = ['keyboard']

[tool.poetry.dependencies]
python = '>=3.6'
evdev = '^1.1'
python-xlib = '^0.23.0'
inotify_simple = '^1.1'
pyyaml = '^3.13'
tabulate = '^0.8.2'

[tool.poetry.dev-dependencies]
isort = "^4.3"
jedi = "^0.13.1"
pycodestyle = "^2.4"
pydocstyle = "^3.0"
pylint = "^2.2"
pytest = "^4.0"
pytype = "^2018.11"
tox = "^3.5"
pytest-cov = "^2.6"
coverage = "^4.4.2"

[build-system]
requires = ['poetry>=0.12']
build-backend = 'poetry.masonry.api'

[scripts]
keydope = 'bin/keydope'
keydope-analyze-stats = 'bin/keydope-analyze-stats'
