
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-26T20:02:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c3ab67f1b3102b2db5b3222fb845a35846abdb3",
 "version": "0.8.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
