
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-10T22:49:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa3fc4b94111046f28e0fe21d73946a570392e10",
 "version": "0.0.1rc14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
