# The # should be replaced with the
# manila share ID and share access ID
# obtained when creating them
# following the instructions in:
# https://clouddocs.web.cern.ch/clouddocs/containers/tutorials/cephfs.html

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manila-csicephfs-share
provisioner: manila-provisioner
parameters:
  type: "Geneva CephFS Testing"
  zones: nova
  osSecretName: ceph-secret
  osSecretNamespace: default
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: csi-cephfsplugin
  os-shareID: #
  os-shareAccessID: #
  # monitors: {{ CEPHFS_MONITORS|join(',') }}
  provisionVolume: "false"
  rootPath: # /volumes/_nogroup/<uuid>
reclaimPolicy: Delete
