# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: biometrica.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='biometrica.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x62iometrica.proto\"\x1a\n\x0b\x43\x61rdRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\"+\n\x0c\x43\x61rdTRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0e\n\x06ticket\x18\x02 \x01(\x05\"*\n\tCardReply\x12\x0c\n\x04\x61uth\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\nCardTReply\x12\x0c\n\x04\x61uth\x18\x01 \x01(\x08\x12\x0e\n\x06ticket\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"$\n\rFingerRequest\x12\x13\n\x0b\x66ingerprint\x18\x01 \x01(\t\",\n\x0b\x46ingerReply\x12\x0c\n\x04\x61uth\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\x0e\x46ingerTRequest\x12\x13\n\x0b\x66ingerprint\x18\x01 \x01(\t\x12\x0e\n\x06ticket\x18\x02 \x01(\x05\"=\n\x0c\x46ingerTReply\x12\x0c\n\x04\x61uth\x18\x01 \x01(\x08\x12\x0e\n\x06ticket\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"!\n\x0fTerminalRequest\x12\x0e\n\x06secret\x18\x01 \x01(\t\"4\n\rTerminalReply\x12\x12\n\nregistered\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\">\n\x0bTicketReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0e\n\x06ticket\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x0f\n\rTicketRequest\";\n\x0cPhotoRequest\x12\r\n\x05photo\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06ticket\x18\x03 \x01(\x05\"=\n\nPhotoReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0e\n\x06ticket\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\xcd\x02\n\x06\x42mAuth\x12&\n\x08\x43\x61rdAuth\x12\x0c.CardRequest\x1a\n.CardReply\"\x00\x12)\n\tCardTAuth\x12\r.CardTRequest\x1a\x0b.CardTReply\"\x00\x12,\n\nFingerAuth\x12\x0e.FingerRequest\x1a\x0c.FingerReply\"\x00\x12/\n\x0b\x46ingerTAuth\x12\x0f.FingerTRequest\x1a\r.FingerTReply\"\x00\x12\x36\n\x10RegisterTerminal\x12\x10.TerminalRequest\x1a\x0e.TerminalReply\"\x00\x12.\n\x0cGetNewTicket\x12\x0e.TicketRequest\x1a\x0c.TicketReply\"\x00\x12)\n\tSendPhoto\x12\r.PhotoRequest\x1a\x0b.PhotoReply\"\x00\x42\x17\xaa\x02\x14\x42iometrica.Generatedb\x06proto3')
)




_CARDREQUEST = _descriptor.Descriptor(
  name='CardRequest',
  full_name='CardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='CardRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=46,
)


_CARDTREQUEST = _descriptor.Descriptor(
  name='CardTRequest',
  full_name='CardTRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='CardTRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='CardTRequest.ticket', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=91,
)


_CARDREPLY = _descriptor.Descriptor(
  name='CardReply',
  full_name='CardReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='CardReply.auth', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='CardReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=135,
)


_CARDTREPLY = _descriptor.Descriptor(
  name='CardTReply',
  full_name='CardTReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='CardTReply.auth', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='CardTReply.ticket', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='CardTReply.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=196,
)


_FINGERREQUEST = _descriptor.Descriptor(
  name='FingerRequest',
  full_name='FingerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fingerprint', full_name='FingerRequest.fingerprint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=234,
)


_FINGERREPLY = _descriptor.Descriptor(
  name='FingerReply',
  full_name='FingerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='FingerReply.auth', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='FingerReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=280,
)


_FINGERTREQUEST = _descriptor.Descriptor(
  name='FingerTRequest',
  full_name='FingerTRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fingerprint', full_name='FingerTRequest.fingerprint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='FingerTRequest.ticket', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=335,
)


_FINGERTREPLY = _descriptor.Descriptor(
  name='FingerTReply',
  full_name='FingerTReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='FingerTReply.auth', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='FingerTReply.ticket', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='FingerTReply.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=398,
)


_TERMINALREQUEST = _descriptor.Descriptor(
  name='TerminalRequest',
  full_name='TerminalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secret', full_name='TerminalRequest.secret', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=433,
)


_TERMINALREPLY = _descriptor.Descriptor(
  name='TerminalReply',
  full_name='TerminalReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='registered', full_name='TerminalReply.registered', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='TerminalReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=487,
)


_TICKETREPLY = _descriptor.Descriptor(
  name='TicketReply',
  full_name='TicketReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TicketReply.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='TicketReply.ticket', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='TicketReply.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=551,
)


_TICKETREQUEST = _descriptor.Descriptor(
  name='TicketRequest',
  full_name='TicketRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=568,
)


_PHOTOREQUEST = _descriptor.Descriptor(
  name='PhotoRequest',
  full_name='PhotoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='photo', full_name='PhotoRequest.photo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='PhotoRequest.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='PhotoRequest.ticket', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=629,
)


_PHOTOREPLY = _descriptor.Descriptor(
  name='PhotoReply',
  full_name='PhotoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='PhotoReply.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='PhotoReply.ticket', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='PhotoReply.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=631,
  serialized_end=692,
)

DESCRIPTOR.message_types_by_name['CardRequest'] = _CARDREQUEST
DESCRIPTOR.message_types_by_name['CardTRequest'] = _CARDTREQUEST
DESCRIPTOR.message_types_by_name['CardReply'] = _CARDREPLY
DESCRIPTOR.message_types_by_name['CardTReply'] = _CARDTREPLY
DESCRIPTOR.message_types_by_name['FingerRequest'] = _FINGERREQUEST
DESCRIPTOR.message_types_by_name['FingerReply'] = _FINGERREPLY
DESCRIPTOR.message_types_by_name['FingerTRequest'] = _FINGERTREQUEST
DESCRIPTOR.message_types_by_name['FingerTReply'] = _FINGERTREPLY
DESCRIPTOR.message_types_by_name['TerminalRequest'] = _TERMINALREQUEST
DESCRIPTOR.message_types_by_name['TerminalReply'] = _TERMINALREPLY
DESCRIPTOR.message_types_by_name['TicketReply'] = _TICKETREPLY
DESCRIPTOR.message_types_by_name['TicketRequest'] = _TICKETREQUEST
DESCRIPTOR.message_types_by_name['PhotoRequest'] = _PHOTOREQUEST
DESCRIPTOR.message_types_by_name['PhotoReply'] = _PHOTOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CardRequest = _reflection.GeneratedProtocolMessageType('CardRequest', (_message.Message,), dict(
  DESCRIPTOR = _CARDREQUEST,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:CardRequest)
  ))
_sym_db.RegisterMessage(CardRequest)

CardTRequest = _reflection.GeneratedProtocolMessageType('CardTRequest', (_message.Message,), dict(
  DESCRIPTOR = _CARDTREQUEST,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:CardTRequest)
  ))
_sym_db.RegisterMessage(CardTRequest)

CardReply = _reflection.GeneratedProtocolMessageType('CardReply', (_message.Message,), dict(
  DESCRIPTOR = _CARDREPLY,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:CardReply)
  ))
_sym_db.RegisterMessage(CardReply)

CardTReply = _reflection.GeneratedProtocolMessageType('CardTReply', (_message.Message,), dict(
  DESCRIPTOR = _CARDTREPLY,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:CardTReply)
  ))
_sym_db.RegisterMessage(CardTReply)

FingerRequest = _reflection.GeneratedProtocolMessageType('FingerRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINGERREQUEST,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:FingerRequest)
  ))
_sym_db.RegisterMessage(FingerRequest)

FingerReply = _reflection.GeneratedProtocolMessageType('FingerReply', (_message.Message,), dict(
  DESCRIPTOR = _FINGERREPLY,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:FingerReply)
  ))
_sym_db.RegisterMessage(FingerReply)

FingerTRequest = _reflection.GeneratedProtocolMessageType('FingerTRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINGERTREQUEST,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:FingerTRequest)
  ))
_sym_db.RegisterMessage(FingerTRequest)

FingerTReply = _reflection.GeneratedProtocolMessageType('FingerTReply', (_message.Message,), dict(
  DESCRIPTOR = _FINGERTREPLY,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:FingerTReply)
  ))
_sym_db.RegisterMessage(FingerTReply)

TerminalRequest = _reflection.GeneratedProtocolMessageType('TerminalRequest', (_message.Message,), dict(
  DESCRIPTOR = _TERMINALREQUEST,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:TerminalRequest)
  ))
_sym_db.RegisterMessage(TerminalRequest)

TerminalReply = _reflection.GeneratedProtocolMessageType('TerminalReply', (_message.Message,), dict(
  DESCRIPTOR = _TERMINALREPLY,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:TerminalReply)
  ))
_sym_db.RegisterMessage(TerminalReply)

TicketReply = _reflection.GeneratedProtocolMessageType('TicketReply', (_message.Message,), dict(
  DESCRIPTOR = _TICKETREPLY,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:TicketReply)
  ))
_sym_db.RegisterMessage(TicketReply)

TicketRequest = _reflection.GeneratedProtocolMessageType('TicketRequest', (_message.Message,), dict(
  DESCRIPTOR = _TICKETREQUEST,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:TicketRequest)
  ))
_sym_db.RegisterMessage(TicketRequest)

PhotoRequest = _reflection.GeneratedProtocolMessageType('PhotoRequest', (_message.Message,), dict(
  DESCRIPTOR = _PHOTOREQUEST,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:PhotoRequest)
  ))
_sym_db.RegisterMessage(PhotoRequest)

PhotoReply = _reflection.GeneratedProtocolMessageType('PhotoReply', (_message.Message,), dict(
  DESCRIPTOR = _PHOTOREPLY,
  __module__ = 'biometrica_pb2'
  # @@protoc_insertion_point(class_scope:PhotoReply)
  ))
_sym_db.RegisterMessage(PhotoReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\024Biometrica.Generated'))

_BMAUTH = _descriptor.ServiceDescriptor(
  name='BmAuth',
  full_name='BmAuth',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=695,
  serialized_end=1028,
  methods=[
  _descriptor.MethodDescriptor(
    name='CardAuth',
    full_name='BmAuth.CardAuth',
    index=0,
    containing_service=None,
    input_type=_CARDREQUEST,
    output_type=_CARDREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CardTAuth',
    full_name='BmAuth.CardTAuth',
    index=1,
    containing_service=None,
    input_type=_CARDTREQUEST,
    output_type=_CARDTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FingerAuth',
    full_name='BmAuth.FingerAuth',
    index=2,
    containing_service=None,
    input_type=_FINGERREQUEST,
    output_type=_FINGERREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FingerTAuth',
    full_name='BmAuth.FingerTAuth',
    index=3,
    containing_service=None,
    input_type=_FINGERTREQUEST,
    output_type=_FINGERTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterTerminal',
    full_name='BmAuth.RegisterTerminal',
    index=4,
    containing_service=None,
    input_type=_TERMINALREQUEST,
    output_type=_TERMINALREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNewTicket',
    full_name='BmAuth.GetNewTicket',
    index=5,
    containing_service=None,
    input_type=_TICKETREQUEST,
    output_type=_TICKETREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendPhoto',
    full_name='BmAuth.SendPhoto',
    index=6,
    containing_service=None,
    input_type=_PHOTOREQUEST,
    output_type=_PHOTOREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BMAUTH)

DESCRIPTOR.services_by_name['BmAuth'] = _BMAUTH

# @@protoc_insertion_point(module_scope)
