
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-11T23:08:33-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d0d16c1dc6ab78607dc10e56f1786d385106e20",
 "version": "0.1.2-alpha-1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
