
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-23T17:14:44-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "087ffa8cb2eba1d08b4fa0e39ee7f2466ff97395",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
