
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bee607003a4c963565f1b8264e8604bedc0dc423",
 "version": "2032"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
