
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3ab42a526010270117d1ed9770ce91b028dd6c94",
 "version": "0.4.2.a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
