
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-09T00:02:27-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "56b1da06c07b4c1353e1ff8d4701de7fdb252ac2",
 "version": "0.0.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
