
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-20T17:47:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "af88e9758d14af36f06a8cb1edd3fd49215f7249",
 "version": "1.6.62"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
