
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-05T15:22:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2b68c4ca5c2b3000c211a9eee2381be968f7f81",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
