
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.8'
version_full = '453a011430661e6c90299930f8077d15394c809a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

