
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-05T21:48:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "69da0e8741f4aca16298d7f7654fee91e4b498b6",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
