
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-27T13:39:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e91c6402cb19079f4be3c853307259d3d483bf4",
 "version": "v1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
