
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-16T16:50:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e60df1a6384bbf09e57f85d86d9928ecc4e5cec",
 "version": "2.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
