
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-22T16:14:39+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "733d53e9e2cbd6fe599147634b2f2ceb088e45a0",
 "version": "0.1.5-alpha"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
