# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: charonrpc/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='charonrpc/common.proto',
  package='charonrpc',
  syntax='proto3',
  serialized_options=_b('Z*github.com/piotrkowalczuk/charon/charonrpc'),
  serialized_pb=_b('\n\x16\x63haronrpc/common.proto\x12\tcharonrpc\")\n\x05Order\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ndescending\x18\x02 \x01(\x08\x42,Z*github.com/piotrkowalczuk/charon/charonrpcb\x06proto3')
)




_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='charonrpc.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='charonrpc.Order.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='descending', full_name='charonrpc.Order.descending', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['Order'] = _ORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), dict(
  DESCRIPTOR = _ORDER,
  __module__ = 'charonrpc.common_pb2'
  # @@protoc_insertion_point(class_scope:charonrpc.Order)
  ))
_sym_db.RegisterMessage(Order)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
