
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "642b6ed24a9b03bc12557ec7adb0a7a405d3c2ea",
 "version": "0.1.1a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
