
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bed7c2c4b37ab1ea4dce87398f89515add889122",
 "version": "2.0a16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
