
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-18T21:02:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d48844f071801dc2f366d30f8917757f51e51da",
 "version": "1.1.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
