
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-22T11:12:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1cd618d12bf76d3dcbb88945a703051d5736c72",
 "version": "0.0.0a18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
