
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-13T02:41:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca36311cb29e3214b4d804746d763238315b1ebe",
 "version": "0.0.2a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
