# coding: utf-8
# Generated by setup.py for PyCBC on 2018-11-16 19:24:26 +0000.

version = '1.13.1'
date = '2018-11-16 18:26:27 +0000'
release = True
last_release = '1.13.1'

git_hash = '24b36c152500a9b2d06a91af51a874fc7dfa61a8'
git_branch = 'None'
git_tag = 'v1.13.1'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Travis CI User <travis@example.org>'
git_build_date = '2018-11-16 19:24:26 +0000'
git_verbose_msg = """Version: 1.13.1
Branch: None
Tag: v1.13.1
Id: 24b36c152500a9b2d06a91af51a874fc7dfa61a8
Builder: Travis CI User <travis@example.org>
Build date: 2018-11-16 19:24:26 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
