language: python
env:
  global:
  # Set defaults to avoid repeating in most cases
  - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='scipy coveralls coverage codecov mock six appdirs pykdtree pyresample docutils pyyaml matplotlib'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request cron'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
  - CONDA_CHANNEL_PRIORITY='True'
matrix:
  include:
    - env: PYTHON_VERSION=2.7
      os: linux
    - env: PYTHON_VERSION=2.7
      os: osx
      language: generic
    - env: PYTHON_VERSION=3.6
      os: linux
    - env: PYTHON_VERSION=3.6
      os: osx
      language: generic
install:
    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
script: coverage run --source=trollsched setup.py test
after_success:
- if [[ $PYTHON_VERSION == 3.6 ]]; then coveralls; fi
#
notifications:
  slack:
    rooms:
    - pytroll:96mNSYSI1dBjGyzVXkBT6qFt#pytroll-schedule
