[tool.poetry]
name = "snakeless"
version = "0.1.3"
description = "Write true serverless apps with joy"
authors = ["German Ivanov <germivanov@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Tasyp/snakeless"

[tool.poetry.dependencies]
python = "^3.7"
cliff = "^2.14"
halo = "^0.0.21"
schema = "^0.6.8"
google-auth = "^1.5"
PyYAML = "^3.13"
fs = "^2.1"
requests = "^2.20"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
snakeless = "snakeless:main"

[tool.poetry.plugins]

[tool.poetry.plugins."snakeless.cli"]
check = "snakeless.commands:Check"
deploy = "snakeless.commands:Deploy"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
