dist: xenial
language: python
cache: pip
python: "3.6"

stages:
  - name: static analysis
  - name: test
  - name: deploy to pypi
    if: type = push AND tag =~ ^\d+\.\d+\.\d+

jobs:
  include:
    - stage: static analysis
      env: TOXENV=flake8

    - stage: static analysis
      env: TOXENV=mypy
      python: "3.7"

    - stage: test
      env: TOXENV=pypy3
      python: pypy3.5
      after_success: &after_success
        - pip install coveralls
        - coveralls

    - stage: test
      env: TOXENV=py35
      python: "3.5.2"
      after_success: *after_success

    - stage: test
      env: TOXENV=py36
      python: "3.6"
      after_success: *after_success

    - stage: test
      env: TOXENV=py37
      python: "3.7"
      after_success: *after_success

    - stage: deploy to pypi
      install: true
      script: skip
      deploy:
        provider: pypi
        user: agronholm
        password:
          secure: WZBuy8ksaA5ZaTnobsUvP6Nx5RxHJE3vqizuCntx6vYjHWcZtPeTDXq42OjMSIVDISXqnDUaVyMrBcyiZ/GQSGKSy5oYAI0/uKd7gPUWFjNgr/FysGfdJmqoRQC4+P95sd3wopvAByoaQz/lAswl/o+99cJZsT4ACixcLsMQI3c3a2lJiuQKZOAnfRy+A+vDqrwF2MhDG7iLH/wjXuuYwxqaovogGDZNr8OsJAlvNrl/BiMojWP4Z5X0FneUfg2T5D+/haCA4ULAwba3tFqvFNAseFblyD+/f/Gmj1gHxEORljfUxkrrzrSjcrsPxkXQbiv31g2HVD/QmRlZuXsclqXxlD1H7y1FxlaaYZeqWKkrvsQRGVRFHnsiZFzYFDKJQyfM0dYZ3NzVV9BfgNLu19LZhzPfGXF44z2Oa1CxHsQpRMjJVIzrCfdxrjIKFaV4yAgeb4d4+N4kft9W/czw7zOtsTDyjDFbXz1cV2jpnWGLwwd5lR9dhvmyzvk4sr6J9nGwW63Dmg5y7fw/3PfIFH8+3uekFav8AgKltP1+IxFrUKDPaz4Gqgkyvxql7gaR8utpHM/2WnepmuAt1lTYKm0J16fSwrB30zLYexNfgzp9k7KUMo7/Z+o/Pi/lLcPiMVBWWjwzKglTZvM2QsArcP79z2vjNIyhGE3cnRqrK4g=
        distributions: sdist bdist_wheel
        on:
          tags: true
          repo: asphalt-framework/asphalt-serialization

install:
  - pip install "setuptools >= 40.1.0"
  - pip install tox

script: tox

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aa5a289b7a0df8aefd68
  irc:
    channels:
      - "chat.freenode.net#asphalt"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
