
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cb656664010161b9bc734c7d334ba579ebe54565",
 "version": "2030"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
