
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-13T02:53:28-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5840377b423d087836198e4dba946e810f0358d6",
 "version": "0.0.2a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
