
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-16T16:45:50-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2b6a0db582c741d72e453268798c3c47cfcdeb7",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
