
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-09T05:23:17+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6ca7b47066917a442e60f90a5f8b1b70eec661d",
 "version": "1.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
