
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-21T10:19:22-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc780452e0e2029b8b2c20891711a2f0da845486",
 "version": "1.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
