
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-12T02:11:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1564e1314780cbeeaec7ea2c64213f649ef4ca0",
 "version": "2018.11.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
