sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=django18
  - DJANGO_VERSION=django19
  - DJANGO_VERSION=django110
  - DJANGO_VERSION=django20
  - DJANGO_VERSION=django21
  - DJANGO_VERSION=djangodev

matrix:
  allow_failures:
    - env: DJANGO_VERSION=djangodev
  include:
    - python: "3.5"
      env: MODE=flake8
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=django20
    - python: "2.7"
      env: DJANGO_VERSION=django21
    - python: "3.4"
      env: DJANGO_VERSION=django21


cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# command to install dependencies
install:
    - pip install tox coveralls

after_success:
    - coveralls

# command to run tests
script:
    - coverage erase
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION}${MODE}
