# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcms', '0002_auto_20170423_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='key',
        ),
    ]
