# This file automatically generated by
#    C:\Jenkins\workspace\python\python-scripted-build-pipeline@11\couchbase-python-client\couchbase_version.py
# at
#    2018-11-12 17:24:10.036571
__version__ = '2.5.1'