#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['matplotlib']

setup(name='celluloid',
      version='0.1.0',
      description='Easy matplotlib animation.',
      author='Jacques Kvam',
      author_email='jwkvam+pypi@gmail.com',
      url='https://github.com/jwkvam/celluloid',
      py_modules=['celluloid'],
      install_requires=install_requires,
      python_requires='>=3.6',
     )
