
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "405dfd3f1570d9500671b7d9a432f9d7566c8258",
 "version": "2033"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
