# -*- coding: utf-8 -*-

"""
    pythondemomessaging1

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class Metadata(object):

    """Implementation of the 'Metadata' model.

    TODO: type model description here.

    Attributes:
        key_1 (string): TODO: type description here.
        key_2 (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key_1":'key1',
        "key_2":'key2'
    }

    def __init__(self,
                 key_1=None,
                 key_2=None):
        """Constructor for the Metadata class"""

        # Initialize members of the class
        self.key_1 = key_1
        self.key_2 = key_2


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        key_1 = dictionary.get('key1')
        key_2 = dictionary.get('key2')

        # Return an object of this model
        return cls(key_1,
                   key_2)


