
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-20T19:35:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e4423165008204f51caed5c511e133d6e51bbb5",
 "version": "1.6.75"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
