
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-11T17:30:10-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b317fd47a34cb6d4505f2bface56885d1c2bb8d",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
