
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7e5712f4cb13b03c80e2cdbd4f1775211784c0ee",
 "version": "1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
