#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyshoper']

package_data = \
{'': ['*']}

install_requires = \
['backoff',
 'certifi',
 'chardet',
 'idna',
 'requests',
 'uplink',
 'uritemplate',
 'urllib3']

extras_require = \
{'test': ['pytest']}

setup(name='pyshoper',
      version='0.1.2',
      description='Python client to shoper.pl REST api',
      author='Przemysław Łada',
      author_email='przlada@gmail.com',
      url='https://github.com/przlada/pyshoper',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.5',
     )
