language: python
python:
  - "2.7"
  - "3.5"
script:
- echo "no tests"
deploy:
  provider: pypi
  user: Guewen.Baconnier
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    repo: camptocamp/pytest-odoo
    branch: master
    tags: true
