repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/tonybaloney/wily
    rev: master
    hooks:
    - id: wily
      language_version: python3.7