name: traffic
author: Ajenti project
email: e@ajenti.org
url: http://ajenti.org
version: '0.13'
title: 'Traffic Widget'
icon: exchange
dependencies:
    - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
    - !!python/object:aj.plugins.PluginDependency { plugin_name: dashboard }
resources:
    - 'resources/js/module.es'
    - 'resources/js/controllers/widget.controller.es'
    - 'resources/partial/widget.html'
    - 'resources/partial/widget.config.html'
    - 'ng:ajenti.traffic'
