#-*- coding:utf-8 -*-

# This file is generated from the AUTHORS file during the installation process.
# Do not edit it as your changes will be overwritten.

__authors__ = [
    u"Naveen Michaud-Agrawal",
    u"Elizabeth J. Denning",
    u"Christian Beckstein (logo)",
    u"Joshua L. Adelman",
    u"Shobhit Agarwal",
    u"Irfan Alibay",
    u"Balasubramanian",
    u"Utkarsh Bansal",
    u"Jonathan Barnoud",
    u"Tone Bengtsen",
    u"Alejandro Bernardin",
    u"Mateusz Bieniek",
    u"Wouter Boomsma",
    u"Jose Borreguero",
    u"Bart Bruininks",
    u"Sébastien Buchoux",
    u"Sören von Bülow",
    u"David Caplan",
    u"Matthieu Chavent",
    u"Kathleen Clark",
    u"Ruggero Cortini",
    u"Davide Cruz",
    u"Robert Delgado",
    u"John Detlefs",
    u"Xavier Deupi",
    u"Jan Domanski",
    u"David L. Dotson",
    u"Shujie Fan",
    u"Lennard van der Feltz",
    u"Philip Fowler",
    u"Joseph Goose",
    u"Richard J. Gowers",
    u"Lukas Grossar",
    u"Abhinav Gupta",
    u"Akshay Gupta",
    u"Benjamin Hall",
    u"Eugen Hruska",
    u"Kyle J. Huston",
    u"Joe Jordan",
    u"Jon Kapla",
    u"Navya Khare",
    u"Andrew William King",
    u"Max Linke",
    u"Philip Loche",
    u"Jinju Lu",
    u"Micaela Matta",
    u"Andrew R. McCluskey",
    u"Robert McGibbon",
    u"Manuel Nuno Melo",
    u"Dominik 'Rathann' Mierzejewski",
    u"Henry Mull",
    u"Fiona B. Naughton",
    u"Alex Nesterenko",
    u"Hai Nguyen",
    u"Sang Young Noh",
    u"Nabarun Pal",
    u"Mattia F. Palermo",
    u"Danny Parton",
    u"Joshua L. Phillips",
    u"Kashish Punjani",
    u"Vedant Rathore",
    u"Tyler Reddy",
    u"Pedro Reis",
    u"Paul Rigor",
    u"Carlos Yanez S.",
    u"Utkarsh Saxena",
    u"Sean L. Seyler",
    u"Paul Smith",
    u"Andy Somogyi",
    u"Caio S. Souza",
    u"Shantanu Srivastava",
    u"Lukas Stelzl",
    u"Gorman Stock",
    u"Ayush Suhane",
    u"Xiki Tempula",
    u"Matteo Tiberti",
    u"Isaac Virshup",
    u"Nestor Wendt",
    u"Zhiyi Wu",
    u"Zhuyi Xue",
    u"Juan Eiros Zamora",
    u"Johannes Zeman",
    u"Oliver Beckstein"
]
