
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-09T15:15:51-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f95780e13b850527f01c1c6e5f8d9b7fcd4a18d4",
 "version": "1.19.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
