language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs/
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - buildout
script:
  - bin/test
after_sucess:
  - bin/coverage run ./bin/test
  - bin/coverage xml -o coverage.xml
  - coveralls
