
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-22T16:24:45+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d1030304ad94a4758c7d63a5f84762b43ad044c",
 "version": "0.1.5-alpha1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
