
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-07T11:55:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "abed8ed065b5192abf00c6d559e55a159637fdd5",
 "version": "0.0.1rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
