
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-27T12:57:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a82b562554a92c40b781cb0e8e7c77f7de4dc941",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
