# Nexys4 board
ETH:
    ip : "192.168.10.16"
    udp_port : 4660
    tcp_port : 24
    tcp_connection : True

# Trigger
TLU:
    TRIGGER_MODE                         : 0  # Selecting trigger mode: Use trigger inputs/trigger select (0), TLU no handshake (1), TLU simple handshake (2), TLU data handshake (3)
    TRIGGER_SELECT                       : 0  # Selecting trigger input: IO_L1P_T0_AD0P_15 (TDC loop-through) (2), IO_L14N_T2_SRCC_15 (1), disabled (0)
    TRIGGER_INVERT                       : 0  # Inverting trigger input: IO_L1P_T0_AD0P_15 (TDC loop-through) (2), IO_L14N_T2_SRCC_15 (1), disabled (0)
    TRIGGER_VETO_SELECT                  : 1  # Selecting trigger veto: RX FIFO full (1), disabled (0)
    TRIGGER_HANDSHAKE_ACCEPT_WAIT_CYCLES : 3  # Minimum TLU trigger length (TLU data handshale mode) required for accepting the trigger (preventing certain EUDAQ TLU firmware flaws)
    TRIGGER_DATA_DELAY                   : 8  # Depends on the cable length and should be adjusted (run scan/tune_tlu.py)
    TRIGGER_THRESHOLD                    : 0  # Minimum trigger length (standard trigger and TLU no handshake mode) required for accepting the trigger
    DATA_FORMAT                          : 0  # 31bit trigger number (0), 31bit time stamp (1), combined (15bit time stamp + 16bit trigger number) (2)

# FE-I4 command ouput
CMD:
    OUTPUT_MODE : 0  # Selecting command output mode: positive edge (0), negative edge (1), Manchester Code according to IEEE 802.3 (2), Manchester Code according to G.E. Thomas (3)

# FE-I4 data receiver
CH3:
    INVERT_RX : 0  # Inverting data input: disabled (0), enabled (e.g. for DBM modules) (1)

CH2:
    INVERT_RX : 0

CH1:
    INVERT_RX : 0

CH0:
    INVERT_RX : 0
