#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='get_version',
      version='2.0.4',
      description='A version helper in the spirit of versioneer.',
      author='Philipp Angerer',
      author_email='phil.angerer@gmail.com',
      url='https://github.com/flying-sheep/get_version',
      py_modules=['get_version'],
      python_requires='>=3.6',
     )
