
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-15T07:46:27-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e33bb295f03ec6a971deea817462534c4cf2c76",
 "version": "1.24.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
