
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-13T13:37:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba95abf9dc3c89483da1d9626cdda28a9e708f07",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
