# we want to make sure it is run on trusty where sudo is provided for postgres
dist: trusty
language: python
python:
    - "3.6"
sudo: required
env:
    - DATABASE=DUMMY

cache:
  directories:
    - eggs
install:
  - pip install -e .[test]
  - pip install flake8 codecov
  - sleep 5
script:
  - flake8 guillotina_batch --config=setup.cfg
  - pytest -s --cov=guillotina_batch -s --tb=native -v --cov-report term-missing --cov-append guillotina_batch
after_success:
  - codecov
