
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-15T17:00:21+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce03ad39929ffb5a1798ac0bf6c03a52282f99ad",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
