
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-14T14:21:49+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfbb2e0fe8d3bcfa457b3a4b6ea8f935cdf19356",
 "version": "0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
