
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-08T10:13:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "08374bdb4fb24ec8c4c196aeed2b2bf757acffb3",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
