# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mortar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pymortar import hod_pb2 as hod__pb2
from pymortar import mdal_pb2 as mdal__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mortar.proto',
  package='mdalgrpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0cmortar.proto\x12\x08mdalgrpc\x1a\thod.proto\x1a\nmdal.proto\x1a\x1cgoogle/api/annotations.proto\"r\n\x0eQualifyRequest\x12/\n\x0frequiredqueries\x18\x01 \x03(\x0b\x32\x16.mdalgrpc.QueryRequest\x12/\n\x0foptionalqueries\x18\x02 \x03(\x0b\x32\x16.mdalgrpc.QueryRequest\"/\n\x0fQualifyResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\r\n\x05sites\x18\x02 \x03(\t\";\n\x0c\x46\x65tchRequest\x12+\n\x07request\x18\x01 \x01(\x0b\x32\x1a.mdalgrpc.DataQueryRequest\"M\n\rFetchResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12-\n\x08response\x18\x02 \x01(\x0b\x32\x1b.mdalgrpc.DataQueryResponse2\xbe\x01\n\x06Mortar\x12]\n\x07Qualify\x12\x18.mdalgrpc.QualifyRequest\x1a\x19.mdalgrpc.QualifyResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x12/v1/mortar/qualify:\x01*\x12U\n\x05\x46\x65tch\x12\x16.mdalgrpc.FetchRequest\x1a\x17.mdalgrpc.FetchResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v1/mortar/fetch:\x01*b\x06proto3')
  ,
  dependencies=[hod__pb2.DESCRIPTOR,mdal__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_QUALIFYREQUEST = _descriptor.Descriptor(
  name='QualifyRequest',
  full_name='mdalgrpc.QualifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requiredqueries', full_name='mdalgrpc.QualifyRequest.requiredqueries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='optionalqueries', full_name='mdalgrpc.QualifyRequest.optionalqueries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=193,
)


_QUALIFYRESPONSE = _descriptor.Descriptor(
  name='QualifyResponse',
  full_name='mdalgrpc.QualifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='mdalgrpc.QualifyResponse.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sites', full_name='mdalgrpc.QualifyResponse.sites', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=242,
)


_FETCHREQUEST = _descriptor.Descriptor(
  name='FetchRequest',
  full_name='mdalgrpc.FetchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='mdalgrpc.FetchRequest.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=303,
)


_FETCHRESPONSE = _descriptor.Descriptor(
  name='FetchResponse',
  full_name='mdalgrpc.FetchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='mdalgrpc.FetchResponse.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='mdalgrpc.FetchResponse.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=382,
)

_QUALIFYREQUEST.fields_by_name['requiredqueries'].message_type = hod__pb2._QUERYREQUEST
_QUALIFYREQUEST.fields_by_name['optionalqueries'].message_type = hod__pb2._QUERYREQUEST
_FETCHREQUEST.fields_by_name['request'].message_type = mdal__pb2._DATAQUERYREQUEST
_FETCHRESPONSE.fields_by_name['response'].message_type = mdal__pb2._DATAQUERYRESPONSE
DESCRIPTOR.message_types_by_name['QualifyRequest'] = _QUALIFYREQUEST
DESCRIPTOR.message_types_by_name['QualifyResponse'] = _QUALIFYRESPONSE
DESCRIPTOR.message_types_by_name['FetchRequest'] = _FETCHREQUEST
DESCRIPTOR.message_types_by_name['FetchResponse'] = _FETCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QualifyRequest = _reflection.GeneratedProtocolMessageType('QualifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUALIFYREQUEST,
  __module__ = 'mortar_pb2'
  # @@protoc_insertion_point(class_scope:mdalgrpc.QualifyRequest)
  ))
_sym_db.RegisterMessage(QualifyRequest)

QualifyResponse = _reflection.GeneratedProtocolMessageType('QualifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUALIFYRESPONSE,
  __module__ = 'mortar_pb2'
  # @@protoc_insertion_point(class_scope:mdalgrpc.QualifyResponse)
  ))
_sym_db.RegisterMessage(QualifyResponse)

FetchRequest = _reflection.GeneratedProtocolMessageType('FetchRequest', (_message.Message,), dict(
  DESCRIPTOR = _FETCHREQUEST,
  __module__ = 'mortar_pb2'
  # @@protoc_insertion_point(class_scope:mdalgrpc.FetchRequest)
  ))
_sym_db.RegisterMessage(FetchRequest)

FetchResponse = _reflection.GeneratedProtocolMessageType('FetchResponse', (_message.Message,), dict(
  DESCRIPTOR = _FETCHRESPONSE,
  __module__ = 'mortar_pb2'
  # @@protoc_insertion_point(class_scope:mdalgrpc.FetchResponse)
  ))
_sym_db.RegisterMessage(FetchResponse)



_MORTAR = _descriptor.ServiceDescriptor(
  name='Mortar',
  full_name='mdalgrpc.Mortar',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=385,
  serialized_end=575,
  methods=[
  _descriptor.MethodDescriptor(
    name='Qualify',
    full_name='mdalgrpc.Mortar.Qualify',
    index=0,
    containing_service=None,
    input_type=_QUALIFYREQUEST,
    output_type=_QUALIFYRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\027\"\022/v1/mortar/qualify:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='Fetch',
    full_name='mdalgrpc.Mortar.Fetch',
    index=1,
    containing_service=None,
    input_type=_FETCHREQUEST,
    output_type=_FETCHRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\025\"\020/v1/mortar/fetch:\001*')),
  ),
])
_sym_db.RegisterServiceDescriptor(_MORTAR)

DESCRIPTOR.services_by_name['Mortar'] = _MORTAR

# @@protoc_insertion_point(module_scope)
