
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3ccae1c3de52804d518208f467493dec4d2dc0a9",
 "version": "2025"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
