
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f3a6e03358e9e20a0a3f87e785728d11eb063239",
 "version": "2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
