
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-25T23:58:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c96aa34c954dcdee8770b085ae1c9e36c0c75551",
 "version": "1.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
