-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: e306ff3b7d0d9a6fc7d128ef9ca2e0b6e6e76e8f
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: flake8
        args:
        - --max-line-length=79
        - --exclude=*/migrations/*,docs/*
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
        args:
        - requirements-dev.txt
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: ebb1b1bb080b0c960bcf37cf81d09185cec4fc6d
    hooks:
    -   id: pep257
        args:
        - --explain
        - --ignore=D100,D101,D102,D103,D104,D105,D203
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: ec01d99f48a0dabb2ebbb2675139e2cc0fe2aa93
    hooks:
    -   id: python-import-sorter
