language: python
sudo: false
cache: pip
python:
- '3.6'
env:
  matrix:
  - TOXENV=qa
  - DJANGO=111
  - DJANGO=master
matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO=master
install:
- pip install --upgrade pip tox codecov
before_script:
- |
  if [[ -z $TOXENV ]]; then
    export TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/\.//g')-dj$DJANGO
  fi
- echo $TOXENV
script:
- tox -e $TOXENV
after_success:
- codecov
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: dnmVaqnmG6mSrmI9q6nL2l0aGkX56+WAsqdT/J1O2hBpFBOE4NiqH+2ryIqZj1wrvHZ72/jjyT5Xi1MWYxwDtDfkBIp+juHUGPbFfGy3J7EVgGkmf38E5SC2Q9IHc3A1iHxTZAX3o816TP3bt5vwGll3UzSMiaaPRQ/AiK4+og4=
  on:
    tags: true
  distributions: sdist bdist_wheel
  repo: codingjoe/django-stdimage
