sudo: false
cache: pip
dist: trusty
language: python
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
      - gsl-bin
      - libgsl0-dev
      - libgdal1-dev
matrix:
  include:
  - python: 3.5
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: true
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest
- source activate test-environment
- export CPLUS_INCLUDE_PATH=/usr/include/gdal
- export C_INCLUDE_PATH=/usr/include/gdal
- export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH
- pip install cython CythonGSL numpy
- pip install scikit-learn
- pip install pytest pytest-cov
- pip install coverage codecov
- pip install -e .
script:
- pytest --cov
after_success:
- codecov
