
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-07T09:33:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b81043ef39e5e0fadccba98d8bfb1cc8b4fae663",
 "version": "2018.11.07"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
