
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-19T17:19:26+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d67697d11a9e7458b510b7c61e1ff9265676cf00",
 "version": "v0.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
