
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-08T11:01:46-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4cabca70f86ff1bedcf68e4fb9d84e027a5b26df",
 "version": "1.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
