# Generated by Django 2.1.3 on 2018-11-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0004_auto_20181103_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='browser',
            field=models.CharField(max_length=200, null=True, verbose_name='Browser'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='browser_version',
            field=models.CharField(max_length=200, null=True, verbose_name='Browser Version'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country',
            field=models.CharField(max_length=200, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='device_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Device Name'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='device_name_brand',
            field=models.CharField(max_length=200, null=True, verbose_name='Device Brand Name'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='device_name_model',
            field=models.CharField(max_length=200, null=True, verbose_name='Device Model Name'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='device_type',
            field=models.CharField(max_length=200, null=True, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ipaddress',
            field=models.CharField(max_length=200, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=200, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=200, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='os_info_version',
            field=models.CharField(max_length=200, null=True, verbose_name='OS Version'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='State'),
        ),
    ]
