
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2018-11-04T11:35:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9405a44b4f91e8dab1ec9fcc8d8295ddea028e42",
 "version": "v0.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
