
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-19T15:56:13+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7183575f434a3bc79ac58d7ec1dc9986ad953f5f",
 "version": "0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
