
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-08T10:52:46-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "79293efb78c57c339044b0b0e59b406936b20cf7",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
