# auto-generated by dev/version/info-updater.py
# using metadata from dev/metadata.py

SETUP_INFO = dict(
    name = 'walt-node',
    version = '0.9-7',
    install_requires = ['walt-common==0.9-7'],
    author = 'Etienne Duble',
    author_email = 'etienne.duble@imag.fr',
    keywords = 'WalT wireless testbed',
    license = 'LGPL',
    namespace_packages = ['walt'],
    url = 'http://walt.forge.imag.fr/',
    description = 'WalT (Wireless Testbed) software embedded in images.',
    entry_points = dict(
        console_scripts = ['walt-setup-systemd = walt.node.setup.systemd:run', 'walt-serial-autolog = walt.node.serial.autolog:run', 'walt-logs-daemon = walt.node.logs.daemon:run']
    ),
    include_package_data = True,
    scripts = ['sh/walt-monitor', 'sh/walt-echo']
)
