account:
    aws_account_id: AWS_ACCOUNT_ID
    aws_lambda_role: pywren_exec_role
    aws_region: AWS_REGION


lambda:
    memory : 1536
    timeout : 300
    function_name : pywren1

s3:
    bucket: BUCKET_NAME
    pywren_prefix: pywren.jobs

runtime:
    s3_bucket: RUNTIME_BUCKET
    s3_key: RUNTIME_KEY

scheduler:
    map_item_limit: 10000

standalone:
    ec2_instance_type: m4.large
    sqs_queue_name: pywren-queue
    visibility: 10
    ec2_ssh_key : PYWREN_DEFAULT_KEY
    target_ami : TARGET_AMI
    instance_name: pywren-standalone
    instance_profile_name: pywren-standalone
    max_idle_time: 60
    idle_terminate_granularity: 3600
