name: passwd
author: Ajenti project
email: e@ajenti.org
url: http://ajenti.org
version: '0.22'
title: 'User DB API'
icon: cog
dependencies:
    - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
resources:
    - resources/js/module.es
    - resources/js/services/passwd.service.es
    - ng:ajenti.passwd
