
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-09T13:26:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e71ff01750024d80c0bbe576aaa9ca1622dc737b",
 "version": "1.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
