
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-27T12:59:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b20ec356644ec6ff73297265a0f543558ea7c1d",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
