[tool.poetry]
name = "rafi"
version = "0.1.0"
description = "A tiny route dispatcher for Google Cloud Functions."
authors = ["Danilo Braband"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.10"
black = "^18.3-alpha.0"
aiohttp = "^3.4"
flask = "^1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
