
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "75357ea7e794113313a37f024f0b338a655442c7",
 "version": "2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
