language: python
python:
- '2.7'
- '3.5'
- '3.6'
env:
- DEVPI_PLUMBER_SERVER_HOST=127.0.0.1
sudo: false
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install --no-deps -e .
- pip freeze
script: py.test
after_success: coveralls
deploy:
  provider: pypi
  user: BYPyPi
  password:
    secure: MHNvzUDHGS7SQdPxvZL+gayv6RVTNADZspXltt4eyiC3/xo8qTRuABfU2mNVJHtaxxEd7mSGoNHxsJUEPrU2CeDnD6JW760FdqCvGr5uARYkxoJhAAF8hfpUL7Y7XU1bdNVj/naxjLmPD5WayeWWPGObtiP1xnkxwydpCSFYGlM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true

