[tool.poetry]
name = "snakeless-provider-gcloud"
version = "0.1.0"
description = ""
readme = "README.md"
authors = ["German Ivanov <germivanov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
snakeless = "^0.2.0"
requests = "^2.20"
google-auth = "^1.5"
fs = "^2.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.plugins."snakeless.providers"]
gcloud = "snakeless_provider_gcloud:GCloudProvider"

[tool.poetry.plugins."snakeless.schemas"]
gcloud = "snakeless_provider_gcloud:GCLOUD_SCHEMA"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
