# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_time__',
    '__build_status__'
]

__version__ = '2.1.0'
__version_short__ = '2.1.0'
__version_long__ = '2.1.0-0-g9f7fe0f8'
__version_post__ = '0'
__version_commit__ = '9f7fe0f8'
__version_date__ = '2018-08-07 15:48:02 -0400'
__version_dirty__ = False
__build_date__ = '2018-11-10'
__build_time__ = '19:24:15.416941'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
