
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d161d06f1543661625c29d15d55afa2fc8538b51",
 "version": "1.0.0.post.dev434"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
