
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-21T15:48:39+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f109f00da68cfd5eeef064f8b5e0b3771e3ead5c",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
