
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-07T04:34:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8267306bf9b990981d4ea1751474f561bb80f655",
 "version": "0.0.1rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
