[tool.poetry]
name = "gfra"
version = "0.1.0"
description = "REST API framework for Google Serverless Functions"
license = "MIT"
readme = "README.md"
authors = ["German Ivanov <germivanov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
