
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-05T20:12:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8a31760a9814ee1e2f9714073f07be3ded95857",
 "version": "0.8.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
