
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-07T10:17:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "15d154745318c12b84a9bcfe471edee8d4ca4e89",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
