
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-12T01:05:05-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "398e75e0d26651448f5d74c0684ad2ed8a3a05d1",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
