
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d0dd94d97d973e7c61eee5037209b9946c7829a6",
 "version": "2037"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
