[tool.poetry]
name = "aiohttp-middlewares"
version = "0.2.0a0"
description = "Collection of useful middlewares for aiohttp applications."
authors = ["Igor Davydenko <iam@igordavydenko.com>"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://igordavydenko.com/projects.html#aiohttp-middlewares"
repository = "https://github.com/playpauseandstop/aiohttp-middlewares"
documentation = "https://aiohttp-middlewares.readthedocs.io/"
keywords = ["aiohttp", "middlewares"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Internet :: WWW/HTTP :: WSGI",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application"
]

[tool.poetry.dependencies]
python = "^3.5.3"
aiohttp = "^3"
async-timeout = "^1.2 || ^2 || ^3"

[tool.poetry.dev-dependencies]
coveralls = "^1.5"
Sphinx = "^1.8"
sphinx-autodoc-typehints = "^1.3"
tox = "^3.5"
twine = "^1.12"
fastjsonschema = "^2.5"
pytest = "^3.9"
pytest-aiohttp = "^0.3.0"
pytest-cov = "^2.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
