
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-23T10:22:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc1411fcc228b7792b7bc1a3788d0669fb23c58c",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
