
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-13T15:08:53-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "13102d3eeded33a4ad749078de9bbca5000ffbe6",
 "version": "0.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
