[tool.poetry]
name = "dophon_cloud_center"
version = "1.0.1"
description = "dophon cloud reg center"
authors = ["CallMeE <ealohu@163.com>"]
license = "Apache 2.0"
url='https://github.com/Ca11MeE/dophon_cloud'

[tool.poetry.dependencies]
python = "^3.6"
dophon = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
