
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-16T14:49:16+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5431cf47907d0f3ace1d9f52d34612963bed9584",
 "version": "1.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
