
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-13T12:04:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ee87fb3ef6869284de99bfac5c23ae37d301821",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
