# Config file for automatic testing at travis-ci.org
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  matrix:
    - DJANGO_VERSION='Django>=1.10,<1.11'
    - DJANGO_VERSION='Django>=2.0,<2.1'
matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION='Django>=2.0,<2.1'
install:
  - pip install --upgrade pip
  - pip install $DJANGO_VERSION --upgrade
  - django-admin.py --version
  - pip install -q -e .
  - pip install -q -r test-requirements.txt
script:
  - coverage run --source smuggler --branch manage.py test
after_success:
  - coveralls
branches:
  only:
    - master
sudo: false
