
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-04T15:33:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "872fba15f6c0ac24caeaff8767a3f2300c6a2788",
 "version": "0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
