# Generated by Django 2.1.2 on 2018-11-08 00:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djams', '0010_auto_20181105_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='adm_app',
            name='launch_integrated_apps_url',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='adm_app',
            name='app_thumbnail',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\eburm\\Documents\\MEGA\\platform_code\\_merged_project\\app_portal_project\\../media'), upload_to='app_thumbnails'),
        ),
    ]
