
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-25T00:12:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e6b6b3c00f3ecbd84d29a11f2886a1cac7b0017",
 "version": "2018.11.25.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
