
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-11T03:46:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "178aa9199798138fec4a6cde18c76091bcf98f36",
 "version": "0.0.1dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
