[tool.poetry]
name = "ergal"
version = "0.1.5"
description = "The Elegant and Readable General API Library"
readme = "README.md"
authors = ["Elliott Maguire <etgmag@comcast.net>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.20"
xmltodict = "^0.11.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pylint = "^2.1"
nose = "^1.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
