
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "97da7ec08f21361e69829807de8cbd622818bd3f",
 "version": "0.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
