[tool.poetry]
name = "aws-healthchecker-response"
version = "0.1.1"
description = "Django Middleware to return a 200 response to the AWS ELB HealthChecker without doing Host header checks"
authors = ["Matt Magin <matt.magin@cmv.com.au>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.4"
django = ">=1.10"

[tool.poetry.dev-dependencies]
pre-commit = "^1.12"
prospector = "^1.1"
pytest-django = "^3.4"
tox = "^3.5"
mock = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
