language: python
dist: xenial
sudo: true
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.7-dev
  - pypy2.7-5.10.0
  - pypy3.5
env:
  - PYTEST=3.6.4
  - PYTEST=3.7.4
  - PYTEST=3.8.2
  - PYTEST=3.9.3
  - PYTEST=3.10.0
install:
  - pip install -q pytest==$PYTEST
  - pip install -q -e .
script: py.test
