# Generated by Django 2.0.7 on 2018-11-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterforbase',
            name='url_integracao',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
