# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutWindow(object):
    def setupUi(self, AboutWindow):
        AboutWindow.setObjectName("AboutWindow")
        AboutWindow.resize(600, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutWindow.sizePolicy().hasHeightForWidth())
        AboutWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        AboutWindow.setFont(font)
        AboutWindow.setWindowTitle("About")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../data/icon_export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutWindow.setWindowIcon(icon)
        AboutWindow.setIconSize(QtCore.QSize(512, 512))
        self.centralWidget = QtWidgets.QWidget(AboutWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setObjectName("centralWidget")
        self.logo = QtWidgets.QGraphicsView(self.centralWidget)
        self.logo.setGeometry(QtCore.QRect(40, 95, 160, 160))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(128, 128))
        self.logo.setMaximumSize(QtCore.QSize(512, 512))
        self.logo.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo.setLineWidth(0)
        self.logo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.logo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.logo.setForegroundBrush(brush)
        self.logo.setObjectName("logo")
        self.closeButton = QtWidgets.QPushButton(self.centralWidget)
        self.closeButton.setGeometry(QtCore.QRect(240, 305, 120, 25))
        self.closeButton.setAutoFillBackground(False)
        self.closeButton.setDefault(True)
        self.closeButton.setFlat(False)
        self.closeButton.setObjectName("closeButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(330, 100, 241, 151))
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        self.formLayoutWidget.setFont(font)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 11, 11, 11)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.authorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        font.setPointSize(11)
        self.authorLabel.setFont(font)
        self.authorLabel.setObjectName("authorLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.authorLabel)
        self.authorValue = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        font.setPointSize(11)
        self.authorValue.setFont(font)
        self.authorValue.setOpenExternalLinks(True)
        self.authorValue.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.authorValue.setObjectName("authorValue")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.authorValue)
        self.copyrightLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        font.setPointSize(11)
        self.copyrightLabel.setFont(font)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.copyrightLabel)
        self.copyrightValue = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        font.setPointSize(11)
        self.copyrightValue.setFont(font)
        self.copyrightValue.setObjectName("copyrightValue")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.copyrightValue)
        self.licenseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        font.setPointSize(11)
        self.licenseLabel.setFont(font)
        self.licenseLabel.setObjectName("licenseLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.licenseLabel)
        self.licenseValue = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        font.setPointSize(11)
        self.licenseValue.setFont(font)
        self.licenseValue.setTextFormat(QtCore.Qt.AutoText)
        self.licenseValue.setOpenExternalLinks(True)
        self.licenseValue.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.licenseValue.setObjectName("licenseValue")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.licenseValue)
        self.programName = QtWidgets.QLabel(self.centralWidget)
        self.programName.setGeometry(QtCore.QRect(0, 0, 600, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.programName.sizePolicy().hasHeightForWidth())
        self.programName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        font.setPointSize(15)
        self.programName.setFont(font)
        self.programName.setAlignment(QtCore.Qt.AlignCenter)
        self.programName.setIndent(-1)
        self.programName.setObjectName("programName")
        self.version = QtWidgets.QLabel(self.centralWidget)
        self.version.setGeometry(QtCore.QRect(0, 40, 600, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        font.setPointSize(11)
        self.version.setFont(font)
        self.version.setAlignment(QtCore.Qt.AlignCenter)
        self.version.setObjectName("version")
        AboutWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(AboutWindow)
        QtCore.QMetaObject.connectSlotsByName(AboutWindow)

    def retranslateUi(self, AboutWindow):
        _translate = QtCore.QCoreApplication.translate
        self.closeButton.setText(_translate("AboutWindow", "Close"))
        self.authorLabel.setText(_translate("AboutWindow", "Author"))
        self.authorValue.setText(_translate("AboutWindow", "<name>"))
        self.copyrightLabel.setText(_translate("AboutWindow", "Copyright"))
        self.copyrightValue.setText(_translate("AboutWindow", "2017 - now"))
        self.licenseLabel.setText(_translate("AboutWindow", "License"))
        self.licenseValue.setText(_translate("AboutWindow", "<license>"))
        self.programName.setText(_translate("AboutWindow", "<name>"))
        self.version.setText(_translate("AboutWindow", "<version>"))

