# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_job_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddJobDialog(object):
    def setupUi(self, AddJobDialog):
        AddJobDialog.setObjectName("AddJobDialog")
        AddJobDialog.resize(500, 200)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        AddJobDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(AddJobDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.targetDirectory = QtWidgets.QFrame(AddJobDialog)
        self.targetDirectory.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.targetDirectory.setFrameShadow(QtWidgets.QFrame.Raised)
        self.targetDirectory.setObjectName("targetDirectory")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.targetDirectory)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.targetLabel = QtWidgets.QLabel(self.targetDirectory)
        self.targetLabel.setObjectName("targetLabel")
        self.horizontalLayout_2.addWidget(self.targetLabel)
        self.targetEdit = QtWidgets.QLineEdit(self.targetDirectory)
        self.targetEdit.setObjectName("targetEdit")
        self.horizontalLayout_2.addWidget(self.targetEdit)
        self.targetDialogButton = QtWidgets.QToolButton(self.targetDirectory)
        self.targetDialogButton.setObjectName("targetDialogButton")
        self.horizontalLayout_2.addWidget(self.targetDialogButton)
        self.gridLayout.addWidget(self.targetDirectory, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddJobDialog)
        self.buttonBox.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.frame = QtWidgets.QFrame(AddJobDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startBox = QtWidgets.QCheckBox(self.frame)
        self.startBox.setChecked(True)
        self.startBox.setObjectName("startBox")
        self.horizontalLayout_3.addWidget(self.startBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pauseLabel = QtWidgets.QLabel(self.frame)
        self.pauseLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pauseLabel.setObjectName("pauseLabel")
        self.horizontalLayout_3.addWidget(self.pauseLabel)
        self.pauseEdit = QtWidgets.QTimeEdit(self.frame)
        self.pauseEdit.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.pauseEdit.setTime(QtCore.QTime(0, 0, 10))
        self.pauseEdit.setObjectName("pauseEdit")
        self.horizontalLayout_3.addWidget(self.pauseEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 1)
        self.sourceDirectory = QtWidgets.QFrame(AddJobDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceDirectory.sizePolicy().hasHeightForWidth())
        self.sourceDirectory.setSizePolicy(sizePolicy)
        self.sourceDirectory.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sourceDirectory.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sourceDirectory.setObjectName("sourceDirectory")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sourceDirectory)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sourceLabel = QtWidgets.QLabel(self.sourceDirectory)
        self.sourceLabel.setObjectName("sourceLabel")
        self.horizontalLayout.addWidget(self.sourceLabel)
        self.sourceEdit = QtWidgets.QLineEdit(self.sourceDirectory)
        self.sourceEdit.setObjectName("sourceEdit")
        self.horizontalLayout.addWidget(self.sourceEdit)
        self.sourceDialogButton = QtWidgets.QToolButton(self.sourceDirectory)
        self.sourceDialogButton.setObjectName("sourceDialogButton")
        self.horizontalLayout.addWidget(self.sourceDialogButton)
        self.gridLayout.addWidget(self.sourceDirectory, 1, 0, 1, 1)

        self.retranslateUi(AddJobDialog)
        self.buttonBox.accepted.connect(AddJobDialog.accept)
        self.buttonBox.rejected.connect(AddJobDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddJobDialog)

    def retranslateUi(self, AddJobDialog):
        _translate = QtCore.QCoreApplication.translate
        AddJobDialog.setWindowTitle(_translate("AddJobDialog", "Dialog"))
        self.targetLabel.setText(_translate("AddJobDialog", "Target Directory"))
        self.targetDialogButton.setText(_translate("AddJobDialog", "..."))
        self.startBox.setText(_translate("AddJobDialog", "Start"))
        self.pauseLabel.setToolTip(_translate("AddJobDialog", "Pause between the scans."))
        self.pauseLabel.setText(_translate("AddJobDialog", "Pause"))
        self.pauseEdit.setDisplayFormat(_translate("AddJobDialog", "mm:ss"))
        self.sourceLabel.setText(_translate("AddJobDialog", "Source Directory"))
        self.sourceDialogButton.setText(_translate("AddJobDialog", "..."))

