# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(685, 305)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("MP3 Monitoring")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../data/icon_export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(512, 512))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.monitorTableView = QtWidgets.QTableView(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        self.monitorTableView.setFont(font)
        self.monitorTableView.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.monitorTableView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.monitorTableView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.monitorTableView.setLineWidth(1)
        self.monitorTableView.setMidLineWidth(0)
        self.monitorTableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.monitorTableView.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.monitorTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.monitorTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.monitorTableView.setGridStyle(QtCore.Qt.SolidLine)
        self.monitorTableView.setSortingEnabled(True)
        self.monitorTableView.setObjectName("monitorTableView")
        self.monitorTableView.horizontalHeader().setCascadingSectionResizes(False)
        self.monitorTableView.horizontalHeader().setHighlightSections(False)
        self.monitorTableView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.monitorTableView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 685, 23))
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAdd = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        self.actionAdd.setFont(font)
        self.actionAdd.setObjectName("actionAdd")
        self.actionExit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCheckForUpdates = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        self.actionCheckForUpdates.setFont(font)
        self.actionCheckForUpdates.setObjectName("actionCheckForUpdates")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Noto Sans UI")
        self.actionSettings.setFont(font)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionAdd)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionCheckForUpdates)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionSettings)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionAdd.setText(_translate("MainWindow", "&Add..."))
        self.actionAdd.setToolTip(_translate("MainWindow", "Add a directory"))
        self.actionAdd.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionCheckForUpdates.setText(_translate("MainWindow", "Check for updates..."))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))

