
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-22T21:22:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7aeedf650b37ce81063a2646e0434fa3e2203ae4",
 "version": "v2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
