
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a655fcdf1af23e1371f3592e06360d86e85f8125",
 "version": "1.0.post62"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
