
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-17T13:13:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "140bc991b73fedd45365edc1a9deb389f8d9781d",
 "version": "1.0a9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
