
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "da4131f54ba7f2326274e1ae4c36ab6eb1a38e2d",
 "version": "2031"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
