
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-06T22:07:04+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c97c41f09d0fe493c9b72d9e6056836bd70e8b3",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
