
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-14T15:40:57-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "34d3cd0b6ddc964a4ab765f0111f5ef81bc32a6a",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
