# coding: utf-8

# flake8: noqa

"""
    Vectra API

    Swagger spec for Vectra API v1  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@vectra.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from detect_v1.api.detections_api import DetectionsApi

# import ApiClient
from detect_v1.api_client import ApiClient
from detect_v1.configuration import Configuration
# import models into sdk package
from detect_v1.models.detection import Detection
from detect_v1.models.detections import Detections
from detect_v1.models.error import Error
