
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-05T20:58:31-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4a9959c8c62e9a04cd6bb21a96348cb86475ae6",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
