
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-11T18:27:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a65c5401ffcc4614417371b624a8891308c3f691",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
