
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-05T17:08:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b37f5ef2c8d0a9846b740d48fad23674889a09e3",
 "version": "2018.11.05"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
