# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtpad/gui_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 479)
        self.gridLayout_8 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sideMenuList = QtWidgets.QListWidget(Dialog)
        self.sideMenuList.setMinimumSize(QtCore.QSize(150, 0))
        self.sideMenuList.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sideMenuList.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sideMenuList.setObjectName("sideMenuList")
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        self.gridLayout.addWidget(self.sideMenuList, 0, 0, 1, 2)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.safeDeleteBox = QtWidgets.QCheckBox(self.groupBox)
        self.safeDeleteBox.setObjectName("safeDeleteBox")
        self.gridLayout_3.addWidget(self.safeDeleteBox, 3, 0, 1, 2)
        self.resetButton = QtWidgets.QPushButton(self.groupBox)
        self.resetButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.resetButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.resetButton.setCheckable(False)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_3.addWidget(self.resetButton, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 5, 0, 1, 1)
        self.autoIndentBox = QtWidgets.QCheckBox(self.groupBox)
        self.autoIndentBox.setObjectName("autoIndentBox")
        self.gridLayout_3.addWidget(self.autoIndentBox, 4, 0, 1, 2)
        self.deleteEmptyNotesBox = QtWidgets.QCheckBox(self.groupBox)
        self.deleteEmptyNotesBox.setObjectName("deleteEmptyNotesBox")
        self.gridLayout_3.addWidget(self.deleteEmptyNotesBox, 1, 0, 1, 1)
        self.notesDbLine = QtWidgets.QLineEdit(self.groupBox)
        self.notesDbLine.setObjectName("notesDbLine")
        self.gridLayout_3.addWidget(self.notesDbLine, 5, 1, 1, 2)
        self.minimizeBox = QtWidgets.QCheckBox(self.groupBox)
        self.minimizeBox.setObjectName("minimizeBox")
        self.gridLayout_3.addWidget(self.minimizeBox, 0, 0, 1, 1)
        self.hotkeyBox = QtWidgets.QCheckBox(self.groupBox)
        self.hotkeyBox.setObjectName("hotkeyBox")
        self.gridLayout_3.addWidget(self.hotkeyBox, 2, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 0, 0, 1, 1)
        self.nameTextLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.nameTextLine.setObjectName("nameTextLine")
        self.gridLayout_11.addWidget(self.nameTextLine, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 1, 0, 1, 1)
        self.nameImageLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.nameImageLine.setObjectName("nameImageLine")
        self.gridLayout_11.addWidget(self.nameImageLine, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 2, 0, 1, 1)
        self.nameFormatTextLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.nameFormatTextLine.setText("")
        self.nameFormatTextLine.setObjectName("nameFormatTextLine")
        self.gridLayout_11.addWidget(self.nameFormatTextLine, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_11.addWidget(self.label_28, 3, 0, 1, 1)
        self.nameFormatImageLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.nameFormatImageLine.setObjectName("nameFormatImageLine")
        self.gridLayout_11.addWidget(self.nameFormatImageLine, 3, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_14.addWidget(self.label_2, 2, 0, 1, 1)
        self.actionCommandLine = QtWidgets.QLineEdit(self.page_2)
        self.actionCommandLine.setEnabled(False)
        self.actionCommandLine.setObjectName("actionCommandLine")
        self.gridLayout_14.addWidget(self.actionCommandLine, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_14.addWidget(self.label, 1, 0, 1, 1)
        self.actionTree = QtWidgets.QTreeWidget(self.page_2)
        self.actionTree.setAlternatingRowColors(True)
        self.actionTree.setObjectName("actionTree")
        self.actionTree.header().setDefaultSectionSize(145)
        self.actionTree.header().setMinimumSectionSize(145)
        self.gridLayout_14.addWidget(self.actionTree, 0, 0, 1, 3)
        self.actionListCombo = QtWidgets.QComboBox(self.page_2)
        self.actionListCombo.setEnabled(False)
        self.actionListCombo.setObjectName("actionListCombo")
        self.gridLayout_14.addWidget(self.actionListCombo, 1, 1, 1, 1)
        self.actionSaveButton = QtWidgets.QPushButton(self.page_2)
        self.actionSaveButton.setEnabled(False)
        self.actionSaveButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.actionSaveButton.setObjectName("actionSaveButton")
        self.gridLayout_14.addWidget(self.actionSaveButton, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_8)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.fetchUrlBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.fetchUrlBox.setObjectName("fetchUrlBox")
        self.gridLayout_13.addWidget(self.fetchUrlBox, 0, 0, 1, 1)
        self.fetchFileBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.fetchFileBox.setObjectName("fetchFileBox")
        self.gridLayout_13.addWidget(self.fetchFileBox, 1, 0, 1, 1)
        self.fetchTxtBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.fetchTxtBox.setObjectName("fetchTxtBox")
        self.gridLayout_13.addWidget(self.fetchTxtBox, 2, 0, 1, 1)
        self.fetchClearBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.fetchClearBox.setObjectName("fetchClearBox")
        self.gridLayout_13.addWidget(self.fetchClearBox, 3, 0, 1, 1)
        self.fetchResizeBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.fetchResizeBox.setObjectName("fetchResizeBox")
        self.gridLayout_13.addWidget(self.fetchResizeBox, 4, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_4, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem1, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_8)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hotkeyAddButton = QtWidgets.QPushButton(self.page_5)
        self.hotkeyAddButton.setObjectName("hotkeyAddButton")
        self.gridLayout_4.addWidget(self.hotkeyAddButton, 4, 4, 1, 1)
        self.hotkeyTree = QtWidgets.QTreeWidget(self.page_5)
        self.hotkeyTree.setAlternatingRowColors(True)
        self.hotkeyTree.setIndentation(20)
        self.hotkeyTree.setObjectName("hotkeyTree")
        self.hotkeyTree.header().setDefaultSectionSize(180)
        self.gridLayout_4.addWidget(self.hotkeyTree, 1, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.page_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.hotkeyKeyLine = QtWidgets.QLineEdit(self.page_5)
        self.hotkeyKeyLine.setReadOnly(True)
        self.hotkeyKeyLine.setObjectName("hotkeyKeyLine")
        self.gridLayout_4.addWidget(self.hotkeyKeyLine, 3, 1, 1, 4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 4, 2, 1, 1)
        self.hotkeyClearButton = QtWidgets.QPushButton(self.page_5)
        self.hotkeyClearButton.setObjectName("hotkeyClearButton")
        self.gridLayout_4.addWidget(self.hotkeyClearButton, 4, 1, 1, 1)
        self.hotkeyDeleteButton = QtWidgets.QPushButton(self.page_5)
        self.hotkeyDeleteButton.setEnabled(False)
        self.hotkeyDeleteButton.setObjectName("hotkeyDeleteButton")
        self.gridLayout_4.addWidget(self.hotkeyDeleteButton, 4, 3, 1, 1)
        self.hotkeyActionCombo = QtWidgets.QComboBox(self.page_5)
        self.hotkeyActionCombo.setObjectName("hotkeyActionCombo")
        self.gridLayout_4.addWidget(self.hotkeyActionCombo, 2, 1, 1, 4)
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.page_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 3, 2, 1, 1)
        self.presetDeleteButton = QtWidgets.QPushButton(self.page_4)
        self.presetDeleteButton.setObjectName("presetDeleteButton")
        self.gridLayout_6.addWidget(self.presetDeleteButton, 4, 3, 1, 1)
        self.presetForegroundButton = QtWidgets.QToolButton(self.page_4)
        self.presetForegroundButton.setObjectName("presetForegroundButton")
        self.gridLayout_6.addWidget(self.presetForegroundButton, 3, 1, 1, 1)
        self.presetNameLine = QtWidgets.QLineEdit(self.page_4)
        self.presetNameLine.setObjectName("presetNameLine")
        self.gridLayout_6.addWidget(self.presetNameLine, 3, 3, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 4, 0, 1, 1)
        self.presetBackgroundButton = QtWidgets.QToolButton(self.page_4)
        self.presetBackgroundButton.setObjectName("presetBackgroundButton")
        self.gridLayout_6.addWidget(self.presetBackgroundButton, 4, 1, 1, 1)
        self.presetTree = QtWidgets.QTreeWidget(self.page_4)
        self.presetTree.setIndentation(0)
        self.presetTree.setItemsExpandable(False)
        self.presetTree.setObjectName("presetTree")
        self.presetTree.header().setStretchLastSection(False)
        self.gridLayout_6.addWidget(self.presetTree, 0, 0, 1, 6)
        self.presetPreviewTextEdit = QtWidgets.QPlainTextEdit(self.page_4)
        self.presetPreviewTextEdit.setMaximumSize(QtCore.QSize(16777215, 70))
        self.presetPreviewTextEdit.setObjectName("presetPreviewTextEdit")
        self.gridLayout_6.addWidget(self.presetPreviewTextEdit, 1, 0, 1, 6)
        self.presetAddButton = QtWidgets.QPushButton(self.page_4)
        self.presetAddButton.setObjectName("presetAddButton")
        self.gridLayout_6.addWidget(self.presetAddButton, 4, 5, 1, 1)
        self.presetSaveButton = QtWidgets.QPushButton(self.page_4)
        self.presetSaveButton.setObjectName("presetSaveButton")
        self.gridLayout_6.addWidget(self.presetSaveButton, 4, 4, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.framelessGroupBox = QtWidgets.QGroupBox(self.page_6)
        self.framelessGroupBox.setObjectName("framelessGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.framelessGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.framelessBorderButton = QtWidgets.QToolButton(self.framelessGroupBox)
        self.framelessBorderButton.setObjectName("framelessBorderButton")
        self.gridLayout_2.addWidget(self.framelessBorderButton, 1, 2, 1, 1)
        self.framelessBorderLabel = QtWidgets.QLabel(self.framelessGroupBox)
        self.framelessBorderLabel.setMinimumSize(QtCore.QSize(16, 16))
        self.framelessBorderLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.framelessBorderLabel.setStyleSheet("QLabel { background-color: #000000; }")
        self.framelessBorderLabel.setText("")
        self.framelessBorderLabel.setObjectName("framelessBorderLabel")
        self.gridLayout_2.addWidget(self.framelessBorderLabel, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.framelessGroupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 3, 1, 1)
        self.framelessBox = QtWidgets.QCheckBox(self.framelessGroupBox)
        self.framelessBox.setObjectName("framelessBox")
        self.gridLayout_2.addWidget(self.framelessBox, 0, 0, 1, 4)
        self.gridLayout_15.addWidget(self.framelessGroupBox, 7, 0, 1, 5)
        self.styleOpacityBox = QtWidgets.QDoubleSpinBox(self.page_6)
        self.styleOpacityBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.styleOpacityBox.setMinimum(0.1)
        self.styleOpacityBox.setMaximum(1.0)
        self.styleOpacityBox.setSingleStep(0.05)
        self.styleOpacityBox.setProperty("value", 1.0)
        self.styleOpacityBox.setObjectName("styleOpacityBox")
        self.gridLayout_15.addWidget(self.styleOpacityBox, 2, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_6)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 3, 0, 1, 2)
        self.attributesGroupBox = QtWidgets.QGroupBox(self.page_6)
        self.attributesGroupBox.setObjectName("attributesGroupBox")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.attributesGroupBox)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.stylePinBox = QtWidgets.QCheckBox(self.attributesGroupBox)
        self.stylePinBox.setObjectName("stylePinBox")
        self.gridLayout_16.addWidget(self.stylePinBox, 0, 0, 1, 1)
        self.styleSizegripBox = QtWidgets.QCheckBox(self.attributesGroupBox)
        self.styleSizegripBox.setObjectName("styleSizegripBox")
        self.gridLayout_16.addWidget(self.styleSizegripBox, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.attributesGroupBox, 7, 5, 1, 1)
        self.styleBackgroundButton = QtWidgets.QToolButton(self.page_6)
        self.styleBackgroundButton.setObjectName("styleBackgroundButton")
        self.gridLayout_15.addWidget(self.styleBackgroundButton, 2, 2, 1, 1)
        self.styleForegroundButton = QtWidgets.QToolButton(self.page_6)
        self.styleForegroundButton.setObjectName("styleForegroundButton")
        self.gridLayout_15.addWidget(self.styleForegroundButton, 3, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_15.addItem(spacerItem5, 4, 1, 1, 1)
        self.styleAllBox = QtWidgets.QCheckBox(self.page_6)
        self.styleAllBox.setText("")
        self.styleAllBox.setObjectName("styleAllBox")
        self.gridLayout_15.addWidget(self.styleAllBox, 3, 5, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.page_6)
        self.label_26.setObjectName("label_26")
        self.gridLayout_15.addWidget(self.label_26, 3, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.page_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_15.addWidget(self.label_17, 0, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem6, 0, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem7, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page_6)
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        self.label_13.setObjectName("label_13")
        self.gridLayout_15.addWidget(self.label_13, 1, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_6)
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        self.label_12.setObjectName("label_12")
        self.gridLayout_15.addWidget(self.label_12, 1, 0, 1, 1)
        self.stylePreviewTextEdit = QtWidgets.QPlainTextEdit(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stylePreviewTextEdit.sizePolicy().hasHeightForWidth())
        self.stylePreviewTextEdit.setSizePolicy(sizePolicy)
        self.stylePreviewTextEdit.setMaximumSize(QtCore.QSize(16777215, 70))
        self.stylePreviewTextEdit.setObjectName("stylePreviewTextEdit")
        self.gridLayout_15.addWidget(self.stylePreviewTextEdit, 5, 0, 1, 6)
        self.label_25 = QtWidgets.QLabel(self.page_6)
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 2, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_6)
        self.label_15.setObjectName("label_15")
        self.gridLayout_15.addWidget(self.label_15, 2, 0, 1, 2)
        self.styleFontFamilyCombo = QtWidgets.QFontComboBox(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.styleFontFamilyCombo.sizePolicy().hasHeightForWidth())
        self.styleFontFamilyCombo.setSizePolicy(sizePolicy)
        self.styleFontFamilyCombo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.styleFontFamilyCombo.setObjectName("styleFontFamilyCombo")
        self.gridLayout_15.addWidget(self.styleFontFamilyCombo, 0, 5, 1, 1)
        self.styleFontSizeBox = QtWidgets.QSpinBox(self.page_6)
        self.styleFontSizeBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.styleFontSizeBox.setMinimum(7)
        self.styleFontSizeBox.setObjectName("styleFontSizeBox")
        self.gridLayout_15.addWidget(self.styleFontSizeBox, 1, 5, 1, 1)
        self.styleWidthBox = QtWidgets.QSpinBox(self.page_6)
        self.styleWidthBox.setMinimumSize(QtCore.QSize(70, 0))
        self.styleWidthBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.styleWidthBox.setMinimum(100)
        self.styleWidthBox.setMaximum(9999)
        self.styleWidthBox.setSingleStep(25)
        self.styleWidthBox.setObjectName("styleWidthBox")
        self.gridLayout_15.addWidget(self.styleWidthBox, 0, 2, 1, 1)
        self.styleHeightBox = QtWidgets.QSpinBox(self.page_6)
        self.styleHeightBox.setMinimumSize(QtCore.QSize(70, 0))
        self.styleHeightBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.styleHeightBox.setMinimum(100)
        self.styleHeightBox.setMaximum(9999)
        self.styleHeightBox.setSingleStep(25)
        self.styleHeightBox.setObjectName("styleHeightBox")
        self.gridLayout_15.addWidget(self.styleHeightBox, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_6)
        self.label_14.setMinimumSize(QtCore.QSize(0, 30))
        self.label_14.setObjectName("label_14")
        self.gridLayout_15.addWidget(self.label_14, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_24 = QtWidgets.QLabel(self.page_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.gridLayout_10.addWidget(self.label_24, 0, 0, 1, 1)
        self.cssCombo = QtWidgets.QComboBox(self.page_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cssCombo.sizePolicy().hasHeightForWidth())
        self.cssCombo.setSizePolicy(sizePolicy)
        self.cssCombo.setObjectName("cssCombo")
        self.gridLayout_10.addWidget(self.cssCombo, 0, 1, 1, 1)
        self.cssRefreshButton = QtWidgets.QToolButton(self.page_9)
        self.cssRefreshButton.setObjectName("cssRefreshButton")
        self.gridLayout_10.addWidget(self.cssRefreshButton, 0, 2, 1, 1)
        self.cssTextEdit = QtWidgets.QPlainTextEdit(self.page_9)
        self.cssTextEdit.setObjectName("cssTextEdit")
        self.gridLayout_10.addWidget(self.cssTextEdit, 1, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_9)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem8, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.page_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 1)
        self.menuMotherAvailableList = QtWidgets.QListWidget(self.page_3)
        self.menuMotherAvailableList.setObjectName("menuMotherAvailableList")
        self.gridLayout_9.addWidget(self.menuMotherAvailableList, 1, 0, 3, 1)
        self.menuMotherSelectedList = QtWidgets.QListWidget(self.page_3)
        self.menuMotherSelectedList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.menuMotherSelectedList.setObjectName("menuMotherSelectedList")
        self.gridLayout_9.addWidget(self.menuMotherSelectedList, 1, 2, 3, 1)
        self.label_22 = QtWidgets.QLabel(self.page_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 0, 2, 1, 1)
        self.menuMotherAddButton = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuMotherAddButton.sizePolicy().hasHeightForWidth())
        self.menuMotherAddButton.setSizePolicy(sizePolicy)
        self.menuMotherAddButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuMotherAddButton.setArrowType(QtCore.Qt.RightArrow)
        self.menuMotherAddButton.setObjectName("menuMotherAddButton")
        self.gridLayout_9.addWidget(self.menuMotherAddButton, 1, 1, 1, 1)
        self.menuMotherRemoveButton = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuMotherRemoveButton.sizePolicy().hasHeightForWidth())
        self.menuMotherRemoveButton.setSizePolicy(sizePolicy)
        self.menuMotherRemoveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuMotherRemoveButton.setArrowType(QtCore.Qt.LeftArrow)
        self.menuMotherRemoveButton.setObjectName("menuMotherRemoveButton")
        self.gridLayout_9.addWidget(self.menuMotherRemoveButton, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_21 = QtWidgets.QLabel(self.page_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 0, 1, 1)
        self.menuChildAvailableList = QtWidgets.QListWidget(self.page_7)
        self.menuChildAvailableList.setObjectName("menuChildAvailableList")
        self.gridLayout_5.addWidget(self.menuChildAvailableList, 1, 0, 3, 1)
        self.menuChildSelectedList = QtWidgets.QListWidget(self.page_7)
        self.menuChildSelectedList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.menuChildSelectedList.setObjectName("menuChildSelectedList")
        self.gridLayout_5.addWidget(self.menuChildSelectedList, 1, 2, 3, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 250, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 3, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 0, 2, 1, 1)
        self.menuChildAddButton = QtWidgets.QToolButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuChildAddButton.sizePolicy().hasHeightForWidth())
        self.menuChildAddButton.setSizePolicy(sizePolicy)
        self.menuChildAddButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuChildAddButton.setArrowType(QtCore.Qt.RightArrow)
        self.menuChildAddButton.setObjectName("menuChildAddButton")
        self.gridLayout_5.addWidget(self.menuChildAddButton, 1, 1, 1, 1)
        self.menuChildRemoveButton = QtWidgets.QToolButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuChildRemoveButton.sizePolicy().hasHeightForWidth())
        self.menuChildRemoveButton.setSizePolicy(sizePolicy)
        self.menuChildRemoveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuChildRemoveButton.setArrowType(QtCore.Qt.LeftArrow)
        self.menuChildRemoveButton.setObjectName("menuChildRemoveButton")
        self.gridLayout_5.addWidget(self.menuChildRemoveButton, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.gridLayout.addWidget(self.stackedWidget, 0, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 4)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.minimizeBox, self.resetButton)
        Dialog.setTabOrder(self.resetButton, self.deleteEmptyNotesBox)
        Dialog.setTabOrder(self.deleteEmptyNotesBox, self.safeDeleteBox)
        Dialog.setTabOrder(self.safeDeleteBox, self.notesDbLine)
        Dialog.setTabOrder(self.notesDbLine, self.autoIndentBox)
        Dialog.setTabOrder(self.autoIndentBox, self.presetForegroundButton)
        Dialog.setTabOrder(self.presetForegroundButton, self.styleWidthBox)
        Dialog.setTabOrder(self.styleWidthBox, self.styleFontFamilyCombo)
        Dialog.setTabOrder(self.styleFontFamilyCombo, self.styleHeightBox)
        Dialog.setTabOrder(self.styleHeightBox, self.styleFontSizeBox)
        Dialog.setTabOrder(self.styleFontSizeBox, self.styleBackgroundButton)
        Dialog.setTabOrder(self.styleBackgroundButton, self.sideMenuList)
        Dialog.setTabOrder(self.sideMenuList, self.menuMotherAvailableList)
        Dialog.setTabOrder(self.menuMotherAvailableList, self.menuMotherAddButton)
        Dialog.setTabOrder(self.menuMotherAddButton, self.menuMotherSelectedList)
        Dialog.setTabOrder(self.menuMotherSelectedList, self.menuMotherRemoveButton)
        Dialog.setTabOrder(self.menuMotherRemoveButton, self.menuChildAvailableList)
        Dialog.setTabOrder(self.menuChildAvailableList, self.menuChildAddButton)
        Dialog.setTabOrder(self.menuChildAddButton, self.menuChildSelectedList)
        Dialog.setTabOrder(self.menuChildSelectedList, self.menuChildRemoveButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        __sortingEnabled = self.sideMenuList.isSortingEnabled()
        self.sideMenuList.setSortingEnabled(False)
        item = self.sideMenuList.item(0)
        item.setText(_translate("Dialog", "General settings"))
        item = self.sideMenuList.item(1)
        item.setText(_translate("Dialog", "Widgets actions"))
        item = self.sideMenuList.item(2)
        item.setText(_translate("Dialog", "Clipboard"))
        item = self.sideMenuList.item(3)
        item.setText(_translate("Dialog", "Hotkeys"))
        item = self.sideMenuList.item(4)
        item.setText(_translate("Dialog", "Style presets"))
        item = self.sideMenuList.item(5)
        item.setText(_translate("Dialog", "Style default"))
        item = self.sideMenuList.item(6)
        item.setText(_translate("Dialog", "Style sheets"))
        item = self.sideMenuList.item(7)
        item.setText(_translate("Dialog", "Main context menu"))
        item = self.sideMenuList.item(8)
        item.setText(_translate("Dialog", "Note context menu"))
        self.sideMenuList.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("Dialog", "General"))
        self.safeDeleteBox.setText(_translate("Dialog", "Enable safe delete (move to trash)"))
        self.resetButton.setText(_translate("Dialog", "Reset to default"))
        self.label_8.setText(_translate("Dialog", "Notes database directory"))
        self.autoIndentBox.setText(_translate("Dialog", "Enable automatic indenting"))
        self.deleteEmptyNotesBox.setText(_translate("Dialog", "Delete empty notes"))
        self.minimizeBox.setText(_translate("Dialog", "Minimize on startup"))
        self.hotkeyBox.setText(_translate("Dialog", "Enable hotkeys"))
        self.groupBox_2.setTitle(_translate("Dialog", "Title format"))
        self.label_4.setText(_translate("Dialog", "Text default name"))
        self.label_5.setText(_translate("Dialog", "Image default name"))
        self.label_27.setText(_translate("Dialog", "Text title format"))
        self.nameFormatTextLine.setToolTip(_translate("Dialog", "Translatables variables:\n"
"%fullname%, %shortname%\n"
"%folder%, %path%\n"
"%extension%, %size%"))
        self.label_28.setText(_translate("Dialog", "Image title format"))
        self.nameFormatImageLine.setToolTip(_translate("Dialog", "Translatables variables:\n"
"%fullname%, %shortname%\n"
"%folder%, %path%\n"
"%extension%, %size%"))
        self.label_2.setText(_translate("Dialog", "Command"))
        self.label.setText(_translate("Dialog", "Action"))
        self.actionTree.headerItem().setText(0, _translate("Dialog", "Trigger"))
        self.actionTree.headerItem().setText(1, _translate("Dialog", "Action"))
        self.actionTree.headerItem().setText(2, _translate("Dialog", "Command"))
        self.actionSaveButton.setText(_translate("Dialog", "Save"))
        self.groupBox_4.setTitle(_translate("Dialog", "Fetch options"))
        self.fetchUrlBox.setText(_translate("Dialog", "Fetch image from URL (cause slow downs)"))
        self.fetchFileBox.setText(_translate("Dialog", "Fetch image from file"))
        self.fetchTxtBox.setText(_translate("Dialog", "Fetch text from file (*.txt)"))
        self.fetchClearBox.setText(_translate("Dialog", "Clear clipboard after fetch"))
        self.fetchResizeBox.setText(_translate("Dialog", "Resize images larger than screen"))
        self.hotkeyAddButton.setText(_translate("Dialog", "Add"))
        self.hotkeyTree.setSortingEnabled(True)
        self.hotkeyTree.headerItem().setText(0, _translate("Dialog", "Hotkey"))
        self.hotkeyTree.headerItem().setText(1, _translate("Dialog", "Action"))
        self.label_3.setText(_translate("Dialog", "Action"))
        self.label_6.setText(_translate("Dialog", "Hotkey"))
        self.hotkeyKeyLine.setPlaceholderText(_translate("Dialog", "Press any key..."))
        self.hotkeyClearButton.setText(_translate("Dialog", "Clear"))
        self.hotkeyDeleteButton.setText(_translate("Dialog", "Delete"))
        self.label_10.setText(_translate("Dialog", "Foreground"))
        self.presetDeleteButton.setText(_translate("Dialog", "Delete"))
        self.presetForegroundButton.setText(_translate("Dialog", "..."))
        self.presetNameLine.setPlaceholderText(_translate("Dialog", "Name"))
        self.label_11.setText(_translate("Dialog", "Background"))
        self.presetBackgroundButton.setText(_translate("Dialog", "..."))
        self.presetTree.headerItem().setText(0, _translate("Dialog", "Name"))
        self.presetTree.headerItem().setText(1, _translate("Dialog", "Foreground"))
        self.presetTree.headerItem().setText(2, _translate("Dialog", "Background"))
        self.presetPreviewTextEdit.setPlainText(_translate("Dialog", "Beautiful is better than ugly.\n"
"Explicit is better than implicit.\n"
"Simple is better than complex."))
        self.presetAddButton.setText(_translate("Dialog", "Add"))
        self.presetSaveButton.setText(_translate("Dialog", "Save"))
        self.framelessGroupBox.setTitle(_translate("Dialog", "Frameless mode"))
        self.framelessBorderButton.setText(_translate("Dialog", "..."))
        self.label_18.setText(_translate("Dialog", "Border color"))
        self.framelessBox.setText(_translate("Dialog", "Replace native window frame"))
        self.label_16.setText(_translate("Dialog", "Foreground"))
        self.attributesGroupBox.setTitle(_translate("Dialog", "Attributes"))
        self.stylePinBox.setText(_translate("Dialog", "Enable pin"))
        self.styleSizegripBox.setText(_translate("Dialog", "Enable size grip"))
        self.styleBackgroundButton.setText(_translate("Dialog", "..."))
        self.styleForegroundButton.setText(_translate("Dialog", "..."))
        self.label_26.setText(_translate("Dialog", "Apply to all"))
        self.label_17.setText(_translate("Dialog", "Font family"))
        self.label_13.setText(_translate("Dialog", "Font size"))
        self.label_12.setText(_translate("Dialog", "Height"))
        self.stylePreviewTextEdit.setPlainText(_translate("Dialog", "Complex is better than complicated.\n"
"Flat is better than nested.\n"
"Sparse is better than dense."))
        self.label_25.setText(_translate("Dialog", "Opacity"))
        self.label_15.setText(_translate("Dialog", "Background"))
        self.label_14.setText(_translate("Dialog", "Width"))
        self.label_24.setText(_translate("Dialog", "Current file :"))
        self.cssRefreshButton.setText(_translate("Dialog", "..."))
        self.label_20.setText(_translate("Dialog", "Available elements"))
        self.label_22.setText(_translate("Dialog", "Selected elements"))
        self.label_21.setText(_translate("Dialog", "Available elements"))
        self.label_23.setText(_translate("Dialog", "Selected elements"))

