
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-12T15:02:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "44f8ffea3c1e16e9ea3a785e405c11f8a7e02d59",
 "version": "0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
